# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aasm/all/aasm.rbi
#
# aasm-5.0.6
module AASM
  def aasm(name = nil); end
  def aasm_failed(state_machine_name, event_name, old_state, failures = nil); end
  def aasm_fire_event(state_machine_name, event_name, options, *args, &block); end
  def aasm_fired(state_machine_name, event, old_state, new_state_name, options, *args); end
  def fire_default_callbacks(event, *processed_args); end
  def fire_exit_callbacks(old_state, *processed_args); end
  def initialize_dup(other); end
  def process_args(event, from_state, *args); end
  def self.included(base); end
end
class AASM::UnknownStateMachineError < RuntimeError
end
class AASM::InvalidTransition < RuntimeError
  def event_name; end
  def failures; end
  def initialize(object, event_name, state_machine_name, failures = nil); end
  def object; end
  def originating_state; end
  def reasoning; end
  def state_machine_name; end
end
class AASM::UndefinedState < RuntimeError
end
class AASM::NoDirectAssignmentError < RuntimeError
end
class AASM::Configuration
  def column; end
  def column=(arg0); end
  def create_scopes; end
  def create_scopes=(arg0); end
  def enum; end
  def enum=(arg0); end
  def logger; end
  def logger=(arg0); end
  def namespace; end
  def namespace=(arg0); end
  def no_direct_assignment; end
  def no_direct_assignment=(arg0); end
  def requires_lock; end
  def requires_lock=(arg0); end
  def requires_new_transaction; end
  def requires_new_transaction=(arg0); end
  def self.hide_warnings; end
  def self.hide_warnings=(arg0); end
  def skip_validation_on_save; end
  def skip_validation_on_save=(arg0); end
  def use_transactions; end
  def use_transactions=(arg0); end
  def whiny_persistence; end
  def whiny_persistence=(arg0); end
  def whiny_transitions; end
  def whiny_transitions=(arg0); end
  def with_klass; end
  def with_klass=(arg0); end
end
class AASM::Base
  def after_all_events(*callbacks, &block); end
  def after_all_transactions(*callbacks, &block); end
  def after_all_transitions(*callbacks, &block); end
  def attribute_name(column_name = nil); end
  def before_all_events(*callbacks, &block); end
  def before_all_transactions(*callbacks, &block); end
  def configure(key, default_value); end
  def create_scope(name); end
  def create_scope?(name); end
  def default_column; end
  def ensure_on_all_events(*callbacks, &block); end
  def error_on_all_events(*callbacks, &block); end
  def event(name, options = nil, &block); end
  def events; end
  def from_states_for_state(state, options = nil); end
  def human_event_name(event); end
  def initial_state(new_initial_state = nil); end
  def initialize(klass, name, state_machine, options = nil, &block); end
  def interpret_state_args(args); end
  def klass; end
  def namespace; end
  def namespace?; end
  def safely_define_method(klass, method_name, method_definition); end
  def skip_instance_level_validation(event, name, aasm_name, klass); end
  def state(*args); end
  def state_machine; end
  def state_with_scope(*args); end
  def state_without_scope(*args); end
  def states; end
  def states_for_select; end
end
module DslHelper
  def add_options_from_dsl(options, valid_keys, &block); end
end
class DslHelper::Proxy
  def initialize(options, valid_keys, source); end
  def method_missing(name, *args, &block); end
  def options; end
  def options=(arg0); end
end
class AASM::InstanceBase
  def current_event; end
  def current_event=(arg0); end
  def current_state; end
  def current_state=(state); end
  def determine_state_name(state); end
  def enter_initial_state; end
  def events(options = nil, *args); end
  def fire!(event_name, *args, &block); end
  def fire(event_name, *args, &block); end
  def from_state; end
  def from_state=(arg0); end
  def human_state; end
  def initialize(instance, name = nil); end
  def may_fire_event?(name, *args); end
  def set_current_state_with_persistence(state); end
  def state_object_for_name(name); end
  def states(options = nil, *args); end
  def to_state; end
  def to_state=(arg0); end
end
module AASM::Core
end
class AASM::Core::Transition
  def ==(obj); end
  def _fire_callbacks(code, record, args); end
  def allowed?(obj, *args); end
  def event; end
  def execute(obj, *args); end
  def failures; end
  def from; end
  def from?(value); end
  def initialize(event, opts, &block); end
  def initialize_copy(orig); end
  def invoke_callbacks_compatible_with_guard(code, record, args, options = nil); end
  def invoke_success_callbacks(obj, *args); end
  def options; end
  def opts; end
  def to; end
  include DslHelper
end
class AASM::Core::Event
  def ==(event); end
  def _fire(obj, options = nil, to_state = nil, *args); end
  def attach_event_guards(definitions); end
  def clear_failed_callbacks; end
  def failed_callbacks; end
  def fire(obj, options = nil, to_state = nil, *args); end
  def fire_callbacks(callback_name, record, *args); end
  def fire_global_callbacks(callback_name, record, *args); end
  def fire_transition_callbacks(obj, *args); end
  def initialize(name, state_machine, options = nil, &block); end
  def initialize_copy(orig); end
  def invoke_callbacks(code, record, args); end
  def may_fire?(obj, to_state = nil, *args); end
  def name; end
  def options; end
  def state_machine; end
  def transitions(definitions = nil, &block); end
  def transitions_from_state(state); end
  def transitions_from_state?(state); end
  def transitions_to_state(state); end
  def transitions_to_state?(state); end
  include DslHelper
end
class AASM::Core::State
  def <=>(state); end
  def ==(state); end
  def _fire_callbacks(action, record, args); end
  def display_name; end
  def fire_callbacks(action, record, *args); end
  def for_select; end
  def human_name; end
  def initialize(name, klass, state_machine, options = nil); end
  def initialize_copy(orig); end
  def localized_name; end
  def name; end
  def options; end
  def state_machine; end
  def to_s; end
  def update(options = nil); end
end
class AASM::Core::Invoker
  def args; end
  def class_invoker; end
  def default_return_value; end
  def failures; end
  def initialize(subject, record, args); end
  def invoke; end
  def invoke_array; end
  def literal_invoker; end
  def options; end
  def proc_invoker; end
  def record; end
  def sub_invoke(new_subject); end
  def subject; end
  def with_default_return_value(value); end
  def with_failures(failures); end
  def with_options(options); end
end
module AASM::Core::Invokers
end
class AASM::Core::Invokers::BaseInvoker
  def args; end
  def failures; end
  def initialize(subject, record, args); end
  def invoke; end
  def invoke_subject; end
  def log_failure; end
  def may_invoke?; end
  def record; end
  def result; end
  def subject; end
  def with_failures(failures_buffer); end
end
class AASM::Core::Invokers::ClassInvoker < AASM::Core::Invokers::BaseInvoker
  def instance; end
  def invoke_subject; end
  def log_failure; end
  def log_method_info; end
  def log_source_location; end
  def may_invoke?; end
  def retrieve_instance; end
  def subject_arity; end
end
class AASM::Core::Invokers::LiteralInvoker < AASM::Core::Invokers::BaseInvoker
  def exec_subject; end
  def invoke_subject; end
  def log_failure; end
  def may_invoke?; end
  def record_error; end
  def subject_arity; end
end
class AASM::Core::Invokers::ProcInvoker < AASM::Core::Invokers::BaseInvoker
  def exec_proc(parameters_size); end
  def invoke_subject; end
  def log_failure; end
  def log_proc_info; end
  def log_source_location; end
  def may_invoke?; end
  def parameters_to_arity; end
  def support_parameters?; end
end
class AASM::Localizer
  def ancestors_list(klass); end
  def human_event_name(klass, event); end
  def human_state_name(klass, state); end
  def i18n_klass(klass); end
  def i18n_scope(klass); end
  def item_for(klass, state, ancestor, options = nil); end
  def translate_queue(checklist); end
end
class AASM::StateMachineStore
  def [](name); end
  def clone; end
  def initialize; end
  def keys; end
  def machine(name); end
  def machine_names; end
  def register(name, machine, force = nil); end
  def self.[](klass, fallback = nil); end
  def self.[]=(klass, overwrite = nil, state_machine = nil); end
  def self.fetch(klass, fallback = nil); end
  def self.register(klass, overwrite = nil, state_machine = nil); end
  def self.stores; end
  def self.unregister(klass); end
end
class AASM::StateMachine
  def add_event(name, options, &block); end
  def add_global_callbacks(name, *callbacks, &block); end
  def add_state(state_name, klass, options); end
  def config; end
  def config=(arg0); end
  def events; end
  def events=(arg0); end
  def global_callbacks; end
  def global_callbacks=(arg0); end
  def initial_state; end
  def initial_state=(arg0); end
  def initialize(name); end
  def initialize_copy(orig); end
  def name; end
  def name=(arg0); end
  def set_initial_state(name, options); end
  def states; end
  def states=(arg0); end
end
module AASM::Persistence
  def self.capitalize(string_or_symbol); end
  def self.constantize(string); end
  def self.include_persistence(base, type); end
  def self.load_persistence(base); end
  def self.require_persistence(type); end
end
module AASM::Persistence::Base
  def aasm_new_record?; end
  def aasm_read_state(name = nil); end
  def self.included(base); end
end
module AASM::Persistence::Base::ClassMethods
  def aasm_column(attribute_name = nil); end
end
module AASM::Persistence::PlainPersistence
  def aasm_read_state(name = nil); end
  def aasm_write_state(new_state, name = nil); end
  def aasm_write_state_without_persistence(new_state, name = nil); end
end
module AASM::ClassMethods
  def aasm(*args, &block); end
  def inherited(base); end
end
