# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activerecord-clean-db-structure/all/activerecord-clean-db-structure.rbi
#
# activerecord-clean-db-structure-82f92235563d
module ActiveRecordCleanDbStructure
end
class ActiveRecordCleanDbStructure::Railtie < Rails::Railtie
end
