# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ahoy_matey/all/ahoy_matey.rbi
#
# ahoy_matey-3.0.1
module Ahoy
  def api; end
  def api=(obj); end
  def api_only; end
  def api_only=(obj); end
  def bot_detection_version; end
  def bot_detection_version=(obj); end
  def cookie_domain; end
  def cookie_domain=(obj); end
  def cookies; end
  def cookies=(obj); end
  def exclude_method; end
  def exclude_method=(obj); end
  def geocode; end
  def geocode=(obj); end
  def job_queue; end
  def job_queue=(obj); end
  def logger; end
  def logger=(obj); end
  def mask_ips; end
  def mask_ips=(obj); end
  def max_content_length; end
  def max_content_length=(obj); end
  def max_events_per_request; end
  def max_events_per_request=(obj); end
  def preserve_callbacks; end
  def preserve_callbacks=(obj); end
  def protect_from_forgery; end
  def protect_from_forgery=(obj); end
  def quiet; end
  def quiet=(obj); end
  def self.api; end
  def self.api=(obj); end
  def self.api_only; end
  def self.api_only=(obj); end
  def self.bot_detection_version; end
  def self.bot_detection_version=(obj); end
  def self.cookie_domain; end
  def self.cookie_domain=(obj); end
  def self.cookies; end
  def self.cookies=(obj); end
  def self.exclude_method; end
  def self.exclude_method=(obj); end
  def self.geocode; end
  def self.geocode=(obj); end
  def self.job_queue; end
  def self.job_queue=(obj); end
  def self.log(message); end
  def self.logger; end
  def self.logger=(obj); end
  def self.mask_ip(ip); end
  def self.mask_ips; end
  def self.mask_ips=(obj); end
  def self.max_content_length; end
  def self.max_content_length=(obj); end
  def self.max_events_per_request; end
  def self.max_events_per_request=(obj); end
  def self.preserve_callbacks; end
  def self.preserve_callbacks=(obj); end
  def self.protect_from_forgery; end
  def self.protect_from_forgery=(obj); end
  def self.quiet; end
  def self.quiet=(obj); end
  def self.server_side_visits; end
  def self.server_side_visits=(obj); end
  def self.token_generator; end
  def self.token_generator=(obj); end
  def self.track_bots; end
  def self.track_bots=(obj); end
  def self.user_agent_parser; end
  def self.user_agent_parser=(obj); end
  def self.user_method; end
  def self.user_method=(obj); end
  def self.visit_duration; end
  def self.visit_duration=(obj); end
  def self.visitor_duration; end
  def self.visitor_duration=(obj); end
  def server_side_visits; end
  def server_side_visits=(obj); end
  def token_generator; end
  def token_generator=(obj); end
  def track_bots; end
  def track_bots=(obj); end
  def user_agent_parser; end
  def user_agent_parser=(obj); end
  def user_method; end
  def user_method=(obj); end
  def visit_duration; end
  def visit_duration=(obj); end
  def visitor_duration; end
  def visitor_duration=(obj); end
end
module Ahoy::Utils
  def self.ensure_utf8(str); end
end
class Ahoy::BaseStore
  def ahoy; end
  def authenticate(data); end
  def bot?; end
  def controller; end
  def exclude?; end
  def exclude_by_method?; end
  def generate_id; end
  def geocode(data); end
  def initialize(options); end
  def request; end
  def track_event(data); end
  def track_visit(data); end
  def user; end
  def user=(arg0); end
  def visit; end
  def visit_or_create; end
end
module Ahoy::Controller
  def ahoy; end
  def current_visit; end
  def self.included(base); end
  def set_ahoy_cookies; end
  def set_ahoy_request_store; end
  def track_ahoy_visit; end
end
class Ahoy::DatabaseStore < Ahoy::BaseStore
  def authenticate(_); end
  def event_model; end
  def geocode(data); end
  def slice_data(model, data); end
  def track_event(data); end
  def track_visit(data); end
  def unique_exception?(e); end
  def visit; end
  def visit_model; end
  def visit_or_create(started_at: nil); end
end
module Ahoy::Helper
  def amp_event(name, properties = nil); end
end
module Ahoy::Model
  def visitable(name = nil, **options); end
end
module Ahoy::QueryMethods
  extend ActiveSupport::Concern
end
module Ahoy::QueryMethods::ClassMethods
  def where_event(name, properties = nil); end
  def where_properties(properties); end
  def where_props(properties); end
end
class Ahoy::Tracker
  def api?; end
  def authenticate(user); end
  def controller; end
  def debug(message); end
  def delete_cookie(name); end
  def ensure_token(token); end
  def exclude?; end
  def existing_visit_token; end
  def existing_visitor_token; end
  def generate_id; end
  def geocode(data); end
  def initialize(**options); end
  def missing_params?; end
  def new_visit?; end
  def new_visitor?; end
  def report_exception(e); end
  def request; end
  def reset; end
  def reset_visit; end
  def set_cookie(name, value, duration = nil, use_domain = nil); end
  def set_visit_cookie; end
  def set_visitor_cookie; end
  def track(name, properties = nil, options = nil); end
  def track_visit(defer: nil, started_at: nil); end
  def trusted_time(time = nil); end
  def user; end
  def visit; end
  def visit_anonymity_set; end
  def visit_cookie; end
  def visit_header; end
  def visit_id; end
  def visit_or_create; end
  def visit_param; end
  def visit_properties; end
  def visit_token; end
  def visit_token_helper; end
  def visitor_anonymity_set; end
  def visitor_cookie; end
  def visitor_header; end
  def visitor_id; end
  def visitor_param; end
  def visitor_token; end
  def visitor_token_helper; end
end
class Ahoy::VisitProperties
  def generate; end
  def initialize(request, api:); end
  def ip; end
  def landing_page; end
  def params; end
  def referrer; end
  def request; end
  def request_properties; end
  def tech_properties; end
  def traffic_properties; end
  def utm_properties; end
end
class Ahoy::Engine < Rails::Engine
end
class ActiveRecord::Base
  extend Ahoy::Model
end
module ActiveModel::Callbacks
  include Ahoy::Model
end
