# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/anycable/all/anycable.rbi
#
# anycable-0.6.3
module AnyCable
  def self.broadcast(channel, payload); end
  def self.broadcast_adapter; end
  def self.broadcast_adapter=(adapter); end
  def self.capture_exception(&block); end
  def self.config; end
  def self.configure; end
  def self.configure_server(&block); end
  def self.connection_factory; end
  def self.connection_factory=(arg0); end
  def self.error_handlers; end
  def self.logger; end
  def self.logger=(arg0); end
  def self.middleware; end
  def self.middleware=(arg0); end
  def self.server_callbacks; end
end
module AnyCable::ExceptionsHandling
  def self.<<(block); end
  def self.add_handler(block); end
  def self.handlers; end
  def self.notify(exp, method_name, message); end
  def self.procify(block); end
end
module AnyCable::BroadcastAdapters
  def lookup_adapter(args); end
  def self.lookup_adapter(args); end
end
class AnyCable::Middleware < GRPC::Interceptor
  def call(*arg0); end
  def request_response(request: nil, call: nil, method: nil); end
end
class AnyCable::MiddlewareChain
  def build_middleware(middleware); end
  def check_frozen!; end
  def freeze; end
  def initialize; end
  def mu; end
  def registry; end
  def sync; end
  def to_a; end
  def use(middleware); end
end
class AnyCable::Socket
  def close; end
  def closed?; end
  def env; end
  def initialize(env: nil); end
  def stop_streams?; end
  def streams; end
  def subscribe(_channel, broadcasting); end
  def transmissions; end
  def transmit(websocket_message); end
  def unsubscribe(_channel, _broadcasting); end
  def unsubscribe_from_all(_channel); end
end
class AnyCable::ConnectionRequest
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
class AnyCable::ConnectionResponse
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
class AnyCable::CommandMessage
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
class AnyCable::CommandResponse
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
class AnyCable::DisconnectRequest
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
class AnyCable::DisconnectResponse
  def ==(arg0); end
  def [](arg0); end
  def []=(arg0, arg1); end
  def clone; end
  def dup; end
  def eql?(arg0); end
  def hash; end
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to_missing?(*arg0); end
  def self.decode(arg0); end
  def self.decode_json(*arg0); end
  def self.descriptor; end
  def self.encode(arg0); end
  def self.encode_json(*arg0); end
  def to_h; end
  def to_s; end
end
module AnyCable::Status
  def self.descriptor; end
  def self.lookup(arg0); end
  def self.resolve(arg0); end
end
module AnyCable::RPC
end
class AnyCable::RPC::Service
  def command(*arg0); end
  def connect(*arg0); end
  def disconnect(*arg0); end
  extend GRPC::GenericService::Dsl
  include GRPC::GenericService
end
class AnyCable::RPC::Stub < GRPC::ClientStub
  def command(req, metadata = nil); end
  def connect(req, metadata = nil); end
  def disconnect(req, metadata = nil); end
  def initialize(host, creds, **kw); end
end
class AnyCable::RPCHandler < AnyCable::RPC::Service
  def build_headers(headers); end
  def build_socket(**options); end
  def command(message, _unused_call); end
  def connect(request, _unused_call); end
  def disconnect(request, _unused_call); end
  def factory; end
  def logger; end
  def notify_exception(exp, method_name, message); end
  def rack_env(request); end
end
class AnyCable::HealthServer
  def build_server; end
  def grpc_server; end
  def initialize(grpc_server, port:, path: nil, logger: nil); end
  def logger; end
  def path; end
  def port; end
  def running?; end
  def server; end
  def start; end
  def stop; end
end
class AnyCable::Server
  def build_health_checker; end
  def build_server(options); end
  def check_default_host; end
  def grpc_server; end
  def host; end
  def initialize(host:, logger: nil, **options); end
  def logger; end
  def running?; end
  def self.start(**options); end
  def start; end
  def start_thread; end
  def stop; end
  def stopped?; end
  def wait_till_terminated; end
end
class AnyCable::Config < Anyway::Config
  def debug; end
  def debug=(arg0); end
  def debug?; end
  def http_health_path; end
  def http_health_path=(arg0); end
  def http_health_port; end
  def http_health_port=(arg0); end
  def http_health_port_provided?; end
  def log_file; end
  def log_file=(arg0); end
  def log_grpc; end
  def log_grpc=(arg0); end
  def log_level; end
  def log_level=(arg0); end
  def parse_sentinel(sentinel); end
  def redis_channel; end
  def redis_channel=(arg0); end
  def redis_sentinels; end
  def redis_sentinels=(arg0); end
  def redis_url; end
  def redis_url=(arg0); end
  def rpc_host; end
  def rpc_host=(arg0); end
  def rpc_max_waiting_requests; end
  def rpc_max_waiting_requests=(arg0); end
  def rpc_poll_period; end
  def rpc_poll_period=(arg0); end
  def rpc_pool_keep_alive; end
  def rpc_pool_keep_alive=(arg0); end
  def rpc_pool_size; end
  def rpc_pool_size=(arg0); end
  def rpc_server_args; end
  def rpc_server_args=(arg0); end
  def to_grpc_params; end
  def to_http_health_params; end
  def to_redis_params; end
end
class AnyCable::Config::DefaultHostWrapper < String
end
