# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/anycable-rails/all/anycable-rails.rbi
#
# anycable-rails-0.6.4
module AnyCable
end
module AnyCable::Rails
  def self.compatible_adapter?(adapter); end
end
class AnyCable::Config < Anyway::Config
  def access_logs_disabled; end
  def access_logs_disabled=(arg0); end
end
class AnyCable::Rails::Railtie < Rails::Railtie
end
module AnyCable::Rails::Middlewares
end
class AnyCable::Rails::Middlewares::LogTagging < AnyCable::Middleware
  def call(_request, call, _method); end
end
class AnyCable::Rails::Middlewares::Executor < AnyCable::Middleware
  def call(*arg0); end
  def executor; end
  def initialize(executor); end
end
module AnyCable::Refinements
end
module AnyCable::Refinements::Subscriptions
end
module ActionCable
end
module ActionCable::Channel
end
class ActionCable::Channel::Base
  def handle_subscribe; end
  def start_periodic_timers; end
  def stop_all_streams; end
  def stop_periodic_timers; end
  def stream_from(broadcasting, callback = nil, coder: nil); end
end
module ActionCable::Connection
end
class ActionCable::Connection::Base
  def access_logs?; end
  def fetch_identifier(name); end
  def fetch_ltags; end
  def handle_channel_command(identifier, command, data); end
  def identifiers_hash; end
  def identifiers_json; end
  def ids; end
  def ltags; end
  def reject_request; end
  def self.call(socket, **options); end
  def self.identified_by(*identifiers); end
  def socket; end
  def verify_origin!; end
end
class AnyCable::CompatibilityError < StandardError
end
module AnyCable::Compatibility
end
