# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/anyway_config/all/anyway_config.rbi
#
# anyway_config-2.0.0.pre
module Anyway
  def self.env; end
end
class Anyway::OptionParserBuilder
  def self.call(options); end
  def self.option_parser_on_args(key, flag: nil, desc: nil); end
end
module Anyway::Ext
end
module Anyway::Ext::DeepDup
end
module Anyway::Ext::StringSerialize
end
module Anyway::OptparseConfig
  def option_parser; end
  def parse_options!(options); end
  def self.included(base); end
end
module Anyway::OptparseConfig::ClassMethods
  def describe_options(**hargs); end
  def extend_options(&block); end
  def flag_options(*args); end
  def ignore_options(*args); end
  def option_parser_descriptors; end
  def option_parser_extensions; end
  def option_parser_options; end
end
module Anyway::DynamicConfig
  def self.included(base); end
end
module Anyway::DynamicConfig::ClassMethods
  def for(name, **options); end
end
module Anyway::Ext::DeepFreeze
end
module Anyway::Ext::Hash
end
class Anyway::Config
  def clear; end
  def config_name; end
  def default_config_path(name); end
  def each_source(options); end
  def env_prefix; end
  def initialize(overrides = nil); end
  def load(overrides = nil); end
  def load_from_env(name:, env_prefix:, **_options); end
  def load_from_file(name:, config_path:, env_prefix:, **_options); end
  def load_from_sources(**options); end
  def load_from_yml(path); end
  def parse_yml(path); end
  def reload(overrides = nil); end
  def resolve_config_path(name, env_prefix); end
  def self.attr_config(*args, **hargs); end
  def self.build_config_name; end
  def self.config_attributes; end
  def self.config_name(val = nil); end
  def self.defaults; end
  def self.env_prefix(val = nil); end
  def self.explicit_config_name; end
  def self.explicit_config_name?; end
  def set_value(key, val); end
  def to_h; end
  extend Anyway::DynamicConfig::ClassMethods
  extend Anyway::OptparseConfig::ClassMethods
  include Anyway::DynamicConfig
  include Anyway::OptparseConfig
end
module Anyway::Rails
end
module Anyway::Rails::Config
  def default_config_path(name); end
  def each_source(options); end
  def load_from_credentials(name:, **_options); end
  def load_from_file(name:, config_path:, env_prefix:, **_options); end
  def load_from_local_credentials(name:); end
  def load_from_secrets(name:, **_options); end
  def load_from_sources(**options); end
end
module Anyway::Rails::Config::ClassMethods
  def defaults; end
end
class Anyway::Env
  def clear; end
  def fetch(prefix); end
  def get_hash(from, name); end
  def initialize; end
  def parse_env(prefix); end
  def set_by_path(to, path, val); end
end
class Anyway::Railtie < Rails::Railtie
end
class Anyway::Settings
  def self.use_local_files; end
  def self.use_local_files=(arg0); end
end
