# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/anyway_config/all/anyway_config.rbi
#
# anyway_config-1.4.4
module Anyway
  def self.env; end
end
module Anyway::Ext
end
module Anyway::Ext::DeepDup
end
module Anyway::Ext::DeepFreeze
end
module Anyway::Ext::Hash
end
module Anyway::Ext::StringSerialize
end
class Anyway::OptionParserBuilder
  def self.call(options); end
  def self.option_parser_on_args(key, flag: nil, desc: nil); end
end
class Anyway::Config
  def clear; end
  def config_name; end
  def config_path; end
  def default_config_path; end
  def env_part; end
  def env_prefix; end
  def initialize(name: nil, load: nil, overrides: nil); end
  def load(overrides = nil); end
  def load_from_env(config); end
  def load_from_file(config); end
  def load_from_secrets(config); end
  def load_from_sources(config = nil); end
  def option_parser; end
  def parse_options!(options); end
  def parse_yml(path); end
  def reload(overrides = nil); end
  def self.attr_config(*args, **hargs); end
  def self.config_attributes; end
  def self.config_name(val = nil); end
  def self.defaults; end
  def self.describe_options(**hargs); end
  def self.env_prefix(val = nil); end
  def self.extend_options(&block); end
  def self.flag_options(*args); end
  def self.for(name); end
  def self.ignore_options(*args); end
  def self.option_parser_descriptors; end
  def self.option_parser_extension; end
  def self.option_parser_options; end
  def self.underscore_name; end
  def set_value(key, val); end
  def to_h; end
end
class Anyway::Env
  def clear; end
  def fetch(prefix); end
  def get_hash(from, name); end
  def initialize; end
  def parse_env(prefix); end
  def set_by_path(to, path, val); end
end
