# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/aws-ses/all/aws-ses.rbi
#
# aws-ses-0.6.0
module Kernel
  def __called_from__; end
  def expirable_memoize(reload = nil, storage = nil); end
end
class Module
  def memoized(method_name); end
end
module AWS
end
module AWS::SES
  def self.authorization_header(key, alg, sig); end
  def self.encode(secret_access_key, str, urlencode = nil); end
end
class AWS::SES::Response < String
  def [](header); end
  def action; end
  def body; end
  def client_error?; end
  def code; end
  def each(&block); end
  def error(reload = nil, *args, &block); end
  def error?; end
  def headers(reload = nil, *args, &block); end
  def initialize(action, response); end
  def inspect; end
  def parsed(reload = nil, *args, &block); end
  def redirect?; end
  def request_id; end
  def response; end
  def result; end
  def server_error?; end
  def success?; end
  def unmemoized_error_1567765723; end
  def unmemoized_headers_1567765723; end
  def unmemoized_parsed_1567765723; end
end
class AWS::SES::ResponseError < StandardError
  def code; end
  def initialize(response); end
  def inspect; end
  def message; end
  def response; end
end
module AWS::SES::SendEmail
  def add_array_to_hash!(hash, key, ary); end
  def build_raw_email(message, args = nil); end
  def deliver!(mail, args = nil); end
  def deliver(mail, args = nil); end
  def send_email(options = nil); end
  def send_raw_email(mail, args = nil); end
end
class AWS::SES::EmailResponse < AWS::SES::Response
  def message_id; end
  def result; end
end
class AWS::SES::SendEmailResponse < AWS::SES::EmailResponse
end
class AWS::SES::SendRawEmailResponse < AWS::SES::EmailResponse
end
module AWS::SES::Info
  def quota; end
  def statistics; end
end
class AWS::SES::GetSendQuotaResponse < AWS::SES::Response
  def max_24_hour_send; end
  def max_send_rate; end
  def result; end
  def sent_last_24_hours; end
end
class AWS::SES::GetSendStatisticsResponse < AWS::SES::Response
  def data_points; end
  def result(reload = nil, *args, &block); end
  def unmemoized_result_1567765723; end
end
class AWS::SES::Base
  def addresses; end
  def connection; end
  def get_aws_auth_param(timestamp, secret_access_key); end
  def initialize(options = nil); end
  def port; end
  def proxy_server; end
  def request(action, params = nil); end
  def server; end
  def settings; end
  def settings=(arg0); end
  def use_ssl; end
  include AWS::SES::Info
  include AWS::SES::SendEmail
end
module AWS::SES::VERSION
end
class AWS::SES::Addresses < AWS::SES::Base
  def delete(email); end
  def initialize(ses); end
  def list; end
  def verify(email); end
end
class AWS::SES::ListVerifiedEmailAddressesResponse < AWS::SES::Response
  def result(reload = nil, *args, &block); end
  def unmemoized_result_1567765723; end
end
class AWS::SES::VerifyEmailAddressResponse < AWS::SES::Response
end
class AWS::SES::DeleteVerifiedEmailAddressResponse < AWS::SES::Response
  def result; end
end
