# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/babosa/all/babosa.rbi
#
# babosa-1.0.2
module Babosa
  def self.jruby15?; end
end
module Babosa::Transliterator
  def self.get(symbol); end
end
class Babosa::Transliterator::Base
  def [](codepoint); end
  def approximations; end
  def initialize; end
  def self.allocate; end
  def self.instance; end
  def self.new(*arg0); end
  def transliterate(string); end
  extend Singleton::SingletonClassMethods
  include Singleton
end
module Babosa::UTF8
end
module Babosa::UTF8::Proxy
  def downcase(string); end
  def normalize_utf8(string); end
  def tidy_byte(byte); end
  def tidy_bytes(string); end
  def upcase(string); end
end
module Babosa::UTF8::ActiveSupportProxy
  def self.normalize_utf8(string); end
  extend ActiveSupport::Multibyte::Unicode
  extend Babosa::UTF8::ActiveSupportProxy
end
class Babosa::Identifier
  def ==(value); end
  def approximate_ascii!(*kinds); end
  def approximate_ascii(*args); end
  def clean!; end
  def clean(*args); end
  def default_normalize_options; end
  def downcase!; end
  def downcase(*args); end
  def empty?; end
  def eql?(value); end
  def initialize(string); end
  def method_missing(symbol, *args, &block); end
  def normalize!(options = nil); end
  def normalize(*args); end
  def normalize_utf8!; end
  def normalize_utf8(*args); end
  def self.utf8_proxy; end
  def self.utf8_proxy=(obj); end
  def send_to_new_instance(*args); end
  def tidy_bytes!; end
  def tidy_bytes(*args); end
  def to_ascii!; end
  def to_ascii(*args); end
  def to_identifier; end
  def to_ruby_method!(allow_bangs = nil); end
  def to_ruby_method(*args); end
  def to_s; end
  def to_slug; end
  def transliterate!(*kinds); end
  def transliterate(*args); end
  def truncate!(max); end
  def truncate(*args); end
  def truncate_bytes!(max); end
  def truncate_bytes(*args); end
  def upcase!; end
  def upcase(*args); end
  def with_dashes!(char = nil); end
  def with_dashes(*args); end
  def with_separators!(char = nil); end
  def with_separators(*args); end
  def word_chars!; end
  def word_chars(*args); end
  def wrapped_string; end
end
class Babosa::Identifier::Error < StandardError
end
class String
  def to_identifier; end
  def to_slug; end
end
