# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/components/all/components.rbi
#
# components-d46b7a32f4a3
module Components
  def self.component_names; end
  def self.components_path; end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
class Components::Element
  def __callbacks; end
  def __callbacks?; end
  def _run_validate_callbacks(&block); end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def get_instance_variable(name); end
  def initialize(view, attributes = nil, &block); end
  def initialize_attributes(attributes); end
  def initialize_elements; end
  def model_name(*args, &block); end
  def self.__callbacks; end
  def self.__callbacks=(val); end
  def self.__callbacks?; end
  def self._validate_callbacks; end
  def self._validate_callbacks=(value); end
  def self._validators; end
  def self._validators=(val); end
  def self._validators?; end
  def self.attribute(name, default: nil); end
  def self.attributes; end
  def self.define_method_or_raise(method_name, &block); end
  def self.element(name, multiple: nil, &config); end
  def self.elements; end
  def self.model_name; end
  def set_instance_variable(name, value); end
  def to_s; end
  def validation_context; end
  def validation_context=(arg0); end
  extend ActiveModel::Callbacks
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  extend ActiveModel::Validations::ClassMethods
  extend ActiveModel::Validations::HelperMethods
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  include ActiveModel::Validations
  include ActiveModel::Validations::HelperMethods
  include ActiveSupport::Callbacks
end
class Components::Component < Components::Element
  def render; end
  def self._validators; end
  def self.component_name; end
  def self.component_path; end
  def self.model_name; end
  def to_partial_path; end
end
class Components::Engine < Rails::Engine
end
class Components::Error < StandardError
end
