# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/database_validations/all/database_validations.rbi
#
# database_validations-0.9.0
module DatabaseValidations
  extend ActiveSupport::Concern
end
class DatabaseValidations::Railtie < Rails::Railtie
end
module DatabaseValidations::Checkers
end
class DatabaseValidations::Checkers::DbUniquenessValidator
  def initialize(validator); end
  def self.validate!(validator); end
  def valid_index?(columns, index); end
  def validate!; end
  def validate_index_usage!; end
  def validate_indexes!; end
  def validator; end
end
class DatabaseValidations::Checkers::DbPresenceValidator
  def initialize(validator); end
  def self.validate!(validator); end
  def validate!; end
  def validate_foreign_keys!; end
  def validator; end
end
class DatabaseValidations::DbUniquenessValidator < ActiveRecord::Validations::UniquenessValidator
  def apply_error(instance, attribute); end
  def index_name; end
  def initialize(options); end
  def klass; end
  def self.kind; end
  def validate(record); end
  def where; end
end
module DatabaseValidations::ClassMethods
  def db_belongs_to(name, scope = nil, **options); end
  def validates_db_presence_of(*attr_names); end
  def validates_db_uniqueness_of(*attr_names); end
end
class DatabaseValidations::DbPresenceValidator < ActiveRecord::Validations::PresenceValidator
  def apply_error(instance, attribute); end
  def initialize(options); end
  def klass; end
  def self.kind; end
  def validate(record); end
end
module DatabaseValidations::Storage
  def prepare(model); end
  def prepared?(model); end
  def process(validator, extractor, model); end
  def self.prepare(model); end
  def self.prepared?(model); end
  def self.process(validator, extractor, model); end
end
class DatabaseValidations::AttributeValidator < Struct
  def attribute; end
  def attribute=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def validator; end
  def validator=(_); end
end
module DatabaseValidations::KeyGenerator
  def for_db_presence(column); end
  def for_db_uniqueness(*columns); end
  def for_unique_index(index_name); end
  def generate_key(type, *args); end
  def self.for_db_presence(column); end
  def self.for_db_uniqueness(*columns); end
  def self.for_unique_index(index_name); end
  def self.generate_key(type, *args); end
  def self.unify_columns(*args); end
  def unify_columns(*args); end
end
module DatabaseValidations::UniquenessKeyExtractor
  def attribute_by_columns_keys(validator); end
  def attribute_by_indexes_keys(validator); end
  def attribute_by_key(validator); end
  def self.attribute_by_columns_keys(validator); end
  def self.attribute_by_indexes_keys(validator); end
  def self.attribute_by_key(validator); end
end
module DatabaseValidations::PresenceKeyExtractor
  def attribute_by_key(validator); end
  def self.attribute_by_key(validator); end
end
module DatabaseValidations::Validations
  def _database_validations_fallback; end
  def _database_validations_fallback=(arg0); end
  def create_or_update(*args, &block); end
  def perform_validations(options = nil); end
  def valid?(context = nil); end
  extend ActiveSupport::Concern
end
module DatabaseValidations::Errors
end
class DatabaseValidations::Errors::Base < StandardError
  def env_message; end
end
class DatabaseValidations::Errors::IndexNotFound < DatabaseValidations::Errors::Base
  def available_indexes; end
  def columns; end
  def columns_and_where_text(columns, where); end
  def index_name; end
  def initialize(columns, where_clause, index_name, available_indexes, table_name); end
  def table_name; end
  def where_clause; end
end
class DatabaseValidations::Errors::UnknownDatabase < DatabaseValidations::Errors::Base
  def database; end
  def initialize(database); end
end
class DatabaseValidations::Errors::ForeignKeyNotFound < DatabaseValidations::Errors::Base
  def column; end
  def foreign_keys; end
  def initialize(column, foreign_keys); end
end
class DatabaseValidations::Errors::UnsupportedDatabase < DatabaseValidations::Errors::Base
  def database; end
  def initialize(method, database); end
  def method; end
end
module DatabaseValidations::Rescuer
  def handled?(instance, error); end
  def process(instance, error, key_types); end
  def self.handled?(instance, error); end
  def self.process(instance, error, key_types); end
end
module DatabaseValidations::Injector
  def inject(model); end
  def self.inject(model); end
end
module DatabaseValidations::Adapters
  def factory(model); end
  def self.factory(model); end
end
class DatabaseValidations::Adapters::BaseAdapter
  def find_foreign_key_by_column(column); end
  def find_index(columns, where); end
  def find_index_by_name(index_name); end
  def foreign_keys; end
  def indexes; end
  def initialize(model); end
  def model; end
  def table_name; end
end
class DatabaseValidations::Adapters::SqliteAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(error_message); end
  def self.unique_index_name(_error_message); end
end
class DatabaseValidations::Adapters::PostgresqlAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(error_message); end
  def self.unique_index_name(error_message); end
end
class DatabaseValidations::Adapters::MysqlAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(_error_message); end
  def self.unique_index_name(error_message); end
end
class ActiveRecord::Base
  extend DatabaseValidations::ClassMethods
  include DatabaseValidations
end
