# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/database_validations/all/database_validations.rbi
#
# database_validations-0.8.10
module DatabaseValidations
  extend ActiveSupport::Concern
end
class DatabaseValidations::Railtie < Rails::Railtie
end
class DatabaseValidations::DBUniquenessValidator < ActiveRecord::Validations::UniquenessValidator
  def self.kind; end
  def validate(record); end
end
module DatabaseValidations::ClassMethods
  def db_belongs_to(name, scope = nil, **options); end
  def validates_db_uniqueness_of(*attributes); end
end
class DatabaseValidations::UniquenessOptions
  def adapter; end
  def calculated_index_name; end
  def case_sensitive; end
  def check_index_options?(index); end
  def column_key; end
  def columns; end
  def field; end
  def handle_unique_error(instance); end
  def index_columns_size(columns); end
  def index_key; end
  def index_name; end
  def initialize(field, options, adapter); end
  def message; end
  def options; end
  def raise_if_index_missed!(index); end
  def raise_if_unsupported_options!; end
  def responsible_index; end
  def scope; end
  def self.validator_options(attributes, options); end
  def where_clause; end
end
class DatabaseValidations::DBPresenceValidator < ActiveRecord::Validations::PresenceValidator
  def association; end
  def foreign_key; end
  def initialize(options); end
  def self.kind; end
  def validate(record); end
end
class DatabaseValidations::BelongsToOptions
  def adapter; end
  def column; end
  def handle_foreign_key_error(instance); end
  def initialize(column, relation, adapter); end
  def key; end
  def raise_if_foreign_key_missed!; end
  def raise_if_unsupported_database!; end
  def relation; end
  def self.validator_options(association, foreign_key); end
end
module DatabaseValidations::Rescuer
  def _database_validations_fallback; end
  def _database_validations_fallback=(arg0); end
  def create_or_update(*args, &block); end
  def perform_validations(options = nil); end
  def valid?(context = nil); end
  extend ActiveSupport::Concern
end
class DatabaseValidations::OptionsStorage
  def [](key); end
  def adapter; end
  def initialize(klass); end
  def options; end
  def push_belongs_to(field, relation); end
  def push_uniqueness(field, options); end
  def storage; end
end
module DatabaseValidations::Errors
end
class DatabaseValidations::Errors::Base < StandardError
  def env_message; end
end
class DatabaseValidations::Errors::IndexNotFound < DatabaseValidations::Errors::Base
  def available_indexes; end
  def columns; end
  def columns_and_where_text(columns, where); end
  def index_name; end
  def initialize(columns, where_clause, index_name, available_indexes, table_name); end
  def table_name; end
  def where_clause; end
end
class DatabaseValidations::Errors::UnknownDatabase < DatabaseValidations::Errors::Base
  def database; end
  def initialize(database); end
end
class DatabaseValidations::Errors::OptionIsNotSupported < DatabaseValidations::Errors::Base
  def database; end
  def initialize(option, database, supported_options); end
  def option; end
  def supported_options; end
end
class DatabaseValidations::Errors::ForeignKeyNotFound < DatabaseValidations::Errors::Base
  def column; end
  def foreign_keys; end
  def initialize(column, foreign_keys); end
end
class DatabaseValidations::Errors::UnsupportedDatabase < DatabaseValidations::Errors::Base
  def database; end
  def initialize(method, database); end
  def method; end
end
module DatabaseValidations::Helpers
  def cache_valid_method!(klass); end
  def each_options_storage(klass); end
  def generate_key(type, *args); end
  def generate_key_for_belongs_to(column); end
  def generate_key_for_uniqueness(*columns); end
  def generate_key_for_uniqueness_index(index_name); end
  def handle_error!(instance, error); end
  def handle_foreign_key_error!(instance, error); end
  def handle_unique_error!(instance, error); end
  def self.cache_valid_method!(klass); end
  def self.each_options_storage(klass); end
  def self.generate_key(type, *args); end
  def self.generate_key_for_belongs_to(column); end
  def self.generate_key_for_uniqueness(*columns); end
  def self.generate_key_for_uniqueness_index(index_name); end
  def self.handle_error!(instance, error); end
  def self.handle_foreign_key_error!(instance, error); end
  def self.handle_unique_error!(instance, error); end
  def self.storage_of(klass); end
  def self.unify_columns(*args); end
  def storage_of(klass); end
  def unify_columns(*args); end
end
module DatabaseValidations::Adapters
  def factory(model); end
  def self.factory(model); end
end
class DatabaseValidations::Adapters::BaseAdapter
  def adapter_name; end
  def find_foreign_key_by_column(column); end
  def find_index(columns, where); end
  def find_index_by_name(index_name); end
  def foreign_keys; end
  def indexes; end
  def initialize(model); end
  def model; end
  def support_option?(option_name); end
  def supported_options; end
  def table_name; end
end
class DatabaseValidations::Adapters::SqliteAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(error_message); end
  def self.unique_index_name(_error_message); end
end
class DatabaseValidations::Adapters::PostgresqlAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(error_message); end
  def self.unique_index_name(error_message); end
end
class DatabaseValidations::Adapters::MysqlAdapter < DatabaseValidations::Adapters::BaseAdapter
  def self.foreign_key_error_column(error_message); end
  def self.unique_error_columns(_error_message); end
  def self.unique_index_name(error_message); end
end
class ActiveRecord::Base
  extend DatabaseValidations::ClassMethods
  include DatabaseValidations
end
