# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/delivery_boy/all/delivery_boy.rbi
#
# delivery_boy-0.2.8
module DeliveryBoy
  def self.config; end
  def self.configure; end
  def self.deliver(value, topic:, **options); end
  def self.deliver_async!(value, topic:, **options); end
  def self.deliver_async(value, topic:, **options); end
  def self.deliver_messages; end
  def self.instance; end
  def self.logger; end
  def self.logger=(arg0); end
  def self.produce!(value, topic:, **options); end
  def self.produce(value, topic:, **options); end
  def self.shutdown; end
  def self.test_mode!; end
  def self.testing; end
end
class DeliveryBoy::Instance
  def async_producer; end
  def async_producer?; end
  def config; end
  def deliver(value, topic:, **options); end
  def deliver_async!(value, topic:, **options); end
  def deliver_messages; end
  def initialize(config, logger); end
  def kafka; end
  def logger; end
  def produce(value, topic:, **options); end
  def producer_options; end
  def shutdown; end
  def sync_producer; end
  def sync_producer?; end
end
class DeliveryBoy::Fake
  def clear; end
  def deliver(value, topic:, key: nil, partition: nil, partition_key: nil, create_time: nil); end
  def deliver_async!(value, topic:, key: nil, partition: nil, partition_key: nil, create_time: nil); end
  def deliver_messages; end
  def initialize; end
  def messages_for(topic); end
  def produce(value, topic:, key: nil, partition: nil, partition_key: nil, create_time: nil); end
  def shutdown; end
end
class DeliveryBoy::Fake::FakeMessage < Struct
  def bytesize; end
  def create_time; end
  def create_time=(_); end
  def key; end
  def key=(_); end
  def offset; end
  def offset=(_); end
  def partition; end
  def partition=(_); end
  def partition_key; end
  def partition_key=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def topic; end
  def topic=(_); end
  def value; end
  def value=(_); end
end
class DeliveryBoy::Config < KingKonf::Config
  def ack_timeout; end
  def ack_timeout=(value); end
  def brokers; end
  def brokers=(value); end
  def client_id; end
  def client_id=(value); end
  def compression_codec; end
  def compression_codec=(value); end
  def compression_threshold; end
  def compression_threshold=(value); end
  def connect_timeout; end
  def connect_timeout=(value); end
  def datadog_enabled; end
  def datadog_enabled=(value); end
  def datadog_enabled?; end
  def datadog_host; end
  def datadog_host=(value); end
  def datadog_namespace; end
  def datadog_namespace=(value); end
  def datadog_port; end
  def datadog_port=(value); end
  def datadog_tags; end
  def datadog_tags=(value); end
  def delivery_interval; end
  def delivery_interval=(value); end
  def delivery_threshold; end
  def delivery_threshold=(value); end
  def log_level; end
  def log_level=(value); end
  def max_buffer_bytesize; end
  def max_buffer_bytesize=(value); end
  def max_buffer_size; end
  def max_buffer_size=(value); end
  def max_queue_size; end
  def max_queue_size=(value); end
  def max_retries; end
  def max_retries=(value); end
  def required_acks; end
  def required_acks=(value); end
  def retry_backoff; end
  def retry_backoff=(value); end
  def sasl_gssapi_keytab; end
  def sasl_gssapi_keytab=(value); end
  def sasl_gssapi_principal; end
  def sasl_gssapi_principal=(value); end
  def sasl_over_ssl; end
  def sasl_over_ssl=(value); end
  def sasl_over_ssl?; end
  def sasl_plain_authzid; end
  def sasl_plain_authzid=(value); end
  def sasl_plain_password; end
  def sasl_plain_password=(value); end
  def sasl_plain_username; end
  def sasl_plain_username=(value); end
  def sasl_scram_mechanism; end
  def sasl_scram_mechanism=(value); end
  def sasl_scram_password; end
  def sasl_scram_password=(value); end
  def sasl_scram_username; end
  def sasl_scram_username=(value); end
  def socket_timeout; end
  def socket_timeout=(value); end
  def ssl_ca_cert; end
  def ssl_ca_cert=(value); end
  def ssl_ca_cert_file_path; end
  def ssl_ca_cert_file_path=(value); end
  def ssl_ca_certs_from_system; end
  def ssl_ca_certs_from_system=(value); end
  def ssl_ca_certs_from_system?; end
  def ssl_client_cert; end
  def ssl_client_cert=(value); end
  def ssl_client_cert_key; end
  def ssl_client_cert_key=(value); end
  def ssl_verify_hostname; end
  def ssl_verify_hostname=(value); end
  def ssl_verify_hostname?; end
end
class DeliveryBoy::Railtie < Rails::Railtie
end
