# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/device_detector/all/device_detector.rbi
#
# device_detector-1.0.2
class DeviceDetector
  def android_mobile_fragment?; end
  def android_tablet_fragment?; end
  def bot; end
  def bot?; end
  def bot_name; end
  def build_regex(src); end
  def client; end
  def device; end
  def device_brand; end
  def device_name; end
  def device_type; end
  def full_version; end
  def initialize(user_agent); end
  def known?; end
  def name; end
  def opera_tablet?; end
  def opera_tv_store?; end
  def os; end
  def os_family; end
  def os_full_version; end
  def os_name; end
  def puffin_browser?; end
  def self.cache; end
  def self.config; end
  def self.configure(&block); end
  def touch_enabled?; end
  def user_agent; end
end
class Anonymous_Struct_427 < Struct
  def regex_meta; end
  def regex_meta=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def user_agent; end
  def user_agent=(_); end
end
class DeviceDetector::MetadataExtractor < Anonymous_Struct_427
  def call; end
  def extract_metadata; end
  def metadata_string; end
  def regex; end
end
class DeviceDetector::VersionExtractor < DeviceDetector::MetadataExtractor
  def metadata_string; end
end
class DeviceDetector::ModelExtractor < DeviceDetector::MetadataExtractor
  def call; end
  def metadata_string; end
  def regex; end
end
class DeviceDetector::NameExtractor < DeviceDetector::MetadataExtractor
  def call; end
  def metadata_string; end
end
class DeviceDetector::MemoryCache
  def data; end
  def get(key); end
  def get_hit(key); end
  def get_or_set(key, value = nil); end
  def initialize(config); end
  def lock; end
  def max_keys; end
  def purge_cache; end
  def set(key, value); end
end
class Anonymous_Struct_428 < Struct
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def user_agent; end
  def user_agent=(_); end
end
class DeviceDetector::Parser < Anonymous_Struct_428
  def build_regex(src); end
  def filenames; end
  def filepaths; end
  def from_cache(key); end
  def full_version; end
  def load_regexes(file_paths); end
  def matching_regex; end
  def name; end
  def parse_regexes(path, raw_regexes); end
  def regex_meta; end
  def regexes; end
  def regexes_for(file_paths); end
  def symbolize_keys!(object); end
end
class DeviceDetector::Bot < DeviceDetector::Parser
  def bot?; end
  def filenames; end
end
class DeviceDetector::Client < DeviceDetector::Parser
  def filenames; end
  def known?; end
end
class DeviceDetector::Device < DeviceDetector::Parser
  def brand; end
  def filenames; end
  def hbbtv?; end
  def known?; end
  def matching_regex; end
  def name; end
  def parse_regexes(path, raw_regexes); end
  def regexes_for_hbbtv; end
  def regexes_other; end
  def type; end
end
class DeviceDetector::OS < DeviceDetector::Parser
  def desktop?; end
  def family; end
  def filenames; end
  def full_version; end
  def name; end
  def os_info; end
  def short_name; end
end
class InvalidName___Class_0x00___Configuration_429
  def max_cache_keys; end
  def max_cache_keys=(arg0); end
  def to_hash; end
end
