# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/digest-crc/all/digest-crc.rbi
#
# digest-crc-0.4.1
module Digest
end
class Digest::CRC < Digest::Class
  def <<(data); end
  def block_length; end
  def checksum; end
  def digest_length; end
  def finish; end
  def initialize; end
  def reset; end
  def self.checksum(data); end
  def self.pack(crc); end
  def update(data); end
  include Digest::Instance
end
class Digest::CRC32 < Digest::CRC
  def self.pack(crc); end
  def update(data); end
end
