# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/down/all/down.rbi
#
# down-4.8.1
module Down
end
class Down::ChunkedIO
  def cache; end
  def chunks_depleted?; end
  def chunks_fiber; end
  def close; end
  def closed?; end
  def data; end
  def data=(arg0); end
  def each_chunk; end
  def encoding; end
  def encoding=(arg0); end
  def eof?; end
  def find_encoding(encoding); end
  def gets(separator_or_limit = nil, limit = nil); end
  def initialize(chunks:, size: nil, on_close: nil, data: nil, rewindable: nil, encoding: nil); end
  def inspect; end
  def pos; end
  def posix?; end
  def read(length = nil, outbuf = nil); end
  def readpartial(length = nil, outbuf = nil); end
  def retrieve_chunk; end
  def rewind; end
  def rewindable?; end
  def size; end
  def size=(arg0); end
end
