# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faster_path/all/faster_path.rbi
#
# faster_path-0.3.10
module FasterPath
  def self.absolute?(*arg0); end
  def self.add_trailing_separator(*arg0); end
  def self.basename(pth, ext = nil); end
  def self.blank?(str); end
  def self.children(pth, with_directory = nil); end
  def self.children_compat(pth, with_directory = nil); end
  def self.chop_basename(*arg0); end
  def self.cleanpath_aggressive(*arg0); end
  def self.cleanpath_conservative(*arg0); end
  def self.del_trailing_separator(*arg0); end
  def self.directory?(*arg0); end
  def self.dirname(*arg0); end
  def self.entries(*arg0); end
  def self.entries_compat(*arg0); end
  def self.extname(*arg0); end
  def self.has_trailing_separator?(*arg0); end
  def self.join(*arg0); end
  def self.plus(*arg0); end
  def self.relative?(*arg0); end
  def self.relative_path_from(*arg0); end
  def self.ruby_arch_bits; end
  def self.rust_arch_bits; end
end
module Thermite
end
class Thermite::Config
end
class Thermite::Tasks < Rake::TaskLib
  def github_download_uri(_tag, version); end
end
class FasterPath::Public
  def self.basename(*arg0); end
  def self.children(*arg0); end
  def self.children_compat(*arg0); end
end
module FasterPath::Rust
  def rust_arch_bits(*args, &block); end
  def self.rust_arch_bits(*args, &block); end
  extend Fiddle::Importer
end
module FasterPath::RefineFile
end
module FasterPath::RefinePathname
end
