# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fastimage/all/fastimage.rbi
#
# fastimage-2.1.5
class FastImage
  def bytes_read; end
  def content_length; end
  def escaped_location(location); end
  def fetch_using_base64(uri); end
  def fetch_using_file_open; end
  def fetch_using_http; end
  def fetch_using_http_from_parsed_uri; end
  def fetch_using_read(readable); end
  def initialize(uri, options = nil); end
  def orientation; end
  def parse_packets(stream); end
  def parse_size; end
  def parse_size_for_bmp; end
  def parse_size_for_cur; end
  def parse_size_for_gif; end
  def parse_size_for_ico; end
  def parse_size_for_jpeg; end
  def parse_size_for_png; end
  def parse_size_for_psd; end
  def parse_size_for_svg; end
  def parse_size_for_tiff; end
  def parse_size_for_webp; end
  def parse_size_vp8; end
  def parse_size_vp8l; end
  def parse_size_vp8x; end
  def parse_type; end
  def protocol_relative_url?(url); end
  def proxy_uri; end
  def self.size(uri, options = nil); end
  def self.type(uri, options = nil); end
  def setup_http; end
  def size; end
  def type; end
end
class FastImage::FastImageException < StandardError
end
class FastImage::UnknownImageType < FastImage::FastImageException
end
class FastImage::ImageFetchFailure < FastImage::FastImageException
end
class FastImage::SizeNotFound < FastImage::FastImageException
end
class FastImage::CannotParseImage < FastImage::FastImageException
end
module FastImage::StreamUtil
  def read_byte; end
  def read_int; end
  def read_string_int; end
end
class FastImage::FiberStream
  def initialize(read_fiber); end
  def peek(n); end
  def pos; end
  def read(n); end
  def skip(n); end
  include FastImage::StreamUtil
end
class FastImage::IOStream < SimpleDelegator
  include FastImage::StreamUtil
end
class FastImage::Exif
  def get_exif_byte_order; end
  def height; end
  def initialize(stream); end
  def orientation; end
  def parse_exif; end
  def parse_exif_ifd; end
  def rotated?; end
  def width; end
end
class FastImage::Svg
  def attr_value; end
  def initialize(stream); end
  def parse_svg; end
  def width_and_height; end
end
