# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/image_processing/all/image_processing.rbi
#
# image_processing-1.9.3
module ImageProcessing
end
module ImageProcessing::Chainable
  def apply(operations); end
  def branch(loader: nil, saver: nil, operations: nil, **other_options); end
  def call(file = nil, destination: nil, **call_options); end
  def convert(format); end
  def loader(**options); end
  def method_missing(name, *args, &block); end
  def operation(name, *args, &block); end
  def saver(**options); end
  def source(file); end
end
class ImageProcessing::Builder
  def call!(**options); end
  def initialize(options); end
  def options; end
  include ImageProcessing::Chainable
end
class ImageProcessing::Pipeline
  def call(save: nil); end
  def call_processor(**options); end
  def create_tempfile; end
  def destination; end
  def destination_format; end
  def format; end
  def handle_destination; end
  def initialize(options); end
  def loader; end
  def operations; end
  def processor; end
  def saver; end
  def source; end
  def source_path; end
end
class ImageProcessing::Processor
  def custom(&block); end
  def initialize(accumulator = nil); end
  def self.accumulator(name, klass); end
  def self.apply_operation(accumulator, arg1); end
  def self.call(source:, loader:, operations:, saver:, destination: nil); end
  def self.supports_resize_on_load?; end
end
class ImageProcessing::Error < StandardError
end
module ImageProcessing::Vips
  def self.valid_image?(file); end
  extend ImageProcessing::Chainable
end
class ImageProcessing::Vips::Processor < ImageProcessing::Processor
  def composite(overlay, _mode = nil, mode: nil, gravity: nil, offset: nil, **options); end
  def convert_to_image(object, name); end
  def default_dimensions(width, height); end
  def image; end
  def remove(*args); end
  def resize_and_pad(width, height, gravity: nil, extend: nil, background: nil, alpha: nil, **options); end
  def resize_to_fill(width, height, **options); end
  def resize_to_fit(width, height, **options); end
  def resize_to_limit(width, height, **options); end
  def rotate(degrees, **options); end
  def self.load_image(path_or_image, loader: nil, autorot: nil, **options); end
  def self.save_image(image, path, saver: nil, quality: nil, **options); end
  def self.supports_resize_on_load?; end
  def set(*args); end
  def set_type(*args); end
  def set_value(*args); end
  def thumbnail(width, height, sharpen: nil, **options); end
end
module ImageProcessing::Vips::Processor::Utils
  def select_valid_loader_options(source_path, options); end
  def select_valid_options(operation_name, options); end
  def select_valid_saver_options(destination_path, options); end
  def self.select_valid_loader_options(source_path, options); end
  def self.select_valid_options(operation_name, options); end
  def self.select_valid_saver_options(destination_path, options); end
end
