# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/imgproxy/all/imgproxy.rbi
#
# imgproxy-1.0.4
module Imgproxy
  def self.config; end
  def self.configure; end
  def self.extend_active_storage!(use_s3: nil, use_gcs: nil, gcs_bucket: nil); end
  def self.extend_shrine!(host: nil, use_s3: nil); end
  def self.url_for(image, options = nil); end
end
class Imgproxy::UrlAdapters
  def adapters; end
  def add(adapter); end
  def clear!; end
  def initialize; end
  def prepend; end
  def url_of(image); end
end
class Imgproxy::UrlAdapters::ActiveStorage
  def applicable?(image); end
  def url(image); end
end
class Imgproxy::UrlAdapters::ActiveStorageS3 < Imgproxy::UrlAdapters::ActiveStorage
  def applicable?(image); end
  def url(image); end
end
class Imgproxy::UrlAdapters::ActiveStorageGCS < Imgproxy::UrlAdapters::ActiveStorage
  def applicable?(image); end
  def bucket_name; end
  def initialize(bucket_name); end
  def url(image); end
end
class Imgproxy::UrlAdapters::Shrine
  def applicable?(image); end
  def initialize(host: nil); end
  def url(image); end
end
class Imgproxy::UrlAdapters::ShrineS3 < Imgproxy::UrlAdapters::Shrine
  def applicable?(image); end
  def url(image); end
end
class Imgproxy::UrlAdapters::NotFound < StandardError; end
class Imgproxy::UrlAdapters::NotConfigured < StandardError; end
class Imgproxy::Config
  def endpoint; end
  def endpoint=(arg0); end
  def hex_key=(value); end
  def hex_salt=(value); end
  def initialize; end
  def key; end
  def key=(arg0); end
  def salt; end
  def salt=(arg0); end
  def signature_size; end
  def signature_size=(arg0); end
  def url_adapters; end
  def use_short_options; end
  def use_short_options=(arg0); end
end
class Imgproxy::Options < Hash
  def bool(value); end
  def encode_style; end
  def group_gravity_opts; end
  def group_resizing_opts; end
  def group_watermark_opts; end
  def initialize(options); end
  def trim_nils(value); end
  def typecast; end
  def wrap_array(value); end
end
class Imgproxy::Builder
  def config; end
  def initialize(options = nil); end
  def option_alias(name); end
  def processing_options; end
  def ready_to_sign?; end
  def sign_path(path); end
  def signature_key; end
  def signature_salt; end
  def signature_size; end
  def url(image); end
  def url_for(image); end
  def wrap_array(value); end
end
module Imgproxy::Extensions; end
module Imgproxy::Extensions::ActiveStorage
  def imgproxy_url(options = nil); end
end
module Imgproxy::Extensions::Shrine
  def imgproxy_url(options = nil); end
end
