# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/king_konf/all/king_konf.rbi
#
# king_konf-0.3.7
module KingKonf
end
module KingKonf::DurationDecoder
  def self.decode(value); end
end
module KingKonf::Decoder
  def boolean(value, true_values: nil, false_values: nil); end
  def duration(value, **arg1); end
  def float(value, **arg1); end
  def integer(value, **arg1); end
  def list(value, sep: nil, items: nil); end
  def string(value, **arg1); end
  def symbol(value, **arg1); end
  extend KingKonf::Decoder
end
class KingKonf::Variable
  def allowed?(value); end
  def allowed_values; end
  def boolean?; end
  def cast(value); end
  def decode(value); end
  def default; end
  def description; end
  def duration?; end
  def float?; end
  def initialize(name:, type:, default: nil, description: nil, required: nil, allowed_values: nil, options: nil); end
  def integer?; end
  def list?; end
  def name; end
  def options; end
  def required?; end
  def string?; end
  def symbol?; end
  def type; end
  def valid?(value); end
end
class KingKonf::ConfigFileLoader
  def initialize(config); end
  def load_file(path, environment = nil); end
end
class KingKonf::Config
  def decode(name, value); end
  def get(name); end
  def initialize(env: nil); end
  def load_config(config); end
  def load_env(env); end
  def load_file(path, environment = nil); end
  def self.boolean(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.desc(description); end
  def self.duration(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.env_prefix(prefix = nil); end
  def self.float(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.ignore_unknown_variables(should_ignore); end
  def self.ignore_unknown_variables?; end
  def self.integer(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.list(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.string(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.symbol(name, default: nil, required: nil, allowed_values: nil, **options); end
  def self.variable(name); end
  def self.variable?(name); end
  def self.variables; end
  def set(name, value); end
  def validate!; end
end
class KingKonf::ConfigError < StandardError
end
