# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/logidze/all/logidze.rbi
#
# logidze-0.11.0
module Logidze
  def self.append_on_undo; end
  def self.append_on_undo=(arg0); end
  def self.associations_versioning; end
  def self.associations_versioning=(arg0); end
  def self.ignore_log_data_by_default; end
  def self.ignore_log_data_by_default=(arg0); end
  def self.without_logging; end
  extend Logidze::Meta
end
class Logidze::History
  def ==(other); end
  def as_json(options = nil); end
  def build_changes(a, b); end
  def changes_to(time: nil, version: nil, data: nil, from: nil); end
  def current_ts?(time); end
  def current_version; end
  def data; end
  def diff_from(time: nil, version: nil); end
  def dup; end
  def exists_ts?(time); end
  def find_by_time(time); end
  def find_by_version(num); end
  def initialize(data); end
  def meta(*args, &block); end
  def next_version; end
  def previous_version; end
  def responsible_id(*args, &block); end
  def self.dump(object); end
  def self.load(json); end
  def size(*args, &block); end
  def time_filter(item, _, time); end
  def version; end
  def version=(val); end
  def version_filter(item, version, _); end
  def versions; end
end
class Logidze::History::Version
  def changes; end
  def data; end
  def initialize(data); end
  def meta; end
  def responsible_id; end
  def time; end
  def version; end
end
class Logidze::History::Type < ActiveModel::Type::Value
  def cast_value(value); end
  def changed_in_place?(raw_old_value, new_value); end
  def serialize(value); end
  def type; end
end
module Logidze::Deprecations
  def self.show_ts_deprecation_for(meth); end
end
module Logidze::Model
  def apply_column_diff(column, value); end
  def apply_diff(version, diff); end
  def association(name); end
  def at!(ts = nil, time: nil, version: nil); end
  def at(ts = nil, time: nil, version: nil); end
  def at_version!(version); end
  def at_version(version); end
  def build_dup(log_entry, requested_ts = nil); end
  def deleted_column?(column); end
  def deserialize_changes!(diff); end
  def deserialize_value(column, value); end
  def diff_from(ts = nil, version: nil, time: nil); end
  def log_size; end
  def logidze_past?; end
  def logidze_requested_ts; end
  def logidze_requested_ts=(arg0); end
  def parse_time(ts); end
  def redo!; end
  def reload_log_data; end
  def reset_log_data; end
  def switch_to!(version, append: nil); end
  def undo!(append: nil); end
  extend ActiveSupport::Concern
end
module Logidze::Model::ClassMethods
  def at(ts = nil, time: nil, version: nil); end
  def diff_from(ts = nil, time: nil, version: nil); end
  def has_logidze?; end
  def reset_log_data; end
  def without_logging(&block); end
end
module Logidze::VersionedAssociation
  def load_target; end
  def logidze_stale?; end
  def stale_target?; end
end
module Logidze::VersionedAssociation::CollectionAssociation
  def empty?; end
  def ids_reader; end
end
module Logidze::IgnoreLogData
  extend ActiveSupport::Concern
end
module Logidze::HasLogidze
  extend ActiveSupport::Concern
end
module Logidze::HasLogidze::ClassMethods
  def has_logidze(ignore_log_data: nil); end
  def ignores_log_data?; end
end
module Logidze::Meta
  def with_meta(meta, &block); end
  def with_responsible(responsible_id, &block); end
end
class Logidze::Meta::MetaTransaction
  def block; end
  def call_block_in_meta_context; end
  def connection(*args, &block); end
  def current_meta; end
  def initialize(meta, &block); end
  def meta; end
  def meta_stack; end
  def perform; end
  def pg_reset_meta_param(prev_meta); end
  def pg_set_meta_param(value); end
  def self.wrap_with(meta, &block); end
end
class Logidze::Engine < Rails::Engine
end
