# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mini_scheduler/all/mini_scheduler.rbi
#
# mini_scheduler-0.11.0
module MiniScheduler
  def self.before_sidekiq_web_request(&blk); end
  def self.configure; end
  def self.handle_job_exception(ex, context = nil); end
  def self.job_exception_handler(&blk); end
  def self.job_ran(&blk); end
  def self.railtie_helpers_paths; end
  def self.railtie_namespace; end
  def self.railtie_routes_url_helpers(include_path_helpers = nil); end
  def self.redis; end
  def self.redis=(r); end
  def self.skip_schedule(&blk); end
  def self.start; end
  def self.table_name_prefix; end
  def self.use_relative_model_naming?; end
end
class MiniScheduler::Engine < Rails::Engine
end
module MiniScheduler::Schedule
  def daily(options = nil); end
  def every(duration = nil); end
  def is_per_host; end
  def per_host; end
  def queue(value = nil); end
  def schedule_info; end
  def scheduled?; end
end
class MiniScheduler::ScheduleInfo
  def clear!; end
  def current_owner; end
  def current_owner=(arg0); end
  def del!; end
  def initialize(klass, manager); end
  def key; end
  def next_run; end
  def next_run=(arg0); end
  def prev_duration; end
  def prev_duration=(arg0); end
  def prev_result; end
  def prev_result=(arg0); end
  def prev_run; end
  def prev_run=(arg0); end
  def queue_key; end
  def redis; end
  def schedule!; end
  def schedule_daily!; end
  def schedule_every!; end
  def valid?; end
  def valid_daily?; end
  def valid_every?; end
  def write!; end
end
class MiniScheduler::Manager
  def blocking_tick; end
  def enable_stats; end
  def enable_stats=(arg0); end
  def ensure_schedule!(klass); end
  def get_klass(name); end
  def hostname; end
  def identity_key; end
  def initialize(options = nil); end
  def keep_alive; end
  def keep_alive_duration; end
  def lock; end
  def next_run(klass); end
  def queue; end
  def queue=(arg0); end
  def random_ratio; end
  def random_ratio=(arg0); end
  def redis; end
  def redis=(arg0); end
  def remove(klass); end
  def reschedule_orphans!; end
  def reschedule_orphans_on!(hostname = nil); end
  def schedule_info(klass); end
  def schedule_next_job(hostname = nil); end
  def self.current; end
  def self.discover_queues; end
  def self.discover_schedules; end
  def self.lock_key(queue); end
  def self.queue_key(queue, hostname = nil); end
  def self.schedule_key(klass, hostname = nil); end
  def self.seq; end
  def self.without_runner; end
  def stop!; end
  def tick; end
end
class MiniScheduler::Manager::Runner
  def attempts(n); end
  def enq(klass); end
  def hostname; end
  def initialize(manager); end
  def keep_alive; end
  def process_queue; end
  def reschedule_orphans; end
  def stop!; end
  def wait_till_done; end
end
class MiniScheduler::DistributedMutex
  def initialize(key, redis); end
  def self.redis=(redis); end
  def self.synchronize(key, redis = nil, &blk); end
  def synchronize; end
  def try_to_get_lock; end
end
class MiniScheduler::DistributedMutex::Timeout < StandardError
end
class MiniScheduler::SidekiqExceptionHandler
  extend Sidekiq::ExceptionHandler
end
