# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/moneta/all/moneta.rbi
#
# moneta-1.1.1
module Moneta
  def self.build(&block); end
  def self.new(name, options = nil); end
end
module Moneta::Adapters
end
module Moneta::OptionSupport
  def expires(expires); end
  def prefix(prefix); end
  def raw; end
  def with(options = nil, &block); end
end
module Moneta::Defaults
  def [](key); end
  def []=(key, value); end
  def close; end
  def create(key, value, options = nil); end
  def decrement(key, amount = nil, options = nil); end
  def each_key; end
  def features; end
  def fetch(key, default = nil, options = nil); end
  def fetch_values(*keys, **options); end
  def increment(key, amount = nil, options = nil); end
  def key?(key, options = nil); end
  def merge!(pairs, options = nil); end
  def self.included(base); end
  def slice(*keys, **options); end
  def supports?(feature); end
  def update(pairs, options = nil, &block); end
  def values_at(*keys, **options); end
  include Moneta::OptionSupport
end
module Moneta::Defaults::ClassMethods
  def features; end
  def not_supports(*features); end
  def supports(*features); end
end
module Moneta::NilValues
  def fetch_values(*keys, **options); end
  def merge!(pairs, options = nil); end
  def slice(*keys, **options); end
end
module Moneta::IncrementSupport
  def increment(key, amount = nil, options = nil); end
  def self.included(base); end
end
module Moneta::EachKeySupport
  def each_key; end
  def self.included(base); end
end
module Moneta::CreateSupport
  def create(key, value, options = nil); end
  def self.included(base); end
end
module Moneta::HashAdapter
  def backend; end
  def clear(options = nil); end
  def delete(key, options = nil); end
  def fetch_values(*keys, **options, &defaults); end
  def key?(key, options = nil); end
  def load(key, options = nil); end
  def merge!(pairs, options = nil, &block); end
  def slice(*keys, **options); end
  def store(key, value, options = nil); end
  def values_at(*keys, **options); end
end
module Moneta::DBMAdapter
  def close; end
  def merge!(pairs, options = nil); end
  include Moneta::HashAdapter
end
module Moneta::ExpiresSupport
  def default_expires; end
  def default_expires=(arg0); end
  def expires_at(options, default = nil); end
  def expires_value(options, default = nil); end
  def self.included(base); end
end
class Moneta::Adapters::Memory
  def initialize(options = nil); end
  extend Moneta::Defaults::ClassMethods
  include Moneta::CreateSupport
  include Moneta::Defaults
  include Moneta::EachKeySupport
  include Moneta::HashAdapter
  include Moneta::IncrementSupport
  include Moneta::NilValues
end
class Moneta::Builder
  def adapter(adapter, options = nil, &block); end
  def build; end
  def check_arity(klass, proxy, expected); end
  def initialize(&block); end
  def new_proxy(klass, *args, &block); end
  def use(proxy, options = nil, &block); end
end
class Moneta::Proxy
  def adapter; end
  def clear(options = nil); end
  def close; end
  def create(key, value, options = nil); end
  def delete(key, options = nil); end
  def each_key(&block); end
  def features; end
  def fetch_values(*keys, **options, &defaults); end
  def increment(key, amount = nil, options = nil); end
  def initialize(adapter, options = nil); end
  def key?(key, options = nil); end
  def load(key, options = nil); end
  def merge!(pairs, options = nil, &block); end
  def self.features_mask; end
  def self.not_supports(*features); end
  def slice(*keys, **options); end
  def store(key, value, options = nil); end
  def values_at(*keys, **options); end
  extend Moneta::Defaults::ClassMethods
  include Moneta::Defaults
end
class Moneta::Expires < Moneta::Proxy
  def create(key, value, options = nil); end
  def delete(key, options = nil); end
  def fetch_values(*keys, **options); end
  def initialize(adapter, options = nil); end
  def invalidate_entry(key, entry, new_expires = nil); end
  def key?(key, options = nil); end
  def load(key, options = nil); end
  def load_entry(key, options); end
  def merge!(pairs, options = nil); end
  def new_entry(value, expires); end
  def slice(*keys, **options); end
  def store(key, value, options = nil); end
  def values_at(*keys, **options); end
  def with_updates(options); end
  include Moneta::ExpiresSupport
end
class Moneta::Transformer < Moneta::Proxy
  def self.class_name(keys, values); end
  def self.compile(keys, values); end
  def self.compile_initializer(type, transformers); end
  def self.compile_key_transformer(klass, key, key_opts); end
  def self.compile_key_value_transformer(klass, key, key_opts, load, load_opts, dump, dump_opts); end
  def self.compile_transformer(transformer, var, i = nil); end
  def self.compile_validator(s); end
  def self.compile_value_transformer(klass, load, load_opts, dump, dump_opts); end
  def self.new(adapter, options = nil); end
  def self.original_new(*arg0); end
  def self.without(*options); end
end
module Moneta::Transformer::Helper
  def bunzip2(value); end
  def bzip2(value); end
  def escape(value); end
  def hmacsign(value, secret); end
  def hmacverify(value, secret); end
  def spread(value); end
  def truncate(value, maxlen); end
  def unescape(value); end
  extend Moneta::Transformer::Helper
end
