# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/name_of_person/all/name_of_person.rbi
#
# name_of_person-1.1.1
module NameOfPerson
end
class NameOfPerson::PersonName < String
  def abbreviated; end
  def encode_with(coder); end
  def familiar; end
  def first; end
  def full; end
  def initialize(first, last = nil); end
  def initials; end
  def last; end
  def mentionable; end
  def possessive; end
  def self.full(full_name); end
  def sorted; end
end
module NameOfPerson::AssignableName
  def name; end
  def name=(name); end
end
module NameOfPerson::HasPersonName
  extend ActiveSupport::Concern
end
module NameOfPerson::HasPersonName::ClassMethods
  def has_person_name; end
end
module ActiveModel::Model
  include NameOfPerson::HasPersonName
end
class ActiveRecord::Base
  extend NameOfPerson::HasPersonName::ClassMethods
  include NameOfPerson::HasPersonName
end
