# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/onebox/all/onebox.rbi
#
# onebox-1.8.92
class Sanitize
end
module Sanitize::Config
end
module Onebox
  def self.check(url, options = nil); end
  def self.has_matcher?(url); end
  def self.options; end
  def self.options=(options); end
  def self.preview(url, options = nil); end
end
class Onebox::Preview
  def cache; end
  def engine; end
  def engine_html; end
  def initialize(link, parameters = nil); end
  def options; end
  def placeholder_html; end
  def process_html(html); end
  def sanitize(html); end
  def to_s; end
end
class Onebox::Preview::InvalidURI < StandardError
end
class Onebox::StatusCheck
  def check; end
  def human_status; end
  def initialize(url, options = nil); end
  def ok?; end
  def status; end
end
class Onebox::Matcher
  def initialize(link); end
  def oneboxed; end
  def ordered_engines; end
end
module Onebox::Helpers
  def self.blank?(value); end
  def self.clean(html); end
  def self.click_to_scroll_div(width = nil, height = nil); end
  def self.fetch_content_length(location); end
  def self.fetch_html_doc(url, headers = nil); end
  def self.fetch_response(location, limit = nil, domain = nil, headers = nil); end
  def self.get(meta, attr); end
  def self.get_absolute_image_url(src, url); end
  def self.normalize_url_for_output(url); end
  def self.pretty_filesize(size); end
  def self.sanitize(value, length = nil); end
  def self.symbolize_keys(hash); end
  def self.truncate(string, length = nil); end
  def self.uri_encode(url); end
  def self.uri_query_encode(query_string); end
end
class Onebox::Helpers::DownloadTooLarge < StandardError
end
module Onebox::LayoutSupport
  def layout; end
  def self.max_text; end
  def to_html; end
end
module Onebox::FileTypeFinder
  def self.from_file_name(file_name); end
end
class Onebox::OpenGraph
  def data; end
  def extract(doc); end
  def get(attr, length = nil, sanitize = nil); end
  def get_secure_image; end
  def html_entities; end
  def initialize(doc); end
  def integer_suffixes; end
  def method_missing(attr, *args, &block); end
  def title; end
  def title_attr; end
  def url_suffixes; end
end
module Onebox::Engine
  def always_https?; end
  def cache; end
  def data; end
  def initialize(link, cache = nil, timeout = nil); end
  def link; end
  def options; end
  def options=(opt); end
  def placeholder_html; end
  def raw; end
  def record; end
  def self.engines; end
  def self.included(object); end
  def timeout; end
  def to_html; end
  def uri; end
  def url; end
end
module Onebox::Engine::StandardEmbed
  def always_https?; end
  def get_favicon; end
  def get_json_response; end
  def get_oembed; end
  def get_oembed_url; end
  def get_opengraph; end
  def get_twitter; end
  def html_doc; end
  def raw; end
  def self.add_oembed_provider(regexp, endpoint); end
  def self.add_opengraph_provider(regexp); end
  def self.oembed_providers; end
  def self.opengraph_providers; end
end
module Onebox::Engine::HTML
  def html?; end
  def http_params; end
  def raw; end
end
module Onebox::Engine::JSON
  def raw; end
end
class Onebox::Engine::AmazonOnebox
  def data; end
  def http_params; end
  def image; end
  def match; end
  def multiple_authors(authors_xpath); end
  def price; end
  def tld; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Engine::GithubIssueOnebox
  def data; end
  def match; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
module Onebox::Mixins
end
module Onebox::Mixins::GitBlobOnebox
  def self.included(klass); end
end
module Onebox::Mixins::GitBlobOnebox::InstanceMethods
  def calc_range(m, contents_lines_size); end
  def data; end
  def initialize(link, cache = nil, timeout = nil); end
  def line_number_helper(lines, start, selected); end
  def raw; end
  def removeLeadingIndentation(str); end
end
class Onebox::Engine::GithubBlobOnebox
  def raw_regexp; end
  def raw_template(m); end
  def self.git_regexp; end
  def self.onebox_name; end
  def title; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
  include Onebox::Mixins::GitBlobOnebox
  include Onebox::Mixins::GitBlobOnebox::InstanceMethods
end
class Onebox::Engine::GithubCommitOnebox
  def data; end
  def match; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::GithubGistOnebox
  def data; end
  def gist_api; end
  def gist_files; end
  def match; end
  def truncated_files?; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::GithubGistOnebox::GistFile
  def content; end
  def filename; end
  def initialize(json); end
  def language; end
  def lines; end
  def truncated?; end
end
class Onebox::Engine::GithubPullRequestOnebox
  def data; end
  def match; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::GoogleCalendarOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::GoogleDocsOnebox
  def data; end
  def doc_type; end
  def get_og_data; end
  def match; end
  def self.short_types; end
  def self.supported_endpoints; end
  def shorttype; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
end
class Onebox::Engine::GoogleMapsOnebox
  def data; end
  def follow_redirect!; end
  def initialize(url, cache = nil, timeout = nil); end
  def match_url; end
  def placeholder_html; end
  def resolve_url!; end
  def rewrite_custom_url(url, target); end
  def self.===(other); end
  def self.matches_regexp(key, regexp); end
  def streetview?; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::GooglePlayAppOnebox
  def data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Engine::ImageOnebox
  def always_https?; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::VideoOnebox
  def always_https?; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::AudioOnebox
  def always_https?; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::StackExchangeOnebox
  def always_https?; end
  def data; end
  def match; end
  def self.domains; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::TwitterStatusOnebox
  def access(*keys); end
  def avatar; end
  def client; end
  def data; end
  def get_twitter_data; end
  def likes; end
  def match; end
  def raw; end
  def retweets; end
  def timestamp; end
  def title; end
  def tweet; end
  def twitter_api_credentials_present?; end
  def twitter_data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Engine::WikimediaOnebox
  def data; end
  def match; end
  def self.priority; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::WikipediaOnebox
  def data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Oembed < Onebox::OpenGraph
  def html; end
  def initialize(response); end
end
class Onebox::Engine::YoutubeOnebox
  def embed_params; end
  def list_id; end
  def list_oembed_data; end
  def list_thumbnail_url; end
  def params; end
  def parse_timestring(string); end
  def placeholder_html; end
  def to_html; end
  def video_id; end
  def video_oembed_data; end
  def video_title; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::YoukuOnebox
  def to_html; end
  def uri; end
  def video_id; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
end
class Onebox::Engine::DoubanOnebox
  def data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Engine::WhitelistedGenericOnebox
  def article_html; end
  def card_html; end
  def data; end
  def embedded_html; end
  def generic_html; end
  def has_image?; end
  def has_text?; end
  def image_html; end
  def is_article?; end
  def is_card?; end
  def is_embedded?; end
  def is_image?; end
  def is_video?; end
  def placeholder_html; end
  def rewrite_https(html); end
  def self.===(other); end
  def self.default_html_providers; end
  def self.default_whitelist; end
  def self.host_matches(uri, list); end
  def self.html_providers; end
  def self.html_providers=(new_provs); end
  def self.https_hosts; end
  def self.probable_discourse(uri); end
  def self.probable_wordpress(uri); end
  def self.rewrites; end
  def self.rewrites=(new_list); end
  def self.twitter_label_whitelist; end
  def self.whitelist; end
  def self.whitelist=(list); end
  def to_html; end
  def video_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
  include Onebox::LayoutSupport
end
class Onebox::Engine::PubmedOnebox
  def authors_of_xml(xml); end
  def data; end
  def date_of_xml(xml); end
  def get_xml; end
  def match; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
end
class Onebox::Engine::SoundCloudOnebox
  def get_oembed_url; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::ImgurOnebox
  def album_html(og); end
  def image_html(og); end
  def is_album?; end
  def to_html; end
  def video_html(og); end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::PastebinOnebox
  def content; end
  def data; end
  def lines; end
  def paste_key; end
  def truncated?; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
end
class Onebox::Engine::SlidesOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::XkcdOnebox
  def data; end
  def match; end
  def url; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
  include Onebox::LayoutSupport
end
class Onebox::Engine::GiphyOnebox
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::GfycatOnebox
  def data; end
  def get_og_data; end
  def match; end
  def nokogiri_page; end
  def placeholder_html; end
  def self.priority; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::JSON
end
class Onebox::Engine::TypeformOnebox
  def build_typeform_src; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
end
class Onebox::Engine::VimeoOnebox
  def og_data; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::SteamStoreOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::SketchFabOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::AudioboomOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::ReplitOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::AsciinemaOnebox
  def match; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::MixcloudOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::BandCampOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::CoubOnebox
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
module Onebox::Engine::OpengraphImage
  def to_html; end
end
class Onebox::Engine::FlickrOnebox
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::OpengraphImage
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::FlickrShortenedOnebox
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::OpengraphImage
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::FiveHundredPxOnebox
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::PdfOnebox
  def data; end
  def get_pdf_info; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
end
module Onebox::Mixins::TwitchOnebox
  def self.included(klass); end
end
module Onebox::Mixins::TwitchOnebox::InstanceMethods
  def base_url; end
  def to_html; end
  def twitch_id; end
end
class Onebox::Engine::TwitchClipsOnebox
  def base_url; end
  def query_params; end
  def self.twitch_regexp; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Mixins::TwitchOnebox
  include Onebox::Mixins::TwitchOnebox::InstanceMethods
end
class Onebox::Engine::TwitchStreamOnebox
  def query_params; end
  def self.twitch_regexp; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Mixins::TwitchOnebox
  include Onebox::Mixins::TwitchOnebox::InstanceMethods
end
class Onebox::Engine::TwitchVideoOnebox
  def query_params; end
  def self.twitch_regexp; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Mixins::TwitchOnebox
  include Onebox::Mixins::TwitchOnebox::InstanceMethods
end
class Onebox::Engine::TrelloOnebox
  def match; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::WechatMpOnebox
  def data; end
  def extract_script_value(var_name); end
  def http_params; end
  def image; end
  def tld; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::HTML
  include Onebox::LayoutSupport
end
class Onebox::Engine::CloudAppOnebox
  def image_html(og); end
  def link_html(og); end
  def to_html; end
  def video_html(og); end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::WistiaOnebox
  def get_oembed_url; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::SimplecastOnebox
  def get_oembed_url; end
  def placeholder_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::InstagramOnebox
  def data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
  include Onebox::LayoutSupport
end
class Onebox::Engine::GitlabBlobOnebox
  def raw_regexp; end
  def raw_template(m); end
  def self.git_regexp; end
  def self.onebox_name; end
  def title; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::LayoutSupport
  include Onebox::Mixins::GitBlobOnebox
  include Onebox::Mixins::GitBlobOnebox::InstanceMethods
end
class Onebox::Engine::GooglePhotosOnebox
  def album_html(og); end
  def image_html(og); end
  def to_html; end
  def video_html(og); end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::KalturaOnebox
  def preview_html; end
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::RedditImageOnebox
  def to_html; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
end
class Onebox::Engine::GoogleDriveOnebox
  def data; end
  extend Onebox::Engine::ClassMethods
  include Onebox::Engine
  include Onebox::Engine::StandardEmbed
  include Onebox::LayoutSupport
end
module Onebox::Engine::ClassMethods
  def ===(other); end
  def always_https; end
  def always_https?; end
  def matches_regexp(r); end
  def onebox_name; end
  def priority; end
end
module Onebox::TemplateSupport
  def load_paths; end
  def template?(path); end
end
class Onebox::Layout < Mustache
  def cache; end
  def checksum; end
  def details; end
  def domain; end
  def initialize(name, record, cache); end
  def link; end
  def record; end
  def to_html; end
  def uri; end
  def view; end
  include Onebox::TemplateSupport
end
class Onebox::View < Mustache
  def initialize(name, record); end
  def record; end
  def to_html; end
  include Onebox::TemplateSupport
end
class Moneta::Transformer::JsonPrefixKeyJsonValue < Moneta::Transformer
  def create(key, value, options = nil); end
  def delete(key, options = nil); end
  def each_key; end
  def fetch_values(*keys, **options); end
  def increment(key, amount = nil, options = nil); end
  def initialize(adapter, options = nil); end
  def key?(key, options = nil); end
  def load(key, options = nil); end
  def merge!(pairs, options = nil); end
  def slice(*keys, **options); end
  def store(key, value, options = nil); end
  def values_at(*keys, **options); end
end
