# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/racecar/all/racecar.rbi
#
# racecar-0.5.0
module Racecar
  def self.config; end
  def self.configure; end
  def self.instrumenter; end
  def self.logger; end
  def self.logger=(logger); end
  def self.run(processor); end
end
class Racecar::Consumer
  def configure(consumer:, producer:); end
  def heartbeat; end
  def produce(value, **options); end
  def self.group_id; end
  def self.group_id=(arg0); end
  def self.max_wait_time; end
  def self.max_wait_time=(arg0); end
  def self.offset_retention_time; end
  def self.offset_retention_time=(arg0); end
  def self.subscribes_to(*topics, start_from_beginning: nil, max_bytes_per_partition: nil); end
  def self.subscriptions; end
  def teardown; end
end
class Racecar::Consumer::Subscription < Struct
  def max_bytes_per_partition; end
  def max_bytes_per_partition=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def start_from_beginning; end
  def start_from_beginning=(_); end
  def topic; end
  def topic=(_); end
end
class Racecar::Runner
  def config; end
  def consumer; end
  def initialize(processor, config:, logger:, instrumenter: nil); end
  def logger; end
  def processor; end
  def run; end
  def stop; end
end
class Racecar::Config < KingKonf::Config
  def brokers; end
  def brokers=(value); end
  def client_id; end
  def client_id=(value); end
  def connect_timeout; end
  def connect_timeout=(value); end
  def daemonize; end
  def daemonize=(value); end
  def daemonize?; end
  def datadog_enabled; end
  def datadog_enabled=(value); end
  def datadog_enabled?; end
  def datadog_host; end
  def datadog_host=(value); end
  def datadog_namespace; end
  def datadog_namespace=(value); end
  def datadog_port; end
  def datadog_port=(value); end
  def datadog_tags; end
  def datadog_tags=(value); end
  def error_handler; end
  def group_id; end
  def group_id=(value); end
  def group_id_prefix; end
  def group_id_prefix=(value); end
  def heartbeat_interval; end
  def heartbeat_interval=(value); end
  def initialize(env: nil); end
  def inspect; end
  def load_consumer_class(consumer_class); end
  def log_level; end
  def log_level=(value); end
  def logfile; end
  def logfile=(value); end
  def logger; end
  def logger=(arg0); end
  def max_bytes; end
  def max_bytes=(value); end
  def max_fetch_queue_size; end
  def max_fetch_queue_size=(value); end
  def max_pause_timeout; end
  def max_pause_timeout=(value); end
  def max_wait_time; end
  def max_wait_time=(value); end
  def offset_commit_interval; end
  def offset_commit_interval=(value); end
  def offset_commit_threshold; end
  def offset_commit_threshold=(value); end
  def offset_retention_time; end
  def offset_retention_time=(value); end
  def on_error(&handler); end
  def pause_timeout; end
  def pause_timeout=(value); end
  def pause_with_exponential_backoff; end
  def pause_with_exponential_backoff=(value); end
  def pause_with_exponential_backoff?; end
  def pidfile; end
  def pidfile=(value); end
  def producer_compression_codec; end
  def producer_compression_codec=(value); end
  def sasl_gssapi_keytab; end
  def sasl_gssapi_keytab=(value); end
  def sasl_gssapi_principal; end
  def sasl_gssapi_principal=(value); end
  def sasl_over_ssl; end
  def sasl_over_ssl=(value); end
  def sasl_over_ssl?; end
  def sasl_plain_authzid; end
  def sasl_plain_authzid=(value); end
  def sasl_plain_password; end
  def sasl_plain_password=(value); end
  def sasl_plain_username; end
  def sasl_plain_username=(value); end
  def sasl_scram_mechanism; end
  def sasl_scram_mechanism=(value); end
  def sasl_scram_password; end
  def sasl_scram_password=(value); end
  def sasl_scram_username; end
  def sasl_scram_username=(value); end
  def session_timeout; end
  def session_timeout=(value); end
  def socket_timeout; end
  def socket_timeout=(value); end
  def ssl_ca_cert; end
  def ssl_ca_cert=(value); end
  def ssl_ca_cert_file_path; end
  def ssl_ca_cert_file_path=(value); end
  def ssl_ca_certs_from_system; end
  def ssl_ca_certs_from_system=(value); end
  def ssl_ca_certs_from_system?; end
  def ssl_client_cert; end
  def ssl_client_cert=(value); end
  def ssl_client_cert_key; end
  def ssl_client_cert_key=(value); end
  def ssl_verify_hostname; end
  def ssl_verify_hostname=(value); end
  def ssl_verify_hostname?; end
  def subscriptions; end
  def subscriptions=(arg0); end
  def validate!; end
end
class Racecar::NullInstrumenter
  def self.instrument(*arg0); end
end
class Racecar::Error < StandardError
end
class Racecar::ConfigError < Racecar::Error
end
