# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/runbook/all/runbook.rbi
#
# runbook-53d8be6a4f0b
module Runbook
  def self._child_classes(mod); end
  def self._child_modules(mod); end
  def self.book(title, &block); end
  def self.books; end
  def self.config; end
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.deprecator; end
  def self.entities; end
  def self.generators; end
  def self.register(book); end
  def self.reset_configuration; end
  def self.runs; end
  def self.section(title, &block); end
  def self.statements; end
  def self.step(title = nil, &block); end
end
class Runbook::Configuration
  def enable_sudo_prompt; end
  def enable_sudo_prompt=(arg0); end
  def initialize; end
  def self._load_cli_config; end
  def self._load_global_config; end
  def self._load_project_config; end
  def self._load_user_config; end
  def self.cli_config_file; end
  def self.cli_config_file=(cli_config_file); end
  def self.load_config; end
  def self.loaded; end
  def self.loaded=(loaded); end
  def self.reconfigure; end
  def ssh_kit; end
  def ssh_kit=(arg0); end
  def use_same_sudo_password; end
  def use_same_sudo_password=(use_same_pwd); end
end
module Runbook::DSL
  def self.class(*modules); end
  def self.dsl_ivars; end
end
class Runbook::StandardError < StandardError
end
class Runbook::Runner
  def _resume_previous_pose?(metadata, pose); end
  def _stored_position(metadata); end
  def additional_metadata; end
  def book; end
  def initialize(book); end
  def run(run: nil, noop: nil, auto: nil, paranoid: nil, start_at: nil); end
end
class Runbook::Runner::ExecutionError < Runbook::StandardError
end
module Runbook::Hooks
  def _hook_index(hook_name); end
  def hooks; end
  def hooks_for(type, klass); end
  def register_hook(name, type, klass, before: nil, &block); end
end
module Runbook::Hooks::Invoker
  def _execute_after_hooks(executor, object, *args); end
  def _execute_around_hooks(executor, object, *args); end
  def _execute_before_hooks(executor, object, *args); end
  def invoke_with_hooks(executor, object, *args, &block); end
end
module Runbook::Util
end
module Runbook::Util::Repo
  def self._file(book_title); end
  def self._slug(title); end
  def self.delete(title); end
  def self.load(metadata); end
  def self.register_delete_stored_repo_hook(base); end
  def self.register_save_repo_hook(base); end
  def self.save(repo, book_title:); end
end
class Runbook::Util::StickyHash < Hash
  def [](key); end
  def []=(key, value); end
end
class Runbook::Util::Glue
  def initialize(val); end
  def val; end
  def val=(arg0); end
end
module Runbook::Util::StoredPose
  def self._file(book_title); end
  def self._slug(title); end
  def self.delete(title); end
  def self.load(metadata); end
  def self.register_delete_stored_pose_hook(base); end
  def self.register_save_pose_hook(base); end
  def self.save(repo, book_title:); end
end
class Runbook::Node
  def dynamic!; end
  def dynamic?; end
  def initialize; end
  def visited!; end
  def visited?; end
end
class Runbook::Entity < Runbook::Node
  def _render_metadata(items, item, metadata, index); end
  def _run_metadata(items, item, metadata, index); end
  def _should_retraverse?(run, metadata); end
  def _should_reverse?(run, metadata); end
  def add(item); end
  def dsl; end
  def dynamic!; end
  def initialize(title, parent: nil); end
  def items; end
  def method_missing(method, *args, &block); end
  def parent; end
  def parent=(arg0); end
  def render(view, output, metadata); end
  def respond_to?(name, include_private = nil); end
  def run(run, metadata); end
  def self.inherited(child_class); end
  def title; end
  include Runbook::Hooks::Invoker
end
class Runbook::Entity::DSL
  def initialize(parent); end
  def parent; end
end
module Runbook::Entities
end
class Runbook::Entities::Book::DSL
  def initialize(parent); end
  def parent; end
end
class Runbook::Entities::Book < Runbook::Entity
  def initialize(title); end
  def self.initial_render_metadata; end
  def self.initial_run_metadata; end
end
class Runbook::Entities::Section::DSL
  def initialize(parent); end
  def parent; end
end
class Runbook::Entities::Section < Runbook::Entity
  def initialize(title); end
end
class Runbook::Entities::Step::DSL
  def initialize(parent); end
  def parent; end
end
class Runbook::Entities::Step < Runbook::Entity
  def initialize(title = nil); end
end
class Runbook::Statement < Runbook::Node
  def parent; end
  def parent=(arg0); end
  def render(view, output, metadata); end
  def run(run, metadata); end
  include Runbook::Hooks::Invoker
end
module Runbook::Statements
end
class Runbook::Statements::Ask < Runbook::Statement
  def default; end
  def initialize(prompt, into:, default: nil); end
  def into; end
  def prompt; end
end
class Runbook::Statements::Assert < Runbook::Statement
  def attempts; end
  def cmd; end
  def cmd_raw; end
  def cmd_ssh_config; end
  def initialize(cmd, cmd_ssh_config: nil, cmd_raw: nil, interval: nil, timeout: nil, attempts: nil, timeout_statement: nil); end
  def interval; end
  def timeout; end
  def timeout_statement; end
end
class Runbook::Statements::Capture < Runbook::Statement
  def cmd; end
  def initialize(cmd, into:, ssh_config: nil, raw: nil, strip: nil); end
  def into; end
  def raw; end
  def ssh_config; end
  def strip; end
end
class Runbook::Statements::CaptureAll < Runbook::Statement
  def cmd; end
  def initialize(cmd, into:, ssh_config: nil, raw: nil, strip: nil); end
  def into; end
  def raw; end
  def ssh_config; end
  def strip; end
end
class Runbook::Statements::Command < Runbook::Statement
  def cmd; end
  def initialize(cmd, ssh_config: nil, raw: nil); end
  def raw; end
  def ssh_config; end
end
class Runbook::Statements::Confirm < Runbook::Statement
  def initialize(prompt); end
  def prompt; end
end
class Runbook::Statements::Description < Runbook::Statement
  def initialize(msg); end
  def msg; end
end
class Runbook::Statements::Download < Runbook::Statement
  def from; end
  def initialize(from, to: nil, ssh_config: nil, options: nil); end
  def options; end
  def ssh_config; end
  def to; end
end
class Runbook::Statements::Layout < Runbook::Statement
  def initialize(structure); end
  def structure; end
end
class Runbook::Statements::Note < Runbook::Statement
  def initialize(msg); end
  def msg; end
end
class Runbook::Statements::Notice < Runbook::Statement
  def initialize(msg); end
  def msg; end
end
class Runbook::Statements::RubyCommand < Runbook::Statement
  def block; end
  def initialize(&block); end
end
class Runbook::Statements::TmuxCommand < Runbook::Statement
  def cmd; end
  def initialize(cmd, pane); end
  def pane; end
end
class Runbook::Statements::Upload < Runbook::Statement
  def from; end
  def initialize(from, to:, ssh_config: nil, options: nil); end
  def options; end
  def ssh_config; end
  def to; end
end
class Runbook::Statements::Wait < Runbook::Statement
  def initialize(time); end
  def time; end
end
module Runbook::Helpers
end
module Runbook::Helpers::FormatHelper
  def deindent(str, padding: nil); end
end
module Runbook::Helpers::SSHKitHelper
  def _as_block(user, group, &block); end
  def _coordinator_options(ssh_config_parallelization); end
  def _servers(ssh_config_servers); end
  def _with_block(env, &block); end
  def _with_umask(umask, &block); end
  def _within_block(path, &block); end
  def find_ssh_config(object, ssh_config_method = nil); end
  def render_ssh_config_output(ssh_config); end
  def ssh_kit_command(cmd, raw: nil); end
  def ssh_kit_command_options(ssh_config); end
  def with_ssh_config(ssh_config, &exec_block); end
end
module Runbook::Helpers::TmuxHelper
  def _all_panes_exist?(stored_layout); end
  def _initialize_panes(panes_to_init, layout_panes); end
  def _kill_pane(pane_id); end
  def _layout_file(runbook_title); end
  def _new_window(name); end
  def _pager_escape_sequence; end
  def _remove_stale_layouts; end
  def _rename_window(name); end
  def _runbook_pane; end
  def _session_layout_files; end
  def _session_panes; end
  def _set_directory(directory, target); end
  def _setup_layout(structure); end
  def _setup_panes(layout_panes, panes_to_init, current_pane, structure, depth = nil); end
  def _slug(title); end
  def _split(current_pane, depth, size); end
  def _swap_panes(target_pane, source_pane); end
  def _swap_runbook_pane(panes_to_init, layout_panes); end
  def kill_all_panes(layout_panes); end
  def send_keys(command, target); end
  def setup_layout(structure, runbook_title:); end
end
module Runbook::Run
  def self._register_additional_step_whitespace_hook(base); end
  def self._register_kill_all_panes_hook(base); end
  def self.included(base); end
end
module Runbook::Run::ClassMethods
  def _handle_continue_result(result, object, metadata); end
  def _method_name(object); end
  def _step_choices(object, metadata); end
  def execute(object, metadata); end
  def past_position?(current_position, position); end
  def runbook__entities__book(object, metadata); end
  def runbook__entities__section(object, metadata); end
  def runbook__entities__step(object, metadata); end
  def runbook__statements__ask(object, metadata); end
  def runbook__statements__confirm(object, metadata); end
  def runbook__statements__description(object, metadata); end
  def runbook__statements__layout(object, metadata); end
  def runbook__statements__note(object, metadata); end
  def runbook__statements__notice(object, metadata); end
  def runbook__statements__ruby_command(object, metadata); end
  def runbook__statements__tmux_command(object, metadata); end
  def runbook__statements__wait(object, metadata); end
  def should_skip?(metadata); end
  def start_at_is_substep?(object, metadata); end
  include Runbook::Helpers::FormatHelper
  include Runbook::Helpers::TmuxHelper
  include Runbook::Hooks
end
module Runbook::Runs
end
module Runbook::Runs::SSHKit
  def self.included(base); end
  extend Runbook::Helpers::SSHKitHelper
  extend Runbook::Run::ClassMethods
  extend Runbook::Runs::SSHKit::ClassMethods
  include Runbook::Run
end
module Runbook::Runs::SSHKit::ClassMethods
  def _handle_capture(object, metadata, &block); end
  def runbook__statements__assert(object, metadata); end
  def runbook__statements__capture(object, metadata); end
  def runbook__statements__capture_all(object, metadata); end
  def runbook__statements__command(object, metadata); end
  def runbook__statements__download(object, metadata); end
  def runbook__statements__upload(object, metadata); end
end
class Runbook::Toolbox
  def ask(msg, default: nil); end
  def error(msg); end
  def exit(return_value); end
  def expand(msg, choices); end
  def initialize; end
  def output(msg); end
  def prompt; end
  def warn(msg); end
  def yes?(msg); end
end
class Runbook::Viewer
  def additional_metadata; end
  def book; end
  def generate(view: nil); end
  def initialize(book); end
end
module Runbook::View
  def self.included(base); end
end
module Runbook::View::ClassMethods
  def _method_name(object); end
  def render(object, output, metadata); end
  include Runbook::Hooks
end
module Runbook::Views
end
module Runbook::Views::Markdown
  def self.runbook__entities__book(object, output, metadata); end
  def self.runbook__entities__section(object, output, metadata); end
  def self.runbook__entities__step(object, output, metadata); end
  def self.runbook__statements__ask(object, output, metadata); end
  def self.runbook__statements__assert(object, output, metadata); end
  def self.runbook__statements__capture(object, output, metadata); end
  def self.runbook__statements__capture_all(object, output, metadata); end
  def self.runbook__statements__command(object, output, metadata); end
  def self.runbook__statements__confirm(object, output, metadata); end
  def self.runbook__statements__description(object, output, metadata); end
  def self.runbook__statements__download(object, output, metadata); end
  def self.runbook__statements__layout(object, output, metadata); end
  def self.runbook__statements__note(object, output, metadata); end
  def self.runbook__statements__notice(object, output, metadata); end
  def self.runbook__statements__ruby_command(object, output, metadata); end
  def self.runbook__statements__tmux_command(object, output, metadata); end
  def self.runbook__statements__upload(object, output, metadata); end
  def self.runbook__statements__wait(object, output, metadata); end
  extend Runbook::Helpers::FormatHelper
  extend Runbook::Helpers::SSHKitHelper
  extend Runbook::View::ClassMethods
  include Runbook::View
end
module Runbook::Generators
end
module Runbook::Generators::Base
  def self.included(base); end
  def self.set_base_options(base); end
end
module Runbook::Generators::Base::ClassMethods
  def command; end
  def description; end
  def long_description; end
  def options; end
  def usage; end
end
class Runbook::Generators::DslExtension < Thor::Group
  def self.description; end
  def self.long_description; end
  extend Runbook::Generators::Base::ClassMethods
  extend Thor::Actions::ClassMethods
  include Runbook::Generators::Base
  include Thor::Actions
end
class Runbook::Generators::Generator < Thor::Group
  def self.description; end
  def self.usage; end
  extend Runbook::Generators::Base::ClassMethods
  extend Thor::Actions::ClassMethods
  include Runbook::Generators::Base
  include Thor::Actions
end
class Runbook::Generators::Project < Thor::Group
  def self.description; end
  def self.long_description; end
  extend Runbook::Generators::Base::ClassMethods
  extend Thor::Actions::ClassMethods
  include Runbook::Generators::Base
  include Thor::Actions
end
class Runbook::Generators::Runbook < Thor::Group
  def self.description; end
  def self.usage; end
  extend Runbook::Generators::Base::ClassMethods
  extend Thor::Actions::ClassMethods
  include Runbook::Generators::Base
  include Thor::Actions
end
class Runbook::Generators::Statement < Thor::Group
  def self.description; end
  extend Runbook::Generators::Base::ClassMethods
  extend Thor::Actions::ClassMethods
  include Runbook::Generators::Base
  include Thor::Actions
end
module Runbook::Extensions
end
module Runbook::Extensions::Add
end
module Runbook::Extensions::Add::DSL
  def add(entity); end
end
module Runbook::Extensions::Description
end
module Runbook::Extensions::Description::DSL
  def description(msg); end
end
module Runbook::Extensions::SharedVariables
end
module Runbook::Extensions::SharedVariables::RunHooks
  def self._copy_ivars_to_repo(object, metadata); end
  def self._eqls_method(key); end
  def self._target(object); end
  def self.register_shared_variables_hooks(base); end
end
module Runbook::Extensions::Sections
end
module Runbook::Extensions::Sections::DSL
  def section(title, &block); end
end
module Runbook::Extensions::SSHConfig
  def self.blank_ssh_config; end
  def ssh_config; end
end
module Runbook::Extensions::SSHConfig::DSL
  def env(env); end
  def group(group); end
  def parallelization(strategy:, limit: nil, wait: nil); end
  def path(path); end
  def server(server); end
  def servers(*servers); end
  def ssh_config(&block); end
  def umask(umask); end
  def user(user); end
end
module Runbook::Extensions::Statements
end
module Runbook::Extensions::Statements::DSL
  def method_missing(name, *args, &block); end
  def respond_to?(name, include_private = nil); end
  def self._statement_class(name); end
end
module Runbook::Extensions::Steps
end
module Runbook::Extensions::Steps::DSL
  def step(title = nil, &block); end
end
module Runbook::Extensions::Tmux
end
module Runbook::Extensions::Tmux::LayoutDSL
  def layout(layout); end
end
