# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/shrine/all/shrine.rbi
#
# shrine-2.19.3
class Shrine
  def self.version; end
  extend Shrine::ClassMethods
  include Shrine::InstanceMethods
end
module Shrine::VERSION
end
class Shrine::UploadedFile
  extend Shrine::UploadedFile::ClassMethods
  include Shrine::UploadedFile::InstanceMethods
end
module Shrine::UploadedFile::ClassMethods
  def inspect; end
  def shrine_class; end
  def shrine_class=(arg0); end
end
module Shrine::UploadedFile::InstanceMethods
  def ==(other); end
  def [](key); end
  def _open(**options); end
  def as_json(*args); end
  def close; end
  def content_type; end
  def data; end
  def delete; end
  def download(**options); end
  def eof?; end
  def eql?(other); end
  def exists?; end
  def extension; end
  def hash; end
  def id; end
  def initialize(data); end
  def io; end
  def metadata; end
  def mime_type; end
  def open(**options); end
  def opened?; end
  def original_filename; end
  def read(*args); end
  def replace(io, context = nil); end
  def rewind; end
  def shrine_class; end
  def size; end
  def storage; end
  def storage_key; end
  def stream(destination, **options); end
  def to_io; end
  def to_json(*args); end
  def uploader; end
  def url(**options); end
end
class Shrine::Attacher
  extend Shrine::Attacher::ClassMethods
  include Shrine::Attacher::InstanceMethods
end
module Shrine::Attacher::ClassMethods
  def inspect; end
  def shrine_class; end
  def shrine_class=(arg0); end
  def validate(&block); end
end
module Shrine::Attacher::InstanceMethods
  def _delete(uploaded_file, **options); end
  def _equalize_phase_and_action(options); end
  def _promote(uploaded_file = nil, **options); end
  def _set(uploaded_file); end
  def assign(value, **options); end
  def assign_cached(cached_file); end
  def attached?; end
  def cache!(io, **options); end
  def cache; end
  def cached?(file = nil); end
  def changed?; end
  def context; end
  def convert_after_read(value); end
  def convert_before_write(value); end
  def convert_to_data(uploaded_file); end
  def data_attribute; end
  def delete!(uploaded_file, **options); end
  def destroy; end
  def errors; end
  def finalize; end
  def get; end
  def initialize(record, name, cache: nil, store: nil); end
  def name; end
  def promote(uploaded_file = nil, **options); end
  def read; end
  def record; end
  def replace; end
  def save; end
  def set(uploaded_file); end
  def shrine_class; end
  def store!(io, **options); end
  def store; end
  def stored?(file = nil); end
  def swap(uploaded_file); end
  def update(uploaded_file); end
  def uploaded_file(object, &block); end
  def url(**options); end
  def validate; end
  def validate_block; end
  def write(value); end
end
class Shrine::Attachment < Module
  extend Shrine::Attachment::ClassMethods
  include Shrine::Attachment::InstanceMethods
end
module Shrine::Attachment::ClassMethods
  def inspect; end
  def shrine_class; end
  def shrine_class=(arg0); end
end
module Shrine::Attachment::InstanceMethods
  def attachment_name; end
  def build_attacher(object, options); end
  def define_attachment_methods!; end
  def initialize(name, **options); end
  def inspect; end
  def options; end
  def shrine_class; end
  def to_s; end
end
module Shrine::Plugins
  def self.load_plugin(name); end
  def self.register_plugin(name, mod); end
end
class Shrine::Error < StandardError
end
class Shrine::InvalidFile < Shrine::Error
  def initialize(io, missing_methods); end
end
module Shrine::ClassMethods
  def Attachment(name, *args); end
  def [](name, *args); end
  def attachment(name, *args); end
  def deprecation(message); end
  def find_storage(name); end
  def inherited(subclass); end
  def logger; end
  def logger=(arg0); end
  def opts; end
  def plugin(plugin, *args, &block); end
  def storages; end
  def storages=(arg0); end
  def upload(io, storage, context = nil); end
  def uploaded_file(object, &block); end
  def warn(message); end
  def with_file(io); end
end
module Shrine::InstanceMethods
  def _delete(uploaded_file, context); end
  def _enforce_io(io); end
  def _store(io, context); end
  def basic_location(io, metadata:); end
  def copy(io, context); end
  def delete(uploaded_file, context = nil); end
  def extract_filename(io); end
  def extract_metadata(io, context = nil); end
  def extract_mime_type(io); end
  def extract_size(io); end
  def generate_location(io, context = nil); end
  def generate_uid(io); end
  def get_location(io, context); end
  def get_metadata(io, context); end
  def initialize(storage_key); end
  def opts; end
  def process(io, context = nil); end
  def processed(io, context); end
  def put(io, context); end
  def remove(uploaded_file, context); end
  def storage; end
  def storage_key; end
  def store(io, context = nil); end
  def upload(io, context = nil); end
  def uploaded?(uploaded_file); end
end
module Shrine::Plugins::Activerecord
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::Activerecord::AttachmentMethods
  def included(model); end
end
module Shrine::Plugins::Activerecord::AttacherClassMethods
  def find_record(record_class, record_id); end
end
module Shrine::Plugins::Activerecord::AttacherMethods
  def activerecord_json_column?; end
  def convert_before_write(value); end
  def update(uploaded_file); end
end
module Shrine::Plugins::DeletePromoted
end
module Shrine::Plugins::DeletePromoted::AttacherMethods
  def promote(uploaded_file = nil, **options); end
end
module Shrine::Plugins::DeleteRaw
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::DeleteRaw::InstanceMethods
  def copy(io, context); end
  def delete_raw?; end
end
module Shrine::Storage
end
class Shrine::Storage::S3
  def bucket; end
  def clear!(&block); end
  def client; end
  def copy(io, id, **options); end
  def copyable?(io); end
  def delete(id); end
  def delete_objects(objects); end
  def deprecated_download(id, **options); end
  def deprecated_stream(id); end
  def encode_content_disposition(content_disposition); end
  def exists?(id); end
  def extract_path(io); end
  def host; end
  def initialize(bucket:, client: nil, prefix: nil, host: nil, upload_options: nil, multipart_threshold: nil, signer: nil, public: nil, **s3_options); end
  def load_data(object, **options); end
  def method_missing(name, *args, &block); end
  def object(id); end
  def open(id, rewindable: nil, **options); end
  def prefix; end
  def presign(id, method: nil, **presign_options); end
  def public; end
  def put(io, id, **options); end
  def s3; end
  def signer; end
  def upload(io, id, shrine_metadata: nil, **upload_options); end
  def upload_options; end
  def url(id, download: nil, public: nil, host: nil, **options); end
end
class Shrine::Storage::S3::Tempfile < Tempfile
  def content_type; end
  def content_type=(arg0); end
end
class Shrine::Storage::FileSystem
  def clean(path); end
  def clean?; end
  def clear!(older_than: nil, &condition); end
  def delete(id); end
  def deprecated_download(id, **options); end
  def dir_empty?(path); end
  def directory; end
  def directory_permissions; end
  def exists?(id); end
  def host; end
  def initialize(directory, prefix: nil, host: nil, clean: nil, permissions: nil, directory_permissions: nil); end
  def list_files(directory); end
  def method_missing(name, *args, &block); end
  def movable?(io, id); end
  def move(io, id, **arg2); end
  def open(id, **options, &block); end
  def path!(id); end
  def path(id); end
  def permissions; end
  def prefix; end
  def relative(path); end
  def relative_path(id); end
  def upload(io, id, move: nil, **arg3); end
  def url(id, host: nil, **options); end
end
module Shrine::Plugins::Instrumentation
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::Instrumentation::ClassMethods
  def instrument(event_name, payload = nil, &block); end
  def log_subscriber; end
  def notifications; end
  def subscribe(event_name, &subscriber); end
  def subscribers; end
end
module Shrine::Plugins::Instrumentation::InstanceMethods
  def copy(io, context); end
  def get_metadata(io, context); end
end
module Shrine::Plugins::Instrumentation::FileMethods
  def delete; end
  def exists?; end
  def open(**options); end
end
class Shrine::Plugins::Instrumentation::Notifications
  def active_support_subscribe(event_name, &block); end
  def dry_monitor_subscribe(event_name, &block); end
  def initialize(notifications); end
  def instrument(event_name, payload, &block); end
  def library_send(method_name, *args, &block); end
  def notifications; end
  def subscribe(event_name, &block); end
end
class Shrine::Plugins::Instrumentation::Event
  def [](name); end
  def active_support_duration; end
  def active_support_name; end
  def dry_events_duration; end
  def dry_events_name; end
  def duration; end
  def event; end
  def initialize(event); end
  def library_send(method_name, *args, &block); end
  def name; end
  def payload; end
end
class Shrine::Plugins::Instrumentation::LogSubscriber
  def format(properties = nil); end
  def log(message); end
  def logger; end
  def on_delete(event); end
  def on_download(event); end
  def on_exists(event); end
  def on_metadata(event); end
  def on_upload(event); end
  def self.call(event); end
end
module Shrine::Plugins::DetermineMimeType
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::DetermineMimeType::ClassMethods
  def determine_mime_type(io); end
  def instrument_mime_type(io, &block); end
  def mime_type(io); end
  def mime_type_analyzer(name); end
  def mime_type_analyzers; end
end
module Shrine::Plugins::DetermineMimeType::InstanceMethods
  def extract_mime_type(io); end
  def mime_type_analyzers; end
end
class Shrine::Plugins::DetermineMimeType::MimeTypeAnalyzer
  def call(io, options = nil); end
  def extract_filename(io); end
  def extract_with_content_type(io, options); end
  def extract_with_fastimage(io, options); end
  def extract_with_file(io, options); end
  def extract_with_filemagic(io, options); end
  def extract_with_marcel(io, options); end
  def extract_with_mime_types(io, options); end
  def extract_with_mimemagic(io, options); end
  def extract_with_mini_mime(io, options); end
  def initialize(tool); end
end
module Shrine::Plugins::StoreDimensions
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::StoreDimensions::ClassMethods
  def dimensions(io); end
  def dimensions_analyzer(name); end
  def dimensions_analyzers; end
  def extract_dimensions(io); end
  def instrument_dimensions(io, &block); end
end
module Shrine::Plugins::StoreDimensions::InstanceMethods
  def dimensions_analyzers; end
  def extract_dimensions(io); end
  def extract_metadata(io, context = nil); end
end
module Shrine::Plugins::StoreDimensions::FileMethods
  def dimensions; end
  def height; end
  def width; end
end
class Shrine::Plugins::StoreDimensions::DimensionsAnalyzer
  def call(io); end
  def extract_with_fastimage(io); end
  def extract_with_mini_magick(io); end
  def extract_with_ruby_vips(io); end
  def initialize(tool, on_error: nil); end
  def on_error(error); end
end
module Shrine::Plugins::CachedAttachmentData
end
module Shrine::Plugins::CachedAttachmentData::AttachmentMethods
  def initialize(*arg0); end
end
module Shrine::Plugins::CachedAttachmentData::AttacherMethods
  def read_cached; end
end
module Shrine::Plugins::RestoreCachedData
  def self.load_dependencies(uploader, *arg1); end
end
module Shrine::Plugins::RestoreCachedData::AttacherMethods
  def assign_cached(cached_file); end
end
module Shrine::Plugins::ValidationHelpers
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::ValidationHelpers::AttacherClassMethods
  def default_validation_messages; end
end
module Shrine::Plugins::ValidationHelpers::AttacherMethods
  def add_error(*args); end
  def error_message(type, message, object); end
  def regex(value); end
  def validate_dimensions(arg0); end
  def validate_extension(extensions, message: nil); end
  def validate_extension_exclusion(extensions, message: nil); end
  def validate_extension_inclusion(extensions, message: nil); end
  def validate_height(height_range); end
  def validate_max_dimensions(arg0, message: nil); end
  def validate_max_height(max, message: nil); end
  def validate_max_size(max, message: nil); end
  def validate_max_width(max, message: nil); end
  def validate_mime_type(types, message: nil); end
  def validate_mime_type_exclusion(types, message: nil); end
  def validate_mime_type_inclusion(types, message: nil); end
  def validate_min_dimensions(arg0, message: nil); end
  def validate_min_height(min, message: nil); end
  def validate_min_size(min, message: nil); end
  def validate_min_width(min, message: nil); end
  def validate_result(result, type, message, *args); end
  def validate_size(size_range); end
  def validate_width(width_range); end
end
module Shrine::Plugins::PrettyLocation
  def self.configure(uploader, opts = nil); end
end
module Shrine::Plugins::PrettyLocation::InstanceMethods
  def generate_location(io, context); end
  def pretty_location(io, name: nil, record: nil, version: nil, identifier: nil, metadata: nil, **arg6); end
  def record_identifier(record); end
  def record_namespace(record); end
end
module Shrine::Plugins::DerivationEndpoint
  def self.configure(uploader, opts = nil); end
  def self.load_dependencies(uploader, opts = nil); end
end
module Shrine::Plugins::DerivationEndpoint::ClassMethods
  def derivation(name, &block); end
  def derivation_endpoint(**options); end
  def derivation_options; end
  def derivation_response(env, **options); end
  def derivations; end
end
module Shrine::Plugins::DerivationEndpoint::FileMethods
  def derivation(name, *args, **options); end
  def derivation_response(name, *args, env:, **options); end
  def derivation_url(name, *args, **options); end
end
class Shrine::Derivation
  def args; end
  def default_cache_control; end
  def default_filename; end
  def default_upload_location; end
  def default_upload_storage; end
  def delete; end
  def generate(file = nil); end
  def initialize(name:, args:, source:, options:); end
  def name; end
  def option(name); end
  def options; end
  def processed; end
  def response(env); end
  def retrieve; end
  def self.option(name, default: nil, result: nil); end
  def self.options; end
  def shrine_class; end
  def source; end
  def upload(file = nil); end
  def upload_location(location); end
  def url(**options); end
end
class Shrine::Derivation::NotFound < Shrine::Error
end
class Shrine::Derivation::SourceNotFound < Shrine::Error
end
class Shrine::Derivation::Command
  def derivation; end
  def initialize(derivation); end
  def self.delegate(*names); end
  def shrine_class; end
end
class Shrine::Derivation::Url < Shrine::Derivation::Command
  def args; end
  def call(host: nil, prefix: nil, **options); end
  def identifier(expires_in: nil, version: nil, type: nil, filename: nil, disposition: nil, metadata: nil); end
  def name; end
  def plain_url(*components, params); end
  def secret_key; end
  def signed_url(url); end
  def source; end
end
class Shrine::DerivationEndpoint
  def call(env); end
  def check_expiry!(request); end
  def derivation_options; end
  def error!(status, message); end
  def expires_in(request); end
  def handle_request(request); end
  def initialize(shrine_class:, options: nil); end
  def inspect; end
  def options; end
  def secret_key; end
  def shrine_class; end
  def to_s; end
  def verify_signature!(request); end
end
class Shrine::Derivation::Response < Shrine::Derivation::Command
  def call(env); end
  def content_disposition(file); end
  def disposition; end
  def file_response(file, env); end
  def filename; end
  def local_response(env); end
  def rack_file_response(path, env); end
  def type; end
  def upload; end
  def upload_open_options; end
  def upload_redirect; end
  def upload_redirect_url_options; end
  def upload_response(env); end
end
class Shrine::Derivation::Processed < Shrine::Derivation::Command
  def call; end
  def upload; end
end
class Shrine::Derivation::Generate < Shrine::Derivation::Command
  def args; end
  def call(file = nil); end
  def derivation_block; end
  def derive(*args); end
  def download; end
  def download_errors; end
  def download_options; end
  def download_source; end
  def generate(file); end
  def include_uploaded_file; end
  def instrument_derivation(&block); end
  def name; end
  def normalize(derivative); end
  def source; end
  def uploader; end
  def with_downloaded(file, &block); end
end
class Shrine::Derivation::Upload < Shrine::Derivation::Command
  def call(derivative = nil); end
  def upload_location; end
  def upload_options; end
  def upload_storage; end
  def uploader; end
  def with_derivative(derivative); end
end
class Shrine::Derivation::Retrieve < Shrine::Derivation::Command
  def call; end
  def upload_location; end
  def upload_storage; end
end
class Shrine::Derivation::Delete < Shrine::Derivation::Command
  def call; end
  def storage; end
  def upload_location; end
  def upload_storage; end
end
class Shrine::UrlSigner
  def generate_signature(string); end
  def initialize(secret_key); end
  def secret_key; end
  def sign_url(url); end
  def verify_signature(string, signature); end
  def verify_url(url); end
end
class Shrine::UrlSigner::InvalidSignature < Shrine::Error
end
module Shrine::Plugins::AddMetadata
  def self.configure(uploader); end
end
module Shrine::Plugins::AddMetadata::ClassMethods
  def _metadata_method(name); end
  def add_metadata(name = nil, &block); end
  def metadata_method(*names); end
end
module Shrine::Plugins::AddMetadata::InstanceMethods
  def extract_custom_metadata(io, context); end
  def extract_metadata(io, context = nil); end
end
module Shrine::Plugins::AddMetadata::FileMethods
end
module Shrine::Plugins::RackResponse
end
module Shrine::Plugins::RackResponse::FileMethods
  def to_rack_response(**options); end
end
class Shrine::Plugins::RackResponse::FileResponse
  def accept_ranges(range); end
  def call(**options); end
  def content_disposition(disposition, filename); end
  def content_length(range); end
  def content_range(range); end
  def content_type(type); end
  def etag; end
  def file; end
  def initialize(file); end
  def parse_content_range(range_header); end
  def rack_body(range: nil, **arg1); end
  def rack_headers(filename: nil, type: nil, disposition: nil, range: nil); end
  def rack_status(range: nil, **arg1); end
end
class Shrine::Plugins::RackResponse::FileBody
  def close; end
  def each(&block); end
  def file; end
  def initialize(file, range: nil); end
  def method_missing(name, *args, &block); end
  def path; end
  def range; end
  def read_chunks; end
  def read_partial_chunks; end
  def respond_to_missing?(name, include_private = nil); end
end
module Shrine::Plugins::UrlsafeSerialization
end
module Shrine::Plugins::UrlsafeSerialization::ClassMethods
  def urlsafe_deserialize(string); end
  def urlsafe_serialize(hash); end
  def urlsafe_serializer; end
end
module Shrine::Plugins::UrlsafeSerialization::FileMethods
  def urlsafe_data(metadata: nil); end
  def urlsafe_dump(**options); end
end
module Shrine::Plugins::UrlsafeSerialization::FileClassMethods
  def urlsafe_dump(file, **options); end
  def urlsafe_load(string); end
end
class Shrine::Plugins::UrlsafeSerialization::Serializer
  def base64_decode(data); end
  def base64_encode(data); end
  def decode(data); end
  def encode(data); end
  def json_decode(data); end
  def json_encode(data); end
end
module Shrine::Plugins::RefreshMetadata
end
module Shrine::Plugins::RefreshMetadata::FileMethods
  def refresh_metadata!(**context); end
end
module Shrine::Plugins::Recache
end
module Shrine::Plugins::Recache::AttacherMethods
  def recache; end
  def save; end
end
