# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/shrine-memory/all/shrine-memory.rbi
#
# shrine-memory-0.3.1
class Shrine
end
module Shrine::Storage
end
class Shrine::Storage::Memory
  def clear!; end
  def delete(id); end
  def exists?(id); end
  def initialize(store = nil); end
  def open(id, *arg1); end
  def store; end
  def upload(io, id, *arg2); end
  def url(id, **options); end
end
