# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sitemap_generator/all/sitemap_generator.rbi
#
# sitemap_generator-6.0.2
module SitemapGenerator
  def self.app; end
  def self.app=(arg0); end
  def self.root; end
  def self.root=(arg0); end
  def self.templates; end
  def self.templates=(arg0); end
  def self.verbose; end
  def self.verbose=(arg0); end
  def self.yield_sitemap=(arg0); end
  def self.yield_sitemap?; end
end
class SitemapGenerator::SimpleNamer
  def initialize(base, options = nil); end
  def next; end
  def previous; end
  def reset; end
  def start?; end
  def to_s; end
end
module SitemapGenerator::Utilities
  def append_slash(path); end
  def as_array(value); end
  def assert_valid_keys(hash, *valid_keys); end
  def blank?(object); end
  def bytesize(string); end
  def clean_files; end
  def ellipsis(string, max); end
  def falsy?(value); end
  def install_sitemap_rb(verbose = nil); end
  def present?(object); end
  def reverse_merge!(hash, other_hash); end
  def reverse_merge(hash, other_hash); end
  def round(float, precision = nil); end
  def symbolize_keys!(hash); end
  def symbolize_keys(hash); end
  def titleize(string); end
  def truthy?(value); end
  def uninstall_sitemap_rb; end
  def with_warnings(flag); end
  extend SitemapGenerator::Utilities
end
module SitemapGenerator::Helpers
end
module SitemapGenerator::Helpers::NumberHelper
  def number_to_human_size(number, options = nil); end
  def number_with_delimiter(number, options = nil); end
  def number_with_precision(number, options = nil); end
end
class SitemapGenerator::Helpers::NumberHelper::InvalidNumberError < StandardError
  def initialize(number); end
  def number; end
  def number=(arg0); end
end
module SitemapGenerator::Builder
end
class SitemapGenerator::Builder::SitemapFile
  def add(link, options = nil); end
  def empty?; end
  def file_can_fit?(bytes); end
  def filesize; end
  def finalize!; end
  def finalized?; end
  def initialize(opts = nil); end
  def lastmod; end
  def link_count; end
  def location; end
  def max_sitemap_links; end
  def new; end
  def news_count; end
  def reserve_name; end
  def reserved_name?; end
  def write; end
  def written?; end
  include SitemapGenerator::Helpers::NumberHelper
end
class SitemapGenerator::Builder::SitemapIndexFile < SitemapGenerator::Builder::SitemapFile
  def add(link, options = nil); end
  def create_index?; end
  def file_can_fit?(bytes); end
  def finalize!; end
  def index_url; end
  def initialize(opts = nil); end
  def stats_summary(opts = nil); end
  def super_add(link, options = nil); end
  def total_link_count; end
  def write; end
  def write_first_sitemap; end
end
class SitemapGenerator::Builder::SitemapUrl < Hash
  def format_float(value); end
  def initialize(path, options = nil); end
  def news?; end
  def prepare_images(images, host); end
  def prepare_news(news); end
  def prepare_video_price_attribs(video); end
  def to_xml(builder = nil); end
  def w3c_date(date); end
  def yes_or_no(value); end
  def yes_or_no_with_default(value, default); end
end
class SitemapGenerator::Builder::SitemapIndexUrl < SitemapGenerator::Builder::SitemapUrl
  def initialize(path, options = nil); end
  def to_xml(builder = nil); end
end
class SitemapGenerator::Builder::LinkHolder < Struct
  def link; end
  def link=(_); end
  def options; end
  def options=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class SitemapGenerator::LinkSet
  def adapter; end
  def adapter=(arg0); end
  def add(link, options = nil); end
  def add_default_links; end
  def add_to_index(link, options = nil); end
  def create(opts = nil, &block); end
  def create_index; end
  def default_host; end
  def filename; end
  def finalize!; end
  def finalize_sitemap!; end
  def finalize_sitemap_index!; end
  def group(opts = nil, &block); end
  def include_index; end
  def include_index=(arg0); end
  def include_index?; end
  def include_root; end
  def include_root=(arg0); end
  def include_root?; end
  def initialize(options = nil); end
  def interpreter; end
  def link_count; end
  def max_sitemap_links; end
  def max_sitemap_links=(arg0); end
  def options_for_group(opts); end
  def output(string); end
  def ping_search_engines(*args); end
  def reset!; end
  def set_options(opts = nil); end
  def sitemap; end
  def sitemap_index; end
  def sitemap_index_url; end
  def sitemaps_host; end
  def sitemaps_path; end
  def verbose; end
  def verbose=(arg0); end
  def yield_sitemap; end
  def yield_sitemap=(arg0); end
  def yield_sitemap?; end
  include SitemapGenerator::LinkSet::LocationHelpers
end
module SitemapGenerator::LinkSet::LocationHelpers
  def compress; end
  def compress=(value); end
  def create_index=(value, force = nil); end
  def default_host=(value); end
  def filename=(value); end
  def namer; end
  def namer=(value); end
  def public_path; end
  def public_path=(value); end
  def search_engines; end
  def search_engines=(value); end
  def sitemap_index_location; end
  def sitemap_location; end
  def sitemaps_host=(value); end
  def sitemaps_path=(value); end
  def update_location_info(attribute, value, opts = nil); end
end
class SitemapGenerator::Templates
  def initialize(root = nil); end
  def read_template(template); end
  def sitemap_sample; end
  def sitemap_sample=(arg0); end
  def template_path(template); end
end
class SitemapGenerator::Application
  def is_at_least_rails3?; end
  def is_rails?; end
  def rails_env; end
  def rails_root; end
  def root; end
end
class SitemapGenerator::SitemapLocation < Hash
  def []=(key, value, opts = nil); end
  def adapter; end
  def directory; end
  def filename; end
  def filesize; end
  def host; end
  def initialize(opts = nil); end
  def namer; end
  def path; end
  def path_in_public; end
  def public_path; end
  def reserve_name; end
  def reserved_name?; end
  def sitemaps_path; end
  def summary(link_count); end
  def url; end
  def verbose?; end
  def with(opts = nil); end
  def write(data, link_count); end
  include SitemapGenerator::Helpers::NumberHelper
end
class SitemapGenerator::SitemapIndexLocation < SitemapGenerator::SitemapLocation
  def create_index; end
  def initialize(opts = nil); end
  def summary(link_count); end
end
class SitemapGenerator::Railtie < Rails::Railtie
end
class SitemapGenerator::SitemapError < StandardError
end
class SitemapGenerator::SitemapFullError < SitemapGenerator::SitemapError
end
class SitemapGenerator::SitemapFinalizedError < SitemapGenerator::SitemapError
end
class SitemapGenerator::FileAdapter
  def gzip(stream, data); end
  def plain(stream, data); end
  def write(location, raw_data); end
end
class SitemapGenerator::Interpreter
  def add(*args); end
  def add_to_index(*args); end
  def default_url_options; end
  def default_url_options=(val); end
  def default_url_options?; end
  def eval(opts = nil, &block); end
  def group(*args, &block); end
  def initialize(opts = nil, &block); end
  def self._routes; end
  def self.default_url_options; end
  def self.default_url_options=(val); end
  def self.default_url_options?; end
  def self.run(opts = nil, &block); end
  def sitemap; end
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_407
end
module Anonymous_Module_407
  def _generate_paths_by_default; end
  def _routes; end
  def self._routes; end
  def self.full_url_for(options); end
  def self.optimize_routes_generation?; end
  def self.polymorphic_path(record_or_hash_or_array, options = nil); end
  def self.polymorphic_url(record_or_hash_or_array, options = nil); end
  def self.route_for(name, *args); end
  def self.url_for(options); end
  def self.url_options; end
  extend ActiveSupport::Concern
  extend Anonymous_Module_408
  extend Anonymous_Module_409
  include ActionDispatch::Routing::UrlFor
  include Anonymous_Module_408
  include Anonymous_Module_409
end
class SitemapGenerator::Numeric
  def byte; end
  def bytes; end
  def exabyte; end
  def exabytes; end
  def gigabyte; end
  def gigabytes; end
  def initialize(number); end
  def kilobyte; end
  def kilobytes; end
  def megabyte; end
  def megabytes; end
  def petabyte; end
  def petabytes; end
  def terabyte; end
  def terabytes; end
end
