# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sshkey/all/sshkey.rbi
#
# sshkey-2.0.0
class SSHKey
  def bits; end
  def comment; end
  def comment=(arg0); end
  def directives; end
  def directives=(directives); end
  def dsa_private_key; end
  def dsa_public_key; end
  def encrypted_private_key; end
  def fingerprint; end
  def initialize(private_key, options = nil); end
  def key_object; end
  def md5_fingerprint; end
  def passphrase; end
  def passphrase=(arg0); end
  def private_key; end
  def public_key; end
  def randomart; end
  def rsa_private_key; end
  def rsa_public_key; end
  def self.build_ssh2_headers(headers = nil); end
  def self.decoded_key(key); end
  def self.fingerprint(key); end
  def self.fingerprint_regex; end
  def self.format_sshfp_record(hostname, type, key); end
  def self.generate(options = nil); end
  def self.md5_fingerprint(key); end
  def self.parse_ssh_public_key(public_key); end
  def self.sha1_fingerprint(key); end
  def self.sha256_fingerprint(key); end
  def self.ssh_public_key_bits(ssh_public_key); end
  def self.ssh_public_key_to_ssh2_public_key(ssh_public_key, headers = nil); end
  def self.sshfp(hostname, key); end
  def self.unpacked_byte_array(ssh_type, encoded_key); end
  def self.valid_ssh_public_key?(ssh_public_key); end
  def sha1_fingerprint; end
  def sha256_fingerprint; end
  def ssh2_public_key(headers = nil); end
  def ssh_public_key; end
  def ssh_public_key_conversion; end
  def sshfp(hostname); end
  def type; end
end
class SSHKey::PublicKeyError < StandardError
end
