# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sshkit-sudo/all/sshkit-sudo.rbi
#
# sshkit-sudo-0.1.0
module SSHKit
end
module SSHKit::Sudo
  def self.password_cache; end
end
class SSHKit::Sudo::DefaultInteractionHandler
  def on_data(command, stream_name, data, channel); end
  def password_cache_key(host); end
  def password_prompt; end
  def self.password_prompt; end
  def self.password_prompt_regexp(regexp); end
  def self.use_same_password!; end
  def self.wrong_password; end
  def self.wrong_password_regexp(regexp); end
  def wrong_password; end
end
class SSHKit::Sudo::InteractionHandler < SSHKit::Sudo::DefaultInteractionHandler
end
module SSHKit::Sudo::Backend
end
module SSHKit::Sudo::Backend::Abstract
  def create_command_and_execute!(args, options); end
  def execute!(*args); end
  def execute_command!(*args); end
  def sudo(*args); end
end
module SSHKit::Sudo::Backend::Netssh
  def execute_command!(cmd); end
end
class SSHKit::Backend::Abstract
  include SSHKit::Sudo::Backend::Abstract
end
class SSHKit::Backend::Netssh < SSHKit::Backend::Abstract
  include SSHKit::Sudo::Backend::Netssh
end
