# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/strong_migrations/all/strong_migrations.rbi
#
# strong_migrations-0.4.0
module StrongMigrations
  def self.add_check(&block); end
  def self.auto_analyze; end
  def self.auto_analyze=(arg0); end
  def self.checks; end
  def self.checks=(arg0); end
  def self.error_messages; end
  def self.error_messages=(arg0); end
  def self.start_after; end
  def self.start_after=(arg0); end
end
module StrongMigrations::DatabaseTasks
  def migrate; end
end
module StrongMigrations::Migration
  def backfill_code(table, column, default); end
  def command_str(command, args); end
  def foreign_key_str(statement, identifiers); end
  def method_missing(method, *args, &block); end
  def migrate(direction); end
  def postgresql?; end
  def postgresql_version; end
  def raise_error(message_key, header: nil, **vars); end
  def safety_assured; end
  def stop!(message, header: nil); end
  def version_safe?; end
end
class StrongMigrations::Railtie < Rails::Railtie
end
class StrongMigrations::UnsafeMigration < StandardError
end
