# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/thermite/all/thermite.rbi
#
# thermite-0.13.0
module Thermite
end
class Thermite::Config
  def binary_uri_format; end
  def cargo_shared_library; end
  def cargo_target_path(target, *path_components); end
  def cargo_toml_path; end
  def cargo_workspace_member; end
  def crate_version; end
  def debug_filename; end
  def dlext; end
  def dynamic_linker_flags; end
  def git_tag_regex; end
  def initialize(options = nil); end
  def library_name; end
  def libruby_path; end
  def rbconfig_ruby_version; end
  def ruby_extension_path; end
  def ruby_path(*path_components); end
  def ruby_toplevel_dir; end
  def ruby_version; end
  def rust_path(*path_components); end
  def rust_toplevel_dir; end
  def shared_ext; end
  def shared_library; end
  def static_extension?; end
  def tarball_filename(version); end
  def target_arch; end
  def target_os; end
  def toml; end
  def toml_config; end
end
