# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tomlrb/all/tomlrb.rbi
#
# tomlrb-1.2.8
module Tomlrb
  def self.load_file(path, **options); end
  def self.parse(string_or_io, **options); end
end
class Tomlrb::StringUtils
  def self.multiline_replacements(str); end
  def self.replace_escaped_chars(str); end
  def self.strip_spaces(str); end
end
class Tomlrb::Scanner
  def initialize(io); end
  def next_token; end
  def process_datetime; end
end
class Tomlrb::GeneratedParser < Racc::Parser
  def _reduce_10(val, _values, result); end
  def _reduce_12(val, _values, result); end
  def _reduce_13(val, _values, result); end
  def _reduce_15(val, _values, result); end
  def _reduce_16(val, _values, result); end
  def _reduce_17(val, _values, result); end
  def _reduce_18(val, _values, result); end
  def _reduce_19(val, _values, result); end
  def _reduce_20(val, _values, result); end
  def _reduce_22(val, _values, result); end
  def _reduce_23(val, _values, result); end
  def _reduce_25(val, _values, result); end
  def _reduce_27(val, _values, result); end
  def _reduce_29(val, _values, result); end
  def _reduce_30(val, _values, result); end
  def _reduce_31(val, _values, result); end
  def _reduce_32(val, _values, result); end
  def _reduce_33(val, _values, result); end
  def _reduce_34(val, _values, result); end
  def _reduce_36(val, _values, result); end
  def _reduce_38(val, _values, result); end
  def _reduce_40(val, _values, result); end
  def _reduce_41(val, _values, result); end
  def _reduce_47(val, _values, result); end
  def _reduce_48(val, _values, result); end
  def _reduce_49(val, _values, result); end
  def _reduce_50(val, _values, result); end
  def _reduce_51(val, _values, result); end
  def _reduce_52(val, _values, result); end
  def _reduce_53(val, _values, result); end
  def _reduce_54(val, _values, result); end
  def _reduce_55(val, _values, result); end
  def _reduce_7(val, _values, result); end
  def _reduce_8(val, _values, result); end
  def _reduce_9(val, _values, result); end
  def _reduce_none(val, _values, result); end
end
class Tomlrb::Parser < Tomlrb::GeneratedParser
  def initialize(tokenizer, **options); end
  def next_token; end
  def parse; end
end
class Tomlrb::Handler
  def assign(k); end
  def deal_with_array_of_tables(identifiers, is_array_of_tables); end
  def end_(type); end
  def initialize(**options); end
  def output; end
  def push(o); end
  def set_context(identifiers, is_array_of_tables: nil); end
  def start_(type); end
  def symbolize_keys; end
end
class Tomlrb::ParseError < StandardError
end
