# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/turbolinks_render/all/turbolinks_render.rbi
#
# turbolinks_render-0.9.15
module TurbolinksRender
end
module TurbolinksRender::Rendering
  def capture_turbolinks_option_to_make_it_accessible_by_middleware(options); end
  def render(*args, &block); end
  extend ActiveSupport::Concern
end
class TurbolinksRender::Middleware
  def call(env); end
  def initialize(app); end
  def render_with_turbolinks?(request, response); end
  def render_with_turbolinks_by_default?; end
end
class TurbolinksRender::Middleware::Request < Struct
  def candidate_for_turbolinks?; end
  def request; end
  def request=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def turbolinks_render_option; end
end
class TurbolinksRender::Middleware::Response < Struct
  def body; end
  def candidate_for_turbolinks?; end
  def empty?; end
  def headers; end
  def headers=(_); end
  def html_response?; end
  def js_code_to_render_html(html); end
  def response; end
  def response=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def status; end
  def status=(_); end
  def turbolinks_body; end
end
module TurbolinksRender::DebugExceptionsPatch
  def render_for_browser_request(request, wrapper); end
end
class TurbolinksRender::TurbolinksRenderMiddleware
  def call(env); end
  def initialize(app); end
end
class TurbolinksRender::Engine < Rails::Railtie
end
