# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/yabeda/all/yabeda.rbi
#
# yabeda-0.1.3
module Yabeda
  def self.adapters; end
  def self.collectors; end
  def self.groups; end
  def self.metrics; end
  def self.register_adapter(name, instance); end
  extend Yabeda::DSL::ClassMethods
  include Yabeda::DSL
end
class Yabeda::Metric
  def get(labels = nil); end
  def values; end
  extend Dry::Initializer
  include Anonymous_Module_406
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_406
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *arg1, **__dry_initializer_options__); end
  def comment; end
  def group; end
  def name; end
  def per; end
  def unit; end
  extend Dry::Initializer::Mixin::Local
end
module Anonymous_Module_407
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *arg1, **__dry_initializer_options__); end
  extend Dry::Initializer::Mixin::Local
end
class Yabeda::Counter < Yabeda::Metric
  def increment(tags, by: nil); end
  def values; end
  include Anonymous_Module_407
end
module Anonymous_Module_408
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *arg1, **__dry_initializer_options__); end
  extend Dry::Initializer::Mixin::Local
end
class Yabeda::Gauge < Yabeda::Metric
  def set(tags, value); end
  include Anonymous_Module_408
end
module Anonymous_Module_409
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *arg1, **__dry_initializer_options__); end
  def buckets; end
  extend Dry::Initializer::Mixin::Local
end
class Yabeda::Histogram < Yabeda::Metric
  def measure(tags, value); end
  include Anonymous_Module_409
end
class Yabeda::Group
  def register_metric(metric); end
  extend Dry::Initializer
  include Anonymous_Module_410
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_410
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(name, *arg1); end
  def name; end
  extend Dry::Initializer::Mixin::Local
end
module Yabeda::DSL
  def self.included(base); end
end
class Yabeda::DSL::OptionBuilder
  def kwarg?(method_name); end
  def method_missing(method_name, method_args, &_block); end
  def option_names; end
  def options_from(&block); end
  def respond_to_missing?(method_name, _args); end
  def unknown_options; end
  extend Dry::Initializer
  include Anonymous_Module_411
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_411
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(metric_klass, options, *arg2); end
  def metric_klass; end
  def options; end
  extend Dry::Initializer::Mixin::Local
end
class Yabeda::ConfigurationError < StandardError
end
class Yabeda::DSL::MetricBuilder
  def build(args, kwargs, group, &block); end
  def initialize_metric(params, options, group); end
  extend Dry::Initializer
  include Anonymous_Module_412
  include Dry::Initializer::Mixin::Root
end
module Anonymous_Module_412
  def __dry_initializer_config__; end
  def __dry_initializer_initialize__(metric_klass, *arg1); end
  def metric_klass; end
  extend Dry::Initializer::Mixin::Local
end
module Yabeda::DSL::ClassMethods
  def collect(&block); end
  def configure(&block); end
  def counter(*args, **kwargs, &block); end
  def gauge(*args, **kwargs, &block); end
  def group(group_name); end
  def histogram(*args, **kwargs, &block); end
  def register_group_for(metric); end
  def register_metric(metric); end
end
