export { default as Bold } from './bold'
export { default as Code } from './code'
export { default as Italic } from './italic'
export { default as Link } from './link'
export { default as StrikeThrough } from './strike-through'
