pipeline:
  test:
    image: gcr.io/chuspace-210609/ci:latest
    environment:
      - RAILS_ENV=test
    commands:
      - bundle install
      - yarn install
      - bin/rspec
  push:
    image: plugins/gcr
    repo: chuspace-210609/chuspace-web
    tags: ${DRONE_PULL_REQUEST}
    secrets: [google_credentials]
    when:
      branch: master


service:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chuspace_test
  redis:
    image: redis:alpine
