steps:
  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'install', '--jobs', '3', '--retry', '3', '--without', 'development,production']
    waitFor: ['-']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'BUNDLE_DISABLE_SHARED_GEMS=true'

  - name: gcr.io/chuspace-210609/ci
    waitFor: ['-']
    args: ['yarn', 'install']

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rails', 'db:schema:load']
    env:
      - 'RAILS_ENV=test'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rails', 'db:migrate']
    env:
      - 'RAILS_ENV=test'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rubocop']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  # Run tests
  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rspec']
    env:
      - 'MOBIUS_SERVICE_HOST=localhost'
      - 'MOBIUS_SERVICE_PORT=3001'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  # Build image
  - name: gcr.io/cloud-builders/docker
    id: build-image
    args: [
      'build',
      '-t', 'gcr.io/chuspace-210609/web:latest',
      '-t', 'gcr.io/chuspace-210609/web:${SHORT_SHA}',
      '--cache-from', 'gcr.io/chuspace-210609/web:latest',
      '.'
    ]
    timeout: 600s

  - name: gcr.io/cloud-builders/kubectl
    waitFor: [build-image]
    args:
      - 'set'
      - 'image'
      - 'deployment/web'
      - 'web=gcr.io/chuspace-210609/web:${SHORT_SHA}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=chuspace-staging'

  - name: gcr.io/cloud-builders/kubectl
    waitFor: [build-image]
    args:
      - 'set'
      - 'image'
      - 'deployment/worker'
      - 'worker=gcr.io/chuspace-210609/web:${SHORT_SHA}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=chuspace-staging'


substitutions:
  _DATABASE_URL: 'postgres://proxyuser:gauravrocket@35.195.162.224:5432/chuspace_test'

images:
  - 'gcr.io/chuspace-210609/web'

options:
  substitution_option: 'ALLOW_LOOSE'

timeout: 1200s
