steps:
  - name: gcr.io/chuspace-210609/ci
    waitFor: ['-']
    args: ['bundle', 'install', '--jobs', '3', '--retry', '3', '--without', 'development,production']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'BUNDLE_DISABLE_SHARED_GEMS=true'

  - name: gcr.io/chuspace-210609/ci
    waitFor: ['-']
    args: ['yarn', 'install']

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rails', 'db:schema:load']
    env:
      - 'RAILS_ENV=test'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rails', 'db:migrate']
    env:
      - 'RAILS_ENV=test'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rubocop']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  # Run tests
  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rspec']
    env:
      - 'MOBIUS_SERVICE_HOST=localhost'
      - 'MOBIUS_SERVICE_PORT=3001'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'


substitutions:
  _DATABASE_URL: 'postgres://proxyuser:gauravrocket@35.240.126.48:5432/chuspace_test'

options:
  substitution_option: 'ALLOW_LOOSE'

timeout: 1200s
