steps:
  #- name: gcr.io/cloud-builders/gsutil
  #  args: ['cp', 'gs://artifacts.chuspace-210609.appspot.com/bundler_cache', './vendor/cache']

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'install', '--jobs', '3', '--retry', '3', '--without', 'development,production']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'BUNDLE_DISABLE_SHARED_GEMS=true'

  #- name: gcr.io/cloud-builders/gsutil
  #  args: ['cp', './vendor/cache', 'gs://artifacts.chuspace-210609.appspot.com/bundler_cache']


  - name: gcr.io/chuspace-210609/ci
    args: ['yarn', 'install']

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rails', 'db:migrate']
    env:
      - 'RAILS_ENV=test'
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rspec']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/chuspace-210609/ci
    args: ['bundle', 'exec', 'rubocop']
    env:
      - 'BUNDLE_PATH=./vendor/cache'
      - 'DATABASE_URL=$_DATABASE_URL'
      - 'REDIS_URL=redis://redis:6379'
      - 'DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true'

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/chuspace-210609/chuspace-web', '.', '--cache-from', 'gcr.io/chuspace-210609/chuspace-web:latest']
    timeout: 600s

  - name: gcr.io/cloud-builders/kubectl
    args: ['set', 'image', 'deployment/chuspace-web', 'chuspace-web=chuspace-210609/chuspace-web']
    env:
      - 'cloudsdk_compute_zone=europe-west2'
      - 'cloudsdk_container_cluster=chuspace'

  - name: gcr.io/cloud-builders/kubectl
    args: ['set', 'image', 'deployment/chuspace-worker', 'chuspace-worker=chuspace-210609/chuspace-web']
    env:
      - 'cloudsdk_compute_zone=europe-west2'
      - 'cloudsdk_container_cluster=chuspace'


substitutions:
  _DATABASE_URL: 'postgres://proxyuser:gauravrocket@35.230.130.2:5432/chuspace_test'

images:
  - grc.io/chuspace-210609/chuspace-web

options:
  substitution_option: 'ALLOW_LOOSE'

timeout: 1200s
