#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id  = ENV.delete('GL_ID')
gl_repository = ENV.delete('GL_REPOSITORY')
repo_path = Dir.pwd

require_relative '../post-receive'

if Git::PostReceive.new(gl_repository, repo_path, key_id, refs).exec
  exit 0
else
  exit 1
end
