#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id = ENV.delete('GL_ID')
protocol = ENV.delete('GL_PROTOCOL')
repo_path = Dir.pwd
gl_repository = ENV['GL_REPOSITORY']

require_relative '../pre-receive'

if Git::PreReceive.new(gl_repository, repo_path, key_id, refs, protocol).exec
  exit 0
else
  exit 1
end
