steps:
  # Setup fake GOPATH
  - name: bash
    args: ['-c', 'mkdir -p src/github.com/gauravtiwari/chuspace; mv mobius src/github.com/gauravtiwari/chuspace/']

  - name: instrumentisto/dep
    dir: src/github.com/gauravtiwari/chuspace/mobius
    args: ['ensure']
    env:
      - 'GOPATH=/workspace'

  - name: gcr.io/cloud-builders/go
    dir: src/github.com/gauravtiwari/chuspace/mobius
    args: ['test', './...']
    env:
      - 'GOPATH=/workspace'

  - name: gcr.io/cloud-builders/docker
    dir: src/github.com/gauravtiwari/chuspace/mobius
    args: [
      'build',
      '-t', 'gcr.io/chuspace-210609/mobius:latest',
      '-t', 'gcr.io/chuspace-210609/mobius:${SHORT_SHA}',
      '--cache-from', 'gcr.io/chuspace-210609/mobius:latest',
      '.'
    ]
    timeout: 600s

  - name: gcr.io/cloud-builders/kubectl
    args:
      - 'set'
      - 'image'
      - 'deployment/mobius'
      - 'mobius=gcr.io/chuspace-210609/mobius:${SHORT_SHA}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=chuspace-staging'

images:
  - 'gcr.io/chuspace-210609/mobius'

options:
  substitution_option: 'ALLOW_LOOSE'

timeout: 1200s
