steps:
  # Setup fake GOPATH
  - name: bash
    args: ['-c', 'mkdir -p src/github.com/gauravtiwari/chuspace; mv mobius src/github.com/gauravtiwari/chuspace/']

  - name: instrumentisto/dep
    dir: src/github.com/gauravtiwari/chuspace/mobius
    args: ['ensure']
    env:
      - 'GOPATH=/workspace'

  - name: gcr.io/cloud-builders/go
    dir: src/github.com/gauravtiwari/chuspace/mobius
    args: ['test', './...']
    env:
      - 'GOPATH=/workspace'

  - name: gcr.io/cloud-builders/docker
    dir: src/github.com/gauravtiwari/chuspace/mobius
    entrypoint: bash
    args: [
      '-c',
      'docker build -t gcr.io/chuspace-210609/mobius:latest -t gcr.io/chuspace-210609/mobius:${SHORT_SHA} --build-arg github_token=$$GITHUB_TOKEN --cache-from gcr.io/chuspace-210609/mobius:latest .'
    ]
    timeout: 600s
    secretEnv: ['GITHUB_TOKEN']

images:
  - 'gcr.io/chuspace-210609/mobius'

options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
  - kmsKeyName: projects/chuspace-210609/locations/global/keyRings/ci/cryptoKeys/github-token
    secretEnv:
      GITHUB_TOKEN: CiQA1qDtXke8tW1njt26Db+2MwFRKzK7dThzGuykSsOkTD/VGusSUQC1oDemRTinUqYwF8vzgNgfBBPhECdmZ02Xf6kPLsGO/UR4hnWSh7+i+dIDN5BWkue1M42/0A9vvQqxC98FZgAVQAo+UWlgLhajtBKc1DQyMg==

timeout: 1200s
