version: 2
jobs:
  build:
    working_directory: ~/chuspace
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: postgres:11.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: chuspace_test
          POSTGRES_PASSWORD: ''
      - image: redis:5.0.4-alpine

    steps:
      - checkout

      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install gcc g++ cmake'

      - run:
          name: Installing vips
          command: sudo apt install libvips libvips-dev

      - run:
        name: Installing crystal
        command: \
          curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
          curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add -
          echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
          sudo apt-get update
          sudo apt install crystal

      - run:
        name: Installing postgres client
        command: |
          echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-client-11

      - restore_cache:
          keys:
            - v2-node-dependencies-{{ checksum "package.json" }}
            - v2-node-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - node_modules/.cache/**/*
          key: v2-node-dependencies-{{ checksum "package.json" }}

      - restore_cache:
          keys:
            - v2-rails-dependencies-{{ checksum "Gemfile.lock" }}
            - v2-rails-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run:
          name: Compiling assets...
          command: CI=yes bundle exec rails assets:precompile

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./tmp/cache/webpacker/*
            - ./public/packs-test/**/*
            - ./public/assets/**/*
          key: v2-rails-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Setting databases...
          command: bundle exec rails db:create && bundle exec rails db:structure:load

      - run:
          name: Setup configs...
          command: |
            cp config/git.yml.example config/git.yml
            cp openssh/sshd_config.example openssh/sshd_config
            ssh-keygen -t rsa -b 4096 -C "gaurav@gauravtiwari.co.uk" -f ./openssh/ssh_host_rsa_key -q -N ""

      - run:
          name: Run linters
          command: bin/rubocop && brakeman -q -w2 && bundle audit --update

      - run:
          name: Copying mobius
          command: sudo cp bin/mobius /etc/git/mobius

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
