#!/usr/bin/env ruby
# frozen_string_literal: true

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id = ENV.delete('GL_ID')
repo_path = Dir.pwd

require_relative '../custom_hook'
require_relative '../post_receive'

if Mobius::PostReceive.new(repo_path, key_id, refs).exec &&
    Mobius::CustomHook.new(repo_path, key_id).post_receive(refs)
  exit 0
else
  exit 1
end
