#!/usr/bin/env ruby
# frozen_string_literal: true

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = $stdin.read
key_id = ENV.delete('GL_ID')
protocol = ENV.delete('GL_PROTOCOL')
repo_path = Dir.pwd

require_relative '../lib/mobius_custom_hook'
require_relative '../lib/mobius_reference_counter'
require_relative '../lib/mobius_access'

# It's important that on pre-receive `increase_reference_counter` gets executed
# last so that it only runs if everything else succeeded. On post-receive on the
# other hand, we run MobiusPostReceive first because the push is already done
# and we don't want to skip it if the custom hook fails.
if MobiusAccess.new(repo_path, key_id, refs, protocol).exec &&
    MobiusCustomHook.new(repo_path, key_id).pre_receive(refs) &&
    MobiusReferenceCounter.new(repo_path).increase
  exit 0
else
  exit 1
end
