# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.User" do
    optional :id, :string, 1
    optional :nickname, :string, 2
    optional :repo, :message, 3, "api.Repo"
  end
  add_message "api.Repo" do
    optional :name, :string, 1
  end
  add_message "api.InitialRepo" do
    optional :user, :message, 1, "api.User"
    optional :head, :string, 2
    optional :uri, :string, 3
  end
end

module Api
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.User").msgclass
  Repo = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Repo").msgclass
  InitialRepo = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.InitialRepo").msgclass
end
