# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'api'

require 'grpc'
require 'api_pb'

module Api
  module Mobius
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.Mobius'

      rpc :InitBareRepo, User, InitialRepo
    end

    Stub = Service.rpc_stub_class
  end
end
