# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "rpc.User" do
    optional :id, :string, 1
    optional :nickname, :string, 2
    optional :repo, :message, 3, "rpc.Repo"
  end
  add_message "rpc.Repo" do
    optional :name, :string, 1
  end
  add_message "rpc.InitialRepo" do
    optional :user, :message, 1, "rpc.User"
    optional :head, :string, 2
    optional :uri, :string, 3
  end
end

module Rpc
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.User").msgclass
  Repo = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Repo").msgclass
  InitialRepo = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.InitialRepo").msgclass
end
