# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpc.proto for package 'rpc'

require 'grpc'
require 'rpc_pb'

module Rpc
  module Mobius
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Mobius'

      rpc :InitBareRepo, User, InitialRepo
    end

    Stub = Service.rpc_stub_class
  end
end
