apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-ci-agent
  labels:
    app: chuspace-ci-agent
    tier: deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chuspace-ci-agent
        tier: deploy
    spec:
      containers:
        - name: ci-agent
          image: drone/drone:0.8
          imagePullPolicy: Always
          command:
            - /drone
            - agent
          env:
            - name: DRONE_SERVER
              value: ws://$(CHUSPACE_CI_SERVICE_HOST):$(CHUSPACE_CI_SERVICE_PORT)
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
        volumes:
          - name: docker-socket
            hostPath:
              path: /var/run/docker.sock
