apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chuspace-ci
    spec:
      containers:
        - name: chuspace-ci
          image: drone/drone:0.8
          imagePullPolicy: Always
          env:
            - name: DRONE_GITHUB
              value: 'true'
            - name: DRONE_OPEN
              value: 'true'
            - name: DRONE_HOST
              value: http://35.197.205.22
            - name: DRONE_ORGS
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: orgs
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_client
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_secret
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
          volumeMounts:
            - name: drone-lib
              mountPath: /var/lib/drone
          ports:
            - name: ci-server
              containerPort: 8000
            - name: ci-agent
              containerPort: 9000
      volumes:
        - name: drone-lib
          hostPath:
            path: /var/lib/drone
      hostNetwork: true
      restartPolicy: Always
