apiVersion: v1
kind: Service
metadata:
  name: chuspace-ci
  labels:
    app: chuspace-ci
    tier: deploy
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: ci-server
  selector:
    app: chuspace-ci
    tier: ci
