apiVersion: v1
kind: Service
metadata:
  name: chuspace-ci
  labels:
    name: chuspace-ci
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: ci-server
  selector:
    name: chuspace-ci
