apiVersion: v1
kind: Service
metadata:
  name: ci-server
  labels:
    name: ci-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: ci-server
  selector:
    name: ci-server

---

apiVersion: v1
kind: Service
metadata:
  name: ci-agent
  labels:
    name: ci-agent
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: ci-agent
  selector:
    name: ci

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ci
    spec:
      containers:
        - name: ci-server
          image: drone/drone:0.8
          imagePullPolicy: Always
          env:
            - name: DRONE_GITHUB
              value: 'true'
            - name: DRONE_OPEN
              value: 'true'
            - name: DRONE_HOST
              value: http://35.197.205.22
            - name: DRONE_ORGS
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: orgs
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_client
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_secret
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
            - name: DRONE_DATABASE_DRIVER
              value: postgres
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: database_url

          volumeMounts:
            - name: drone-lib
              mountPath: /var/lib/drone
          ports:
            - name: ci-server
              containerPort: 8000
            - name: ci-agent
              containerPort: 9000
      volumes:
        - name: drone-lib
          hostPath:
            path: /var/lib/drone
      hostNetwork: true
      restartPolicy: Always

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ci-agent
    spec:
      containers:
        - name: ci-agent
          image: drone/agent:0.8
          imagePullPolicy: Always
          env:
            - name: DRONE_SERVER
              value: $(CI_SERVER_SERVICE_HOST):$(CI_AGENT_SERVICE_PORT)
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
