apiVersion: v1
kind: Service
metadata:
  name: ci-server
  labels:
    name: ci-server
spec:
  type: LoadBalancer
  ports:
    - name: ci-http
      port: 80
      targetPort: ci-http
      protocol: TCP
    - name: ci-grpc
      port: 9000
      targetPort: ci-grpc
      protocol: TCP
  selector:
    name: ci

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ci
    spec:
      containers:
        - name: ci-server
          image: drone/drone:0.8
          imagePullPolicy: Always
          env:
            - name: DRONE_GITHUB
              value: 'true'
            - name: DRONE_OPEN
              value: 'true'
            - name: DRONE_HOST
              value: http://35.197.205.22
            - name: DRONE_ORGS
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: orgs
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_client
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: github_secret
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: db_password
            - name: DRONE_DATABASE_DRIVER
              value: postgres
            - name: DRONE_DATABASE_DATASOURCE
              value: postgres://$(DB_USER):$(DB_PASSWORD)@$(POSTGRES_CI_SERVICE_HOST):$(POSTGRES_CI_SERVICE_PORT)/drone?sslmode=disable
          volumeMounts:
            - name: drone-lib
              mountPath: /var/lib/drone
          ports:
            - name: ci-http
              containerPort: 8000
              protocol: TCP
            - name: ci-grpc
              containerPort: 9000
              protocol: TCP
      volumes:
        - name: drone-lib
          hostPath:
            path: /var/lib/drone
      hostNetwork: true
      restartPolicy: Always

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ci-agent
    spec:
      containers:
        - name: ci-agent
          image: drone/agent:0.8
          imagePullPolicy: Always
          env:
            - name: DRONE_SERVER
              value: 35.197.205.22:9000
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: secret
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
