apiVersion: v1
kind: Service
metadata:
  name: chuspace-staging-db
  labels:
    name: postgres
    db: chuspace-staging
spec:
  ports:
    - port: 5432
      targetPort: staging-db
  selector:
    name: cloudsql-proxy

---

apiVersion: v1
kind: Service
metadata:
  name: test-db
  labels:
    name: postgres
    db: chuspace-test
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: test-db
  selector:
    name: cloudsql-proxy

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cloudsql-proxy
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
            - '/cloud_sql_proxy'
            - '-dir=/cloudsql'
            - '-instances=chuspace-210609:europe-west2:chuspace-staging=tcp:0.0.0.0:5433,chuspace-210609:europe-west2:chuspace-test=tcp:0.0.0.0:5434'
            - '-credential_file=/secrets/cloudsql/credentials.json'
          ports:
            - name: staging-db
              containerPort: 5433
            - name: test-db
              containerPort: 5434
          volumeMounts:
            - name: cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-credentials
          secret:
            secretName: cloudsql-credentials
