apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: load-balancer
  labels:
    name: load-balancer
  annotations:
    kubernetes.io/ingres.global-static-ip-name: load-balancer
spec:
  tls:
    - hosts:
        - staging.chuspace.com
        - chuspace.com
      secretName: ssl-certs

  rules:
    - host: staging.chuspace.com
      http:
        paths:
          - backend:
              serviceName: web
              servicePort: 80
          - backend:
              serviceName: mobius
              servicePort: 22
