apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chuspace-lb
  labels:
    name: chuspace-lb
  annotations:
    kubernetes.io/ingres.global-static-ip-name: chuspace-lb
spec:
  tls:
    - hosts:
        - ci.chuspace.com
        - staging.chuspace.com
        - chuspace.com
      secretName: ssl-certs

  rules:
    - host: ci.chuspace.com
      http:
        paths:
          - backend:
              serviceName: ci-server
              servicePort: 80
          - backend:
              serviceName: ci-agent
              servicePort: 9000

    - host: staging.chuspace.com
      http:
        paths:
          - backend:
              serviceName: chuspace-web
              servicePort: 80
