apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobius
spec:
  volumeMode: Filesystem
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mobius-ssh
  labels:
    name: mobius-ssh
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: mobius-ssh
      protocol: TCP
  selector:
    name: mobius

---

apiVersion: v1
kind: Service
metadata:
  name: mobius
  labels:
    name: mobius
spec:
  ports:
    - port: 80
      targetPort: mobius-http
  selector:
    name: mobius

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobius
spec:
  replicas: 1
  template:
    metadata:
      name: mobius
      labels:
        name: mobius
    spec:
      containers:
        - name: mobius
          image: gcr.io/chuspace-210609/mobius
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PORT
              value: "1006"
            - name: SSH_PORT
              value: "1007"
            - name: GIT_STORAGE_PATH
              value: /mnt/git
            - name: SSL_CERT_DIR
              value: /secrets/ssl
          volumeMounts:
            - name: git-storage
              mountPath: /mnt/git
            - name: ssl-certs
              mountPath: /secrets/ssl
          ports:
            - name: mobius-http
              containerPort: 1006
            - name: mobius-ssh
              containerPort: 1007
          readinessProbe:
            httpGet:
              path: /
              port: 1006
          livenessProbe:
            httpGet:
              path: /
              port: 1006
      volumes:
        - name: git-storage
          persistentVolumeClaim:
            claimName: mobius
        - name: ssl-certs
          secret:
            secretName: ssl-certs
