apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: chuspace
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 6739
      targetPort: redis-server
  selector:
    app: chuspace
    tier: backend
      
