apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chuspace-web
    spec:
      initContainers:
        - name: db-migrate
          image: grc.io/chuspace-210609/chuspace-web:latest
          command:
            - bin/rails
            - db:migrate
          env:
            - name: RAILS_ENV
              value: production

      containers:
        - name: chuspace-web
          image: grc.io/chuspace-210609/chuspace-web:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FORMATION
              value: web=1
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: RAILS_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: REDIS_URL
              value: redis.default.svc.cluster.local:6379
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: database_url
          ports:
            - name: http-server
              containerPort: 3000

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-worker
  labels:
    name: chuspace-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chuspace-worker
    spec:
      containers:
        - name: chuspace-worker
          image: grc.io/chuspace-210609/chuspace-web:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FORMATION
              value: worker=1
            - name: REDIS_URL
              value: redis.default.svc.cluster.local
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: database_url

---

apiVersion: v1
kind: Service
metadata:
  name: chuspace-web
  labels:
    name: chuspace-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    name: chuspace-web
