apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web-http
      protocol: TCP
  selector:
    name: web

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    name: web
    keel.sh/policy: all
    keel.sh/approvals: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      terminationGracePeriodSeconds: 15
      initContainers:
        - name: db-migrate
          image: gcr.io/chuspace-210609/web
          command: ['bin/rails']
          args: ['db:migrate']
          imagePullPolicy: Always
          env:
            - name: RAILS_ENV
              value: staging
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: REDIS_URL
              value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: secret-key-base
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: STORAGE_KEYFILE
              value: /secrets/cloud-storage/credentials.json
            - name: STACKDRIVER_KEYFILE
              value: /secrets/stackdriver/credentials.json
          volumeMounts:
            - name: cloudstorage-credentials
              mountPath: /secrets/cloud-storage
            - name: stackdriver-credentials
              mountPath: /secrets/stackdriver
      containers:
        - name: web
          image: gcr.io/chuspace-210609/web
          imagePullPolicy: Always
          env:
            - name: FORMATION
              value: web=1
            - name: PORT
              value: '3000'
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: RAILS_ENV
              value: staging
            - name: NODE_ENV
              value: production
            - name: REDIS_URL
              value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: secret-key-base
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: github
                  key: client-secret
            - name: SENDGRID_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email
                  key: username
            - name: SENDGRID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email
                  key: password
            - name: STORAGE_KEYFILE
              value: /secrets/cloud-storage/credentials.json
            - name: STACKDRIVER_KEYFILE
              value: /secrets/stackdriver/credentials.json
          ports:
            - name: web-http
              containerPort: 3000
          volumeMounts:
            - name: cloudstorage-credentials
              mountPath: /secrets/cloud-storage
            - name: stackdriver-credentials
              mountPath: /secrets/stackdriver
      volumes:
        - name: cloudstorage-credentials
          secret:
            secretName: cloudstorage-credentials
        - name: stackdriver-credentials
          secret:
            secretName: stackdriver-credentials

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  labels:
    name: worker
    keel.sh/policy: all
    keel.sh/approvals: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: worker
          image: gcr.io/chuspace-210609/web
          imagePullPolicy: Always
          env:
            - name: FORMATION
              value: worker=1
            - name: RAILS_ENV
              value: staging
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: REDIS_URL
              value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: secret-key-base
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: SENDGRID_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email
                  key: username
            - name: SENDGRID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email
                  key: password
            - name: STORAGE_KEYFILE
              value: /secrets/cloud-storage/credentials.json
            - name: STACKDRIVER_KEYFILE
              value: /secrets/stackdriver/credentials.json
          volumeMounts:
            - name: cloudstorage-credentials
              mountPath: /secrets/cloud-storage
            - name: stackdriver-credentials
              mountPath: /secrets/stackdriver
      volumes:
        - name: cloudstorage-credentials
          secret:
            secretName: cloudstorage-credentials
        - name: stackdriver-credentials
          secret:
            secretName: stackdriver-credentials
