apiVersion: v1
kind: Service
metadata:
  name: chuspace-web
  labels:
    app: chuspace
    tier: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: chuspace
    tier: web
      
