apiVersion: v1
kind: Service
metadata:
  name: chuspace-web
  labels:
    name: chuspace-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    name: chuspace-web
      
