apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-web
  labels:
    app: chuspace
    tier: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chuspace
        tier: web
    spec:
      containers:
        - name: chuspace-web
          image: grc.io/maximal-relic-210021/chuspace-web:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FORMATION
              value: web=1
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: redis_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: database_url
          ports:
            - name: http-server
              containerPort: 3000
          
