apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuspace-worker
  labels:
    name: chuspace-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chuspace-worker
    spec:
      containers:
        - name: chuspace-worker
          image: grc.io/chuspace-210609/chuspace-web:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: FORMATION
              value: worker=1
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: redis_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chuspace
                  key: database_url
