// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Repo                 *Repo    `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_af149260d28843d5, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetRepo() *Repo {
	if m != nil {
		return m.Repo
	}
	return nil
}

type Repo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repo) Reset()         { *m = Repo{} }
func (m *Repo) String() string { return proto.CompactTextString(m) }
func (*Repo) ProtoMessage()    {}
func (*Repo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_af149260d28843d5, []int{1}
}
func (m *Repo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repo.Unmarshal(m, b)
}
func (m *Repo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repo.Marshal(b, m, deterministic)
}
func (dst *Repo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repo.Merge(dst, src)
}
func (m *Repo) XXX_Size() int {
	return xxx_messageInfo_Repo.Size(m)
}
func (m *Repo) XXX_DiscardUnknown() {
	xxx_messageInfo_Repo.DiscardUnknown(m)
}

var xxx_messageInfo_Repo proto.InternalMessageInfo

func (m *Repo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type InitialRepo struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Uri                  string   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialRepo) Reset()         { *m = InitialRepo{} }
func (m *InitialRepo) String() string { return proto.CompactTextString(m) }
func (*InitialRepo) ProtoMessage()    {}
func (*InitialRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_af149260d28843d5, []int{2}
}
func (m *InitialRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialRepo.Unmarshal(m, b)
}
func (m *InitialRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialRepo.Marshal(b, m, deterministic)
}
func (dst *InitialRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialRepo.Merge(dst, src)
}
func (m *InitialRepo) XXX_Size() int {
	return xxx_messageInfo_InitialRepo.Size(m)
}
func (m *InitialRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialRepo.DiscardUnknown(m)
}

var xxx_messageInfo_InitialRepo proto.InternalMessageInfo

func (m *InitialRepo) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *InitialRepo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *InitialRepo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*Repo)(nil), "api.Repo")
	proto.RegisterType((*InitialRepo)(nil), "api.InitialRepo")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_af149260d28843d5) }

var fileDescriptor_api_af149260d28843d5 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4d, 0x6b, 0x84, 0x30,
	0x10, 0x86, 0xab, 0x06, 0x69, 0xc6, 0x52, 0x64, 0x4e, 0x22, 0x08, 0x92, 0x93, 0x97, 0x7a, 0xb0,
	0x87, 0xde, 0x7b, 0xeb, 0xa1, 0x87, 0x06, 0xfa, 0x03, 0xe2, 0x1a, 0xd8, 0x61, 0x77, 0x4d, 0x88,
	0xfa, 0xff, 0x97, 0xcc, 0x7e, 0xde, 0x9e, 0x79, 0x99, 0x3c, 0xf3, 0x12, 0x90, 0xc6, 0x53, 0xef,
	0x83, 0x5b, 0x1d, 0x66, 0xc6, 0x93, 0xfa, 0x03, 0xf1, 0xbf, 0xd8, 0x80, 0xef, 0x90, 0xd2, 0x54,
	0x25, 0x6d, 0xd2, 0x49, 0x9d, 0xd2, 0x84, 0x35, 0xbc, 0xce, 0xb4, 0x3b, 0xcc, 0xe6, 0x64, 0xab,
	0x94, 0xd3, 0xfb, 0x8c, 0x0d, 0x88, 0x60, 0xbd, 0xab, 0xb2, 0x36, 0xe9, 0x8a, 0x41, 0xf6, 0x51,
	0xa9, 0xad, 0x77, 0x9a, 0x63, 0x55, 0x83, 0x88, 0x13, 0x22, 0x08, 0x7e, 0x7e, 0x91, 0x32, 0x2b,
	0x0d, 0xc5, 0xcf, 0x4c, 0x2b, 0x99, 0x23, 0xaf, 0x34, 0x20, 0xb6, 0xc5, 0x06, 0x5e, 0xb9, 0x99,
	0x62, 0x1d, 0xcd, 0x71, 0x34, 0xec, 0xad, 0x99, 0xae, 0x05, 0x98, 0xb1, 0x84, 0x6c, 0x0b, 0xc4,
	0xb7, 0xa5, 0x8e, 0x38, 0x7c, 0x41, 0xfe, 0xeb, 0x46, 0xda, 0x16, 0xfc, 0x80, 0xb7, 0x68, 0xff,
	0x36, 0xc1, 0xb2, 0xfe, 0x21, 0xac, 0x4b, 0xc6, 0xa7, 0xdb, 0xea, 0x65, 0xcc, 0xf9, 0x1f, 0x3e,
	0xcf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0x94, 0x1e, 0x38, 0x14, 0x01, 0x00, 0x00,
}
