// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mobius.proto

package mobius

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobius_74fcbce84da0271c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type InitialRepo struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Head                 string   `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Uri                  string   `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialRepo) Reset()         { *m = InitialRepo{} }
func (m *InitialRepo) String() string { return proto.CompactTextString(m) }
func (*InitialRepo) ProtoMessage()    {}
func (*InitialRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mobius_74fcbce84da0271c, []int{1}
}
func (m *InitialRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialRepo.Unmarshal(m, b)
}
func (m *InitialRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialRepo.Marshal(b, m, deterministic)
}
func (dst *InitialRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialRepo.Merge(dst, src)
}
func (m *InitialRepo) XXX_Size() int {
	return xxx_messageInfo_InitialRepo.Size(m)
}
func (m *InitialRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialRepo.DiscardUnknown(m)
}

var xxx_messageInfo_InitialRepo proto.InternalMessageInfo

func (m *InitialRepo) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *InitialRepo) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *InitialRepo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "mobius.User")
	proto.RegisterType((*InitialRepo)(nil), "mobius.InitialRepo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MobiusClient is the client API for Mobius service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MobiusClient interface {
	InitBareRepo(ctx context.Context, in *User, opts ...grpc.CallOption) (*InitialRepo, error)
}

type mobiusClient struct {
	cc *grpc.ClientConn
}

func NewMobiusClient(cc *grpc.ClientConn) MobiusClient {
	return &mobiusClient{cc}
}

func (c *mobiusClient) InitBareRepo(ctx context.Context, in *User, opts ...grpc.CallOption) (*InitialRepo, error) {
	out := new(InitialRepo)
	err := c.cc.Invoke(ctx, "/mobius.Mobius/InitBareRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MobiusServer is the server API for Mobius service.
type MobiusServer interface {
	InitBareRepo(context.Context, *User) (*InitialRepo, error)
}

func RegisterMobiusServer(s *grpc.Server, srv MobiusServer) {
	s.RegisterService(&_Mobius_serviceDesc, srv)
}

func _Mobius_InitBareRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MobiusServer).InitBareRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mobius.Mobius/InitBareRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MobiusServer).InitBareRepo(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mobius_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mobius.Mobius",
	HandlerType: (*MobiusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitBareRepo",
			Handler:    _Mobius_InitBareRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mobius.proto",
}

func init() { proto.RegisterFile("mobius.proto", fileDescriptor_mobius_74fcbce84da0271c) }

var fileDescriptor_mobius_74fcbce84da0271c = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x4f, 0xca,
	0x2c, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x8c, 0xb8, 0x58,
	0x42, 0x8b, 0x53, 0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x98, 0x32, 0x53, 0x84, 0xa4, 0xb8, 0x38, 0xf2, 0x32, 0x93, 0xb3, 0xf3, 0x12, 0x73, 0x53,
	0x25, 0x98, 0xc0, 0xa2, 0x70, 0xbe, 0x52, 0x28, 0x17, 0xb7, 0x67, 0x5e, 0x66, 0x49, 0x66, 0x62,
	0x4e, 0x50, 0x6a, 0x41, 0xbe, 0x90, 0x02, 0x17, 0x4b, 0x69, 0x71, 0x6a, 0x11, 0x58, 0x33, 0xb7,
	0x11, 0x8f, 0x1e, 0xd4, 0x1e, 0x90, 0xb1, 0x41, 0x60, 0x19, 0x21, 0x21, 0x2e, 0x96, 0x8c, 0xd4,
	0xc4, 0x14, 0xa8, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51, 0xa6, 0x04, 0x33, 0x58,
	0x08, 0xc4, 0x34, 0xb2, 0xe5, 0x62, 0xf3, 0x05, 0x6b, 0x15, 0x32, 0xe6, 0xe2, 0x01, 0x59, 0xe0,
	0x94, 0x58, 0x94, 0x0a, 0xb6, 0x01, 0xc5, 0x4c, 0x29, 0x61, 0x18, 0x0f, 0xc9, 0x11, 0x4a, 0x0c,
	0x49, 0x6c, 0x60, 0x8f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xde, 0xa0, 0x32, 0x52, 0xe8,
	0x00, 0x00, 0x00,
}
