default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: chuspace_<$= ENV['RAILS_ENV'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['POSTGRES_WEB_SERVICE_HOST'] %>
  port: <%= ENV['POSTGRES_WEB_SERVICE_PORT'] %>

production:
  <<: *default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['POSTGRES_WEB_SERVICE_HOST'] %>
  port: <%= ENV['POSTGRES_WEB_SERVICE_PORT'] %>
