default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: chuspace_<%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: chuspace
  host: <%= ENV['PG_HOST'] %>
  port: 5432
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
