server-name: "Chuspace"
max-connections: 100000
http2-max-concurrent-requests-per-connection: 256
num-threads: 16

hosts:
  "www.chuspace.com:80":
    listen:
      port: 80
    paths:
      "/":
        status: ON
        redirect: https://chuspace.com/
  "chuspace.com:80":
    listen:
      port: 80
    paths:
      "/":
        status: ON
        redirect: https://chuspace.com/
  "www.chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        status: ON
        redirect: https://chuspace.com/
  "chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            if /\.(css|js|png|jpeg|jpg|ico|html)\z/.match(env["PATH_INFO"])
              headers["cache-control"] = "public, max-age=31536000, s-maxage=31536000, immutable"
            end
            [399, headers, []]
          end
        compress: ON
        file.dir: /home/git/chuspace.com/current/public
        proxy.reverse.url: "http://127.0.0.1:8083/"

  "images.chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        compress: ON
        proxy.reverse.url: "http://127.0.0.1:8082/"
        header.add: "Cache-Control: public, max-age=31536000, s-maxage=31536000, immutable"

  "live.chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        compress: ON
        proxy.reverse.url: "http://127.0.0.1:8081/"
        proxy.websocket: ON

access-log: /usr/local/var/h2o/access-log
error-log: /usr/local/var/h2o/error-log
