server-name: "Chuspace"
max-connections: 100000
http2-max-concurrent-requests-per-connection: 256
num-threads: 16

hosts:
  "www.chuspace.com:80":
    listen:
      port: 80
    paths:
      "/":
        status: OFF
        redirect:
          url: https://chuspace.com/
          status: 301
  "chuspace.com:80":
    listen:
      port: 80
    paths:
      "/":
        status: OFF
        redirect:
          url: https://chuspace.com/
          status: 301
  "18.202.162.75:80":
    listen:
      port: 80
    paths:
      "/":
        status: OFF
        redirect:
          url: https://chuspace.com/
          status: 301
  "18.202.162.75:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        status: OFF
        redirect:
          url: https://chuspace.com/
          status: 301
  "www.chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        status: OFF
        redirect:
          url: https://chuspace.com/
          status: 301
  "chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            if /\.(css|js|png|jpeg|jpg|ico|html|woff|svg|woff2|ttf|eot)\z/.match(env["PATH_INFO"])
              headers["cache-control"] = "public, max-age=31536000, s-maxage=31536000, immutable"
            end
            [399, headers, []]
          end
        mruby.handler: |
          Proc.new do |env|
            headers = {}
            if /\.(woff|svg|woff2|ttf|eot)\z/.match(env["PATH_INFO"])
              headers["Access-Control-Allow-Origin"] = "*"
            end
            [399, headers, []]
          end
        compress: ON
        file.dir: /home/git/chuspace.com/current/public
        proxy.reverse.url: "http://127.0.0.1:8083/"
        proxy.preserve-host: ON

  "live.chuspace.com:443":
    listen:
      port: 443
      ssl:
        certificate-file: /etc/letsencrypt/live/chuspace.com-0001/fullchain.pem
        key-file: /etc/letsencrypt/live/chuspace.com-0001/privkey.pem
        dh-file: /etc/letsencrypt/ssl-dhparams.pem
    paths:
      "/":
        compress: ON
        proxy.reverse.url: "http://127.0.0.1:8081/"
        proxy.websocket: ON
        proxy.preserve-host: ON

access-log: /usr/local/var/h2o/access-log
error-log: /usr/local/var/h2o/error-log
