# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_11; end
module ::Anonymous_Delegator_12; end
module ::Anonymous_Delegator_13; end
module ::Anonymous_Delegator_2; end
module ::Anonymous_Delegator_422; end
module ::Anonymous_Delegator_8; end
module ::Anonymous_Delegator_9; end
module ::User; end
module ::User; end
module ::User; end
module ::User; end
module ::User; end
module ::User; end
module ::User; end
module ::User; end
module ActionMailer::Base::Mail::Message; end
module ActiveRecord::CollectionCacheKey; end
module Blob::User; end
module Blob::User; end
module PostHtmlRenderer::S3Service; end
module PostReceiveConsumer::User; end
module UserMailerPreview::User; end
module UserMailerPreview::User; end
