# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: ignore
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_11; end
module ::Anonymous_Delegator_12; end
module ::Anonymous_Delegator_13; end
module ::Anonymous_Delegator_2; end
module ::Anonymous_Delegator_410; end
module ::Anonymous_Delegator_8; end
module ::Anonymous_Delegator_9; end
module ::DefaultRackup; end
module ::ElasticsearchClient; end
module ::Octokit::Client; end
module ::Octokit::UnprocessableEntity; end
module ::Readthis; end
module ::Readthis; end
module ::Readthis; end
module ::Readthis::Cache; end
module ::Spring; end
module ActionMailer::Base::Mail::Message; end
module Git::Diff::Util; end
module Post::Slug; end
module Sidekiq::Middleware::Server::RetryJobs; end
module Sidekiq::Middleware::Server::RetryJobs; end
