# This is an autogenerated file for dynamic methods in Delayed::Backend::ActiveRecord::Job
# Please rerun rake rails_rbi:models[Delayed::Backend::ActiveRecord::Job] to regenerate.

# typed: strong
module Delayed::Backend::ActiveRecord::Job::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Delayed::Backend::ActiveRecord::Job::GeneratedAttributeMethods
  extend T::Sig

  sig { returns(Integer) }
  def attempts; end

  sig { params(value: Integer).void }
  def attempts=(value); end

  sig { returns(T::Boolean) }
  def attempts?; end

  sig { returns(T.nilable(DateTime)) }
  def created_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(T.nilable(DateTime)) }
  def failed_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def failed_at=(value); end

  sig { returns(T::Boolean) }
  def failed_at?; end

  sig { returns(String) }
  def handler; end

  sig { params(value: String).void }
  def handler=(value); end

  sig { returns(T::Boolean) }
  def handler?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(T.nilable(String)) }
  def last_error; end

  sig { params(value: T.nilable(String)).void }
  def last_error=(value); end

  sig { returns(T::Boolean) }
  def last_error?; end

  sig { returns(T.nilable(DateTime)) }
  def locked_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def locked_at=(value); end

  sig { returns(T::Boolean) }
  def locked_at?; end

  sig { returns(T.nilable(String)) }
  def locked_by; end

  sig { params(value: T.nilable(String)).void }
  def locked_by=(value); end

  sig { returns(T::Boolean) }
  def locked_by?; end

  sig { returns(Integer) }
  def priority; end

  sig { params(value: Integer).void }
  def priority=(value); end

  sig { returns(T::Boolean) }
  def priority?; end

  sig { returns(T.nilable(String)) }
  def queue; end

  sig { params(value: T.nilable(String)).void }
  def queue=(value); end

  sig { returns(T::Boolean) }
  def queue?; end

  sig { returns(T.nilable(DateTime)) }
  def run_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def run_at=(value); end

  sig { returns(T::Boolean) }
  def run_at?; end

  sig { returns(T.nilable(DateTime)) }
  def updated_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end
end

module Delayed::Backend::ActiveRecord::Job::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Delayed::Backend::ActiveRecord::Job) }
  def find_by_id!(id); end
end

class Delayed::Backend::ActiveRecord::Job < ActiveRecord::Base
  include Delayed::Backend::ActiveRecord::Job::GeneratedAttributeMethods
  extend Delayed::Backend::ActiveRecord::Job::CustomFinderMethods
  extend T::Sig
  extend T::Generic

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.by_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.for_queues(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.max_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.min_priority(*args); end

  sig { returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def self.only(*args, &block); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def self.find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.find_by(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def self.find_by!(*args); end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.first; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.first!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.second; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.second!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.third; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.third!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.third_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.third_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.second_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.second_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def self.last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def self.last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def self.exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.one?(*args); end
end

class Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation < ActiveRecord::Relation
  include Delayed::Backend::ActiveRecord::Job::ActiveRelation_WhereNot
  include Delayed::Backend::ActiveRecord::Job::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Delayed::Backend::ActiveRecord::Job)

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def by_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def for_queues(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def max_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def min_priority(*args); end

  sig { returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_Relation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find_by!(*args); end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def first; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def first!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Delayed::Backend::ActiveRecord::Job).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def flatten(level); end

  sig { returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end
end

class Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Delayed::Backend::ActiveRecord::Job::ActiveRelation_WhereNot
  include Delayed::Backend::ActiveRecord::Job::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Delayed::Backend::ActiveRecord::Job)

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def by_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def for_queues(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def max_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def min_priority(*args); end

  sig { returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find_by!(*args); end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def first; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def first!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Delayed::Backend::ActiveRecord::Job).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def flatten(level); end

  sig { returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end
end

class Delayed::Backend::ActiveRecord::Job::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Delayed::Backend::ActiveRecord::Job::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Delayed::Backend::ActiveRecord::Job)

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def by_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def for_queues(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def max_priority(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def min_priority(*args); end

  sig { returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Delayed::Backend::ActiveRecord::Job::ActiveRecord_AssociationRelation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Delayed::Backend::ActiveRecord::Job) }
  def find_by!(*args); end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def first; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def first!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def third_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def third_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def second_to_last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def second_to_last!; end

  sig { returns(T.nilable(Delayed::Backend::ActiveRecord::Job)) }
  def last; end

  sig { returns(Delayed::Backend::ActiveRecord::Job) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Delayed::Backend::ActiveRecord::Job).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def flatten(level); end

  sig { returns(T::Array[Delayed::Backend::ActiveRecord::Job]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end

  sig { params(records: T.any(Delayed::Backend::ActiveRecord::Job, T::Array[Delayed::Backend::ActiveRecord::Job])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Delayed::Backend::ActiveRecord::Job, T::Array[Delayed::Backend::ActiveRecord::Job])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Delayed::Backend::ActiveRecord::Job, T::Array[Delayed::Backend::ActiveRecord::Job])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Delayed::Backend::ActiveRecord::Job, T::Array[Delayed::Backend::ActiveRecord::Job])).returns(T.self_type) }
  def concat(*records); end
end
