# This is an autogenerated file for dynamic methods in Edition
# Please rerun rake rails_rbi:models to regenerate.
# typed: ignore

class Edition::ActiveRecord_Relation < ActiveRecord::Relation
  include Edition::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Edition)
end

class Edition::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Edition::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Edition)
end

class Edition < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Edition::ModelRelationShared
  include Edition::InstanceMethods
  Elem = type_template(fixed: Edition)
end

module Edition::InstanceMethods
  extend T::Sig

  sig { returns(String) }
  def branch_name(); end

  sig { params(value: String).void }
  def branch_name=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def branch_name?(*args); end

  sig { void }
  def closed!(); end

  sig { returns(T::Boolean) }
  def closed?(); end

  sig { returns(String) }
  def commit_sha(); end

  sig { params(value: String).void }
  def commit_sha=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def commit_sha?(*args); end

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def created_at?(*args); end

  sig { void }
  def draft!(); end

  sig { returns(T::Boolean) }
  def draft?(); end

  sig { returns(Integer) }
  def editor_id(); end

  sig { params(value: Integer).void }
  def editor_id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def editor_id?(*args); end

  sig { returns(Integer) }
  def id(); end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def id?(*args); end

  sig { void }
  def merged!(); end

  sig { returns(T::Boolean) }
  def merged?(); end

  sig { void }
  def open!(); end

  sig { returns(T::Boolean) }
  def open?(); end

  sig { returns(Integer) }
  def post_id(); end

  sig { params(value: Integer).void }
  def post_id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def post_id?(*args); end

  sig { returns(String) }
  def status(); end

  sig { params(value: T.any(Integer, String, Symbol)).void }
  def status=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def status?(*args); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def updated_at?(*args); end

end

class Edition
  extend T::Sig

  sig { returns(::User) }
  def editor(); end

  sig { params(value: ::User).void }
  def editor=(value); end

  sig { returns(::Post) }
  def post(); end

  sig { params(value: ::Post).void }
  def post=(value); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def self.closed(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def self.draft(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def self.merged(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def self.open(*args); end

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def self.statuses(); end

end

module Edition::ModelRelationShared
  extend T::Sig

  sig { returns(Edition::ActiveRecord_Relation) }
  def all(); end

  sig { params(block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def closed(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def merged(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def not_closed(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def not_merged(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def not_open(*args); end

  sig { params(args: T.untyped).returns(Edition::ActiveRecord_Relation) }
  def open(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Edition::ActiveRecord_Relation) }
  def only(*args, &block); end

end
