# This is an autogenerated file for dynamic methods in Post
# Please rerun rake rails_rbi:models to regenerate.
# typed: strong

class Post::ActiveRecord_Relation < ActiveRecord::Relation
  include Post::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Post)
end

class Post::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Post::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Post)
end

class Post < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Post::ModelRelationShared
  include Post::InstanceMethods
  Elem = type_template(fixed: Post)
end

module Post::InstanceMethods
  extend T::Sig

  sig { returns(T.nilable(String)) }
  def ancestry(); end

  sig { params(value: T.nilable(String)).void }
  def ancestry=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def ancestry?(*args); end

  sig { void }
  def archived!(); end

  sig { returns(T::Boolean) }
  def archived?(); end

  sig { returns(Integer) }
  def author_id(); end

  sig { params(value: Integer).void }
  def author_id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def author_id?(*args); end

  sig { returns(T.nilable(String)) }
  def blob_id(); end

  sig { params(value: T.nilable(String)).void }
  def blob_id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def blob_id?(*args); end

  sig { returns(String) }
  def blob_path(); end

  sig { params(value: String).void }
  def blob_path=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def blob_path?(*args); end

  sig { returns(T.nilable(String)) }
  def body_html(); end

  sig { params(value: T.nilable(String)).void }
  def body_html=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def body_html?(*args); end

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def created_at?(*args); end

  sig { void }
  def draft!(); end

  sig { returns(T::Boolean) }
  def draft?(); end

  sig { returns(Integer) }
  def id(); end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def id?(*args); end

  sig { void }
  def published!(); end

  sig { returns(T::Boolean) }
  def published?(); end

  sig { returns(T.nilable(DateTime)) }
  def published_at(); end

  sig { params(value: T.nilable(DateTime)).void }
  def published_at=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def published_at?(*args); end

  sig { returns(Integer) }
  def repository_id(); end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def repository_id?(*args); end

  sig { returns(String) }
  def slug(); end

  sig { params(value: String).void }
  def slug=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def slug?(*args); end

  sig { returns(String) }
  def status(); end

  sig { params(value: T.any(Integer, String, Symbol)).void }
  def status=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def status?(*args); end

  sig { returns(T.nilable(String)) }
  def summary(); end

  sig { params(value: T.nilable(String)).void }
  def summary=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def summary?(*args); end

  sig { returns(T.nilable(String)) }
  def title(); end

  sig { params(value: T.nilable(String)).void }
  def title=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def title?(*args); end

  sig { returns(T.nilable(T::Array[T.untyped])) }
  def topics(); end

  sig { params(value: T.nilable(T::Array[T.untyped])).void }
  def topics=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def topics?(*args); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def updated_at?(*args); end

end

class Post
  extend T::Sig

  sig { returns(::User) }
  def author(); end

  sig { params(value: ::User).void }
  def author=(value); end

  sig { returns(::Edition::ActiveRecord_Associations_CollectionProxy) }
  def editions(); end

  sig { params(value: T.any(T::Array[::Edition], ::Edition::ActiveRecord_Associations_CollectionProxy)).void }
  def editions=(value); end

  sig { returns(::Repository) }
  def repository(); end

  sig { params(value: ::Repository).void }
  def repository=(value); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.archived(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.published(*args); end

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def self.statuses(); end

end

module Post::ModelRelationShared
  extend T::Sig

  sig { returns(Post::ActiveRecord_Relation) }
  def all(); end

  sig { params(block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def archived(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def children_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def not_archived(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def not_published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def path_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def roots(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def to_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def with_log_data(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def only(*args, &block); end

end
