# This is an autogenerated file for dynamic methods in Post
# Please rerun rake rails_rbi:models[Post] to regenerate.

# typed: strong
module Post::EnumInstanceMethods
  extend T::Sig

  sig { returns(T::Boolean) }
  def draft?; end

  sig { void }
  def draft!; end

  sig { returns(T::Boolean) }
  def published?; end

  sig { void }
  def published!; end
end

module Post::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Post::GeneratedAttributeMethods
  extend T::Sig

  sig { returns(T.nilable(String)) }
  def ancestry; end

  sig { params(value: T.nilable(String)).void }
  def ancestry=(value); end

  sig { returns(T::Boolean) }
  def ancestry?; end

  sig { returns(Integer) }
  def author_id; end

  sig { params(value: Integer).void }
  def author_id=(value); end

  sig { returns(T::Boolean) }
  def author_id?; end

  sig { returns(T.nilable(String)) }
  def blob_id; end

  sig { params(value: T.nilable(String)).void }
  def blob_id=(value); end

  sig { returns(T::Boolean) }
  def blob_id?; end

  sig { returns(String) }
  def blob_path; end

  sig { params(value: String).void }
  def blob_path=(value); end

  sig { returns(T::Boolean) }
  def blob_path?; end

  sig { returns(T.nilable(String)) }
  def body_html; end

  sig { params(value: T.nilable(String)).void }
  def body_html=(value); end

  sig { returns(T::Boolean) }
  def body_html?; end

  sig { returns(T.nilable(String)) }
  def canonical_url; end

  sig { params(value: T.nilable(String)).void }
  def canonical_url=(value); end

  sig { returns(T::Boolean) }
  def canonical_url?; end

  sig { returns(DateTime) }
  def created_at; end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(T.nilable(T.any(T::Array[T.untyped], T::Boolean, Float, T::Hash[T.untyped, T.untyped], Integer, String))) }
  def log_data; end

  sig { params(value: T.nilable(T.any(T::Array[T.untyped], T::Boolean, Float, T::Hash[T.untyped, T.untyped], Integer, String))).void }
  def log_data=(value); end

  sig { returns(T::Boolean) }
  def log_data?; end

  sig { returns(T.nilable(DateTime)) }
  def published_at; end

  sig { params(value: T.nilable(DateTime)).void }
  def published_at=(value); end

  sig { returns(T::Boolean) }
  def published_at?; end

  sig { returns(Integer) }
  def repository_id; end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { returns(T::Boolean) }
  def repository_id?; end

  sig { returns(String) }
  def slug; end

  sig { params(value: String).void }
  def slug=(value); end

  sig { returns(T::Boolean) }
  def slug?; end

  sig { returns(String) }
  def status; end

  sig { params(value: T.any(Integer, String, Symbol)).void }
  def status=(value); end

  sig { returns(T::Boolean) }
  def status?; end

  sig { returns(T.nilable(String)) }
  def summary; end

  sig { params(value: T.nilable(String)).void }
  def summary=(value); end

  sig { returns(T::Boolean) }
  def summary?; end

  sig { returns(T.nilable(String)) }
  def title; end

  sig { params(value: T.nilable(String)).void }
  def title=(value); end

  sig { returns(T::Boolean) }
  def title?; end

  sig { returns(T.nilable(T::Array[T.untyped])) }
  def topics; end

  sig { params(value: T.nilable(T::Array[T.untyped])).void }
  def topics=(value); end

  sig { returns(T::Boolean) }
  def topics?; end

  sig { returns(DateTime) }
  def updated_at; end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end
end

module Post::GeneratedAssociationMethods
  extend T::Sig

  sig { returns(::User) }
  def author; end

  sig { params(value: ::User).void }
  def author=(value); end

  sig { returns(::Repository) }
  def repository; end

  sig { params(value: ::Repository).void }
  def repository=(value); end
end

module Post::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Post]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Post]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Post]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Post)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Post) }
  def find_by_id!(id); end
end

class Post < ApplicationRecord
  include Post::EnumInstanceMethods
  include Post::GeneratedAttributeMethods
  include Post::GeneratedAssociationMethods
  extend Post::CustomFinderMethods
  extend T::Sig
  extend T::Generic

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def self.statuses; end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.children_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.not_published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.path_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.roots(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.to_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def self.with_log_data(*args); end

  sig { returns(Post::ActiveRecord_Relation) }
  def self.all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def self.only(*args, &block); end

  sig { params(args: T.untyped).returns(Post) }
  def self.find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Post)) }
  def self.find_by(*args); end

  sig { params(args: T.untyped).returns(Post) }
  def self.find_by!(*args); end

  sig { returns(T.nilable(Post)) }
  def self.first; end

  sig { returns(Post) }
  def self.first!; end

  sig { returns(T.nilable(Post)) }
  def self.second; end

  sig { returns(Post) }
  def self.second!; end

  sig { returns(T.nilable(Post)) }
  def self.third; end

  sig { returns(Post) }
  def self.third!; end

  sig { returns(T.nilable(Post)) }
  def self.third_to_last; end

  sig { returns(Post) }
  def self.third_to_last!; end

  sig { returns(T.nilable(Post)) }
  def self.second_to_last; end

  sig { returns(Post) }
  def self.second_to_last!; end

  sig { returns(T.nilable(Post)) }
  def self.last; end

  sig { returns(Post) }
  def self.last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def self.exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def self.one?(*args); end
end

class Post::ActiveRecord_Relation < ActiveRecord::Relation
  include Post::ActiveRelation_WhereNot
  include Post::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Post)

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def children_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def not_published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def path_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def roots(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def to_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_Relation) }
  def with_log_data(*args); end

  sig { returns(Post::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_Relation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Post) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Post)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Post) }
  def find_by!(*args); end

  sig { returns(T.nilable(Post)) }
  def first; end

  sig { returns(Post) }
  def first!; end

  sig { returns(T.nilable(Post)) }
  def second; end

  sig { returns(Post) }
  def second!; end

  sig { returns(T.nilable(Post)) }
  def third; end

  sig { returns(Post) }
  def third!; end

  sig { returns(T.nilable(Post)) }
  def third_to_last; end

  sig { returns(Post) }
  def third_to_last!; end

  sig { returns(T.nilable(Post)) }
  def second_to_last; end

  sig { returns(Post) }
  def second_to_last!; end

  sig { returns(T.nilable(Post)) }
  def last; end

  sig { returns(Post) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Post).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Post]) }
  def flatten(level); end

  sig { returns(T::Array[Post]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end
end

class Post::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Post::ActiveRelation_WhereNot
  include Post::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Post)

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def children_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def not_published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def path_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def roots(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def to_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def with_log_data(*args); end

  sig { returns(Post::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Post) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Post)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Post) }
  def find_by!(*args); end

  sig { returns(T.nilable(Post)) }
  def first; end

  sig { returns(Post) }
  def first!; end

  sig { returns(T.nilable(Post)) }
  def second; end

  sig { returns(Post) }
  def second!; end

  sig { returns(T.nilable(Post)) }
  def third; end

  sig { returns(Post) }
  def third!; end

  sig { returns(T.nilable(Post)) }
  def third_to_last; end

  sig { returns(Post) }
  def third_to_last!; end

  sig { returns(T.nilable(Post)) }
  def second_to_last; end

  sig { returns(Post) }
  def second_to_last!; end

  sig { returns(T.nilable(Post)) }
  def last; end

  sig { returns(Post) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Post).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Post]) }
  def flatten(level); end

  sig { returns(T::Array[Post]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end
end

class Post::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Post::CustomFinderMethods
  include Enumerable
  extend T::Sig
  extend T::Generic
  Elem = type_member(fixed: Post)

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def children_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def not_published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def path_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def published(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def roots(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def to_depth(*args); end

  sig { params(args: T.untyped).returns(Post::ActiveRecord_AssociationRelation) }
  def with_log_data(*args); end

  sig { returns(Post::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def unscoped(&block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def select(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def reselect(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def order(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def reorder(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def group(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def limit(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def offset(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def left_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def where(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def rewhere(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def preload(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def extract_associated(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def eager_load(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def includes(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def from(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def lock(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def readonly(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def or(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def having(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def create_with(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def distinct(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def references(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def none(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def unscope(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def merge(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def except(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::ActiveRecord_AssociationRelation) }
  def only(*args, &block); end

  sig { params(args: T.untyped).returns(Post) }
  def find(*args); end

  sig { params(args: T.untyped).returns(T.nilable(Post)) }
  def find_by(*args); end

  sig { params(args: T.untyped).returns(Post) }
  def find_by!(*args); end

  sig { returns(T.nilable(Post)) }
  def first; end

  sig { returns(Post) }
  def first!; end

  sig { returns(T.nilable(Post)) }
  def second; end

  sig { returns(Post) }
  def second!; end

  sig { returns(T.nilable(Post)) }
  def third; end

  sig { returns(Post) }
  def third!; end

  sig { returns(T.nilable(Post)) }
  def third_to_last; end

  sig { returns(Post) }
  def third_to_last!; end

  sig { returns(T.nilable(Post)) }
  def second_to_last; end

  sig { returns(Post) }
  def second_to_last!; end

  sig { returns(T.nilable(Post)) }
  def last; end

  sig { returns(Post) }
  def last!; end

  sig { params(conditions: T.untyped).returns(T::Boolean) }
  def exists?(conditions = nil); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def any?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def many?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def none?(*args); end

  sig { params(args: T.untyped).returns(T::Boolean) }
  def one?(*args); end

  sig { implementation.params(block: T.proc.params(e: Post).void).void }
  def each(&block); end

  sig { params(level: T.nilable(Integer)).returns(T::Array[Post]) }
  def flatten(level); end

  sig { returns(T::Array[Post]) }
  def to_a; end

  sig do
    type_parameters(:U).params(
        blk: T.proc.params(arg0: Elem).returns(T.type_parameter(:U)),
    )
    .returns(T::Array[T.type_parameter(:U)])
  end
  def map(&blk); end

  sig { params(records: T.any(Post, T::Array[Post])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Post, T::Array[Post])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Post, T::Array[Post])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Post, T::Array[Post])).returns(T.self_type) }
  def concat(*records); end
end
