# This is an autogenerated file for dynamic methods in Post
# Please rerun rake rails_rbi:models to regenerate.
# typed: ignore

class Post::Relation < ActiveRecord::Relation
  include Post::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Post)
end

class Post::CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Post::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Post)
end

class Post < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Post::ModelRelationShared
  extend Post::ClassMethods
  include Post::InstanceMethods
  Elem = type_template(fixed: Post)
end

module Post::InstanceMethods
  extend T::Sig

  sig { returns(T.nilable(String)) }
  def ancestry(); end

  sig { params(value: T.nilable(String)).void }
  def ancestry=(value); end

  sig { returns(T::Boolean) }
  def archived?(); end

  sig { returns(User) }
  def author(); end

  sig { params(value: User).void }
  def author=(value); end

  sig { returns(Integer) }
  def author_id(); end

  sig { params(value: Integer).void }
  def author_id=(value); end

  sig { returns(T.nilable(String)) }
  def blob_path(); end

  sig { params(value: T.nilable(String)).void }
  def blob_path=(value); end

  sig { returns(T.nilable(String)) }
  def body(); end

  sig { params(value: T.nilable(String)).void }
  def body=(value); end

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def draft?(); end

  sig { returns(T.nilable(String)) }
  def summary(); end

  sig { params(value: T.nilable(String)).void }
  def summary=(value); end

  sig { returns(Integer) }
  def id(); end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def published?(); end

  sig { returns(T.nilable(DateTime)) }
  def published_at(); end

  sig { params(value: T.nilable(DateTime)).void }
  def published_at=(value); end

  sig { returns(Repository) }
  def repository(); end

  sig { params(value: Repository).void }
  def repository=(value); end

  sig { returns(Integer) }
  def repository_id(); end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { returns(T.nilable(String)) }
  def slug(); end

  sig { params(value: T.nilable(String)).void }
  def slug=(value); end

  sig { returns(String) }
  def status(); end

  sig { params(value: T.any(Integer, String, Symbol)).void }
  def status=(value); end

  sig { returns(T.nilable(String)) }
  def title(); end

  sig { params(value: T.nilable(String)).void }
  def title=(value); end

  sig { returns(T.nilable(T::Array[T.untyped])) }
  def topics(); end

  sig { params(value: T.nilable(T::Array[T.untyped])).void }
  def topics=(value); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

end

module Post::ClassMethods
  extend T::Sig

  sig { returns(T::Hash[T.any(String, Symbol), Integer]) }
  def statuses(); end

end

module Post::ModelRelationShared
  extend T::Sig

  sig { returns(Post::Relation) }
  def all(); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def after_depth(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def ancestors_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def archived(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def at_depth(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def before_depth(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def children_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def descendants_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def draft(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def from_depth(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def indirects_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def not_archived(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def not_draft(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def not_published(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def ordered_by_ancestry(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def ordered_by_ancestry_and(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def path_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def published(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def roots(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def siblings_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def subtree_of(*args); end

  sig { params(args: T.untyped).returns(Post::Relation) }
  def to_depth(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def select(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def reselect(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def order(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def reorder(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def group(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def limit(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def offset(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def left_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def left_outer_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def where(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def rewhere(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def preload(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def extract_associated(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def eager_load(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def includes(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def from(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def lock(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def readonly(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def extending(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def or(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def having(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def create_with(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def distinct(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def references(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def none(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def unscope(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def optimizer_hints(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def merge(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def except(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Post::Relation) }
  def only(*args, block); end

end
