# This is an autogenerated file for dynamic methods in Repository
# Please rerun rake rails_rbi:models to regenerate.
# typed: ignore

class Repository::Relation < ActiveRecord::Relation
  include Repository::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Repository)
end

class Repository::CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Repository::ModelRelationShared
  extend T::Generic
  Elem = type_member(fixed: Repository)
end

class Repository < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Repository::ModelRelationShared
  extend Repository::ClassMethods
  include Repository::InstanceMethods
  Elem = type_template(fixed: Repository)
end

module Repository::InstanceMethods
  extend T::Sig

  sig { returns(User) }
  def author(); end

  sig { params(value: User).void }
  def author=(value); end

  sig { returns(Integer) }
  def author_id(); end

  sig { params(value: Integer).void }
  def author_id=(value); end

  sig { returns(String) }
  def commit_sha(); end

  sig { params(value: String).void }
  def commit_sha=(value); end

  sig { returns(DateTime) }
  def created_at(); end

  sig { params(value: DateTime).void }
  def created_at=(value); end

  sig { returns(String) }
  def full_name(); end

  sig { params(value: String).void }
  def full_name=(value); end

  sig { returns(Integer) }
  def id(); end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(String) }
  def name(); end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(String) }
  def path(); end

  sig { params(value: String).void }
  def path=(value); end

  sig { returns(ActiveRecord::Associations::CollectionProxy[T.untyped]) }
  def posts(); end

  sig { params(value: T.any(T::Array[Post], ActiveRecord::Associations::CollectionProxy[T.untyped])).void }
  def posts=(value); end

  sig { returns(DateTime) }
  def updated_at(); end

  sig { params(value: DateTime).void }
  def updated_at=(value); end

end

module Repository::ClassMethods
  extend T::Sig

end

module Repository::ModelRelationShared
  extend T::Sig

  sig { returns(Repository::Relation) }
  def all(); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def select(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def reselect(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def order(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def reorder(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def group(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def limit(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def offset(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def left_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def left_outer_joins(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def where(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def rewhere(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def preload(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def extract_associated(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def eager_load(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def includes(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def from(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def lock(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def readonly(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def extending(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def or(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def having(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def create_with(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def distinct(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def references(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def none(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def unscope(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def optimizer_hints(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def merge(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def except(*args, block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Repository::Relation) }
  def only(*args, block); end

end
