# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:helpers to regenerate.
module ActiveClassHelper
  include Kernel
  include ActionView::Helpers
end

module ApplicationHelper
  include Kernel
  include ActionView::Helpers
end

module PostHelper
  include Kernel
  include ActionView::Helpers
end