# typed: strong
# This is an autogenerated file for Rails routes.
# Please run rake rails_rbi:routes to regenerate.
class ActionController::Base
  include GeneratedUrlHelpers
end

module ActionView::Helpers
  include GeneratedUrlHelpers
end

module GeneratedUrlHelpers
  # Sigs for route /
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def authenticated_root_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def authenticated_root_url(*args, **kwargs); end

  # Sigs for route /
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_url(*args, **kwargs); end

  # Sigs for route /sw(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def sw_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def sw_url(*args, **kwargs); end

  # Sigs for route /manifest(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def manifest_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def manifest_url(*args, **kwargs); end

  # Sigs for route /signin/token(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_token_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_token_index_url(*args, **kwargs); end

  # Sigs for route /signin(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signins_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signins_url(*args, **kwargs); end

  # Sigs for route /signin/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_url(*args, **kwargs); end

  # Sigs for route /signup(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signups_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signups_url(*args, **kwargs); end

  # Sigs for route /check_nicknames(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_nicknames_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_nicknames_url(*args, **kwargs); end

  # Sigs for route /check_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_emails_url(*args, **kwargs); end

  # Sigs for route /magic_logins(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def magic_logins_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def magic_logins_url(*args, **kwargs); end

  # Sigs for route /autocomplete/topics(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def autocomplete_topics_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def autocomplete_topics_url(*args, **kwargs); end

  # Sigs for route /me/settings(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_url(*args, **kwargs); end

  # Sigs for route /me/settings/profile(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_profiles_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_profiles_url(*args, **kwargs); end

  # Sigs for route /me/settings/ssh(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_keys_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_keys_url(*args, **kwargs); end

  # Sigs for route /me/settings/ssh/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_settings_ssh_key_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /me/settings/ssh/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_settings_ssh_key_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /me/settings/ssh/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_key_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /me/settings/repository(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_repositories_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_repositories_url(*args, **kwargs); end

  # Sigs for route /images(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def images_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def images_url(*args, **kwargs); end

  # Sigs for route /images/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def image_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def image_url(*args, **kwargs); end

  # Sigs for route /p/:post_slug/publish(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_publish_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_publish_index_url(*args, **kwargs); end

  # Sigs for route /p(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def posts_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def posts_url(*args, **kwargs); end

  # Sigs for route /p/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_post_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_post_url(*args, **kwargs); end

  # Sigs for route /p/:slug/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_post_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_post_url(*args, **kwargs); end

  # Sigs for route /p/:slug(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_url(*args, **kwargs); end

  # Sigs for route /mobius/post_receive(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def mobius_post_receive_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def mobius_post_receive_index_url(*args, **kwargs); end

  # Sigs for route /:user_nickname/images/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_image_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_image_url(*args, **kwargs); end

  # Sigs for route /:user_nickname/drafts(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_drafts_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_drafts_url(*args, **kwargs); end

  # Sigs for route /:user_nickname/:slug(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_post_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_post_url(*args, **kwargs); end

  # Sigs for route /:user_nickname/:slug(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_repository_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_repository_url(*args, **kwargs); end

  # Sigs for route /:nickname(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_url(*args, **kwargs); end

  # Sigs for route /pages/*id
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def page_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def page_url(*args, **kwargs); end
end
