# This is an autogenerated file for routes helper methods

# typed: strong
class ActionController::Base
  extend T::Sig

  # Sigs for route /
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def authenticated_root_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def authenticated_root_url(*args, **kwargs); end

  # Sigs for route /
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_url(*args, **kwargs); end

  # Sigs for route /signin(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signins_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signins_url(*args, **kwargs); end

  # Sigs for route /signin/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signin_url(*args, **kwargs); end

  # Sigs for route /signup(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signups_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def signups_url(*args, **kwargs); end

  # Sigs for route /check_nicknames(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_nicknames_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_nicknames_url(*args, **kwargs); end

  # Sigs for route /check_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_emails_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def check_emails_url(*args, **kwargs); end

  # Sigs for route /magic_logins(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def magic_logins_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def magic_logins_url(*args, **kwargs); end

  # Sigs for route /u(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def users_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def users_url(*args, **kwargs); end

  # Sigs for route /u/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_user_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_user_url(*args, **kwargs); end

  # Sigs for route /u/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_user_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_user_url(*args, **kwargs); end

  # Sigs for route /u/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def user_url(*args, **kwargs); end

  # Sigs for route /p/:post_id/publish(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_publish_index_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_publish_index_url(*args, **kwargs); end

  # Sigs for route /p(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def posts_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def posts_url(*args, **kwargs); end

  # Sigs for route /p/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_post_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_post_url(*args, **kwargs); end

  # Sigs for route /p/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_post_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_post_url(*args, **kwargs); end

  # Sigs for route /p/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def post_url(*args, **kwargs); end

  # Sigs for route /images(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def images_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def images_url(*args, **kwargs); end

  # Sigs for route /images/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def image_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def image_url(*args, **kwargs); end

  # Sigs for route /settings(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_url(*args, **kwargs); end

  # Sigs for route /settings/profile(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_profiles_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_profiles_url(*args, **kwargs); end

  # Sigs for route /settings/ssh(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_keys_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_keys_url(*args, **kwargs); end

  # Sigs for route /settings/ssh/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_settings_ssh_key_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /settings/ssh/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_settings_ssh_key_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /settings/ssh/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_key_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def settings_ssh_key_url(*args, **kwargs); end

  # Sigs for route /mobius/post_receive(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def mobius_post_receive_index_path(*args, **kwargs); end
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def mobius_post_receive_index_url(*args, **kwargs); end

end
