name: Chuspace
on: [push, pull_request]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: chuspace_test
          POSTGRES_PASSWORD: ''
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
          sudo apt-get install -y default-jdk
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
          sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          wget https://selenium-release.storage.googleapis.com/3.13/selenium-server-standalone-3.13.0.jar
          xvfb-run java -Dwebdriver.chrome.driver=/usr/bin/chromedriver -jar selenium-server-standalone.jar

          gem install bundler
          bundle install
          yarn install

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails assets:precompile

      - name: Run Rubocop
        run: bin/rubocop
      - name: Run Bundler Audit
        run: bin/bundler-audit --update
      - name: Run Brakeman
        run: bin/brakeman -q -w2
      - name: Run tests
        run: bundle exec rails test
      - name: Run system tests
        run: bundle exec rails test:system
